import {it,expect} from 'vitest';
import {growthPlan,firstGrowthIds} from '../harness/fixtures/growth-opportunity';
import {r2CreateJoker} from '../src/domain/r2Run';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {r2SelectionFacts} from '../src/domain/r2SelectionFacts';
import {growthOpportunity} from '../src/game/GrowthOpportunity';
import {publicJokerMemoryContext} from '../src/game/JokerMemory';
import {selectionExperience} from '../src/game/JokerExperience';
import {transactionGrowthChange,handGrowthChanges} from '../src/game/SavedGrowthChange';
import {applyCommand,createRun} from '../src/domain/run';
import {r2Price} from '../src/domain/r2Shop';
import {Rational} from '../src/domain/rational';
const scene=(id:string)=>{const s=growthPlan('d03');s.jokers=[r2CreateJoker(id,'unit/'+id,4,'none',s)];s.stage!.initialJokerIds=s.jokers.map(j=>j.instanceId);return s;};
const context=(s:ReturnType<typeof scene>,ids=firstGrowthIds,limited=false)=>{const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);return publicJokerMemoryContext(s,{hand,facts:r2SelectionFacts({hand,selectedIds:ids,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),disabledIds:s.stage!.disabledIds}),scoringLimited:limited,deckSize:52,jokerSlots:5,jokerCount:1});};
it('eight previously omitted families use their identity rule and actual action clock',()=>{
 for(const [id,action] of [['a06','play'],['e05','shop'],['c05','discard'],['e06','shop'],['f05','play'],['e11','clear'],['e12','shop'],['f12','clear']]){const s=scene(id),g=growthOpportunity(s,s.jokers[0],context(s));expect(g).toBeDefined();expect(g!.action).toBe(action);expect(g!.status).not.toBe('ready');expect(g!.body).toContain('保存');}
});
it('a06 distinguishes first-hand preparation, same type, true alternation, used quota and clipped cap',()=>{
 const s=scene('a06');expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('prepare');s.stage!.previousHandType='two-pair';expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('unmet');s.stage!.previousHandType='straight';let g=growthOpportunity(s,s.jokers[0],context(s))!;expect(g.status).toBe('ready');expect(g.body).toContain('×1.15');expect(selectionExperience(s,s.jokers[0],context(s)).readiness).toBe('ready');s.jokers[0].counters={alternationUsed:true};expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('used');expect(selectionExperience(s,s.jokers[0],context(s)).readiness).toBe('unmet');s.jokers[0].counters={alternationUsed:false};s.jokers[0].growth.coefficient={n:'999999',d:'1'};g=growthOpportunity(s,s.jokers[0],context(s))!;expect(g.delta).toEqual({n:'1',d:'1'});s.jokers[0].growth.coefficient={n:'1000000',d:'1'};expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('capped');
});
it('a06 after-hand growth survives score suppression without pretending that multiplier was read',()=>{const s=scene('a06');s.stage!.previousHandType='straight';const g=growthOpportunity(s,s.jokers[0],context(s,firstGrowthIds,true))!;expect(g.status).toBe('ready');expect(g.body).toContain('本手计分停用');expect(selectionExperience(s,s.jokers[0],context(s,firstGrowthIds,true)).readiness).toBe('limited');});
it('c05 uses discarded cards including disabled cards, discard budget and actual saved delta',()=>{
 const s=scene('c05'),hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);const pair=hand.filter(c=>c.suit==='hearts').slice(0,2).map(c=>c.id);expect(pair).toHaveLength(2);const c=context(s,pair);c.disabledIds=pair;expect(growthOpportunity(s,s.jokers[0],c)!.status).toBe('ready');expect(selectionExperience(s,s.jokers[0],c).readiness).toBe('pending');s.stage!.discardsLeft=0;expect(growthOpportunity(s,s.jokers[0],context(s,pair))!.status).toBe('unmet');s.stage!.discardsLeft=3;const command={runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'DiscardHand' as const,selectedIds:pair}};const before=structuredClone(s),r=applyCommand(s,command);expect(r.ok).toBe(true);if(!r.ok)return;const event=r.events.find(e=>e.type==='joker-transaction'&&e.definitionId==='c05');expect(event?.type).toBe('joker-transaction');if(event?.type==='joker-transaction')expect(transactionGrowthChange(before,r.state,event)).toContain('+0→+40');expect(s).toEqual(before);expect(r.state.jokers[0].growth.pendingHeat).toEqual({n:'40',d:'1'});
});
it('c05 cap clips pending heat, and depleted boss discard budget cannot light a source',()=>{const s=scene('c05'),hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);const ids=hand.filter(c=>c.suit==='hearts').slice(0,2).map(c=>c.id);s.jokers[0].growth.pendingHeat={n:'60',d:'1'};expect(growthOpportunity(s,s.jokers[0],context(s,ids))!.delta).toEqual({n:'20',d:'1'});s.stage!.doubleDiscardBeforeFirstPlay=true;s.stage!.discardsLeft=1;expect(growthOpportunity(s,s.jokers[0],context(s,ids))!.status).toBe('unmet');s.jokers[0].growth.pendingHeat={n:'80',d:'1'};expect(growthOpportunity(s,s.jokers[0],context(s,ids))!.status).toBe('capped');});
it('f05 remains result-only even at cap, names baseline and reset instead of forecasting score',()=>{const s=scene('f05');let g=growthOpportunity(s,s.jokers[0],context(s))!;expect(g.status).toBe('waiting');expect(g.body).toContain('建立比分基线');s.stage!.previousHandScore='100';s.jokers[0].growth.multiplier={n:'4',d:'1'};g=growthOpportunity(s,s.jokers[0],context(s))!;expect(g.status).toBe('waiting');expect(g.body).toContain('封顶仍可能归零');expect(selectionExperience(s,s.jokers[0],context(s)).readiness).toBe('pending');});
it('e11 sale breaks this stage qualification, and f12 cannot promise clear from one remaining hand',()=>{const s=scene('e11');s.stage!.jokerSold=true;expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('unmet');expect(growthOpportunity(s,s.jokers[0],context(s))!.body).toContain('买回不恢复');const f=scene('f12');f.stage!.handsLeft=1;expect(growthOpportunity(f,f.jokers[0],context(f))!.status).toBe('waiting');expect(growthOpportunity(f,f.jokers[0],context(f))!.body).toContain('未提交牌不算过关');});
it('d09 and f11 actual score/retrigger conditions stay unlit until real results exist',()=>{for(const id of ['d09','f11']){const s=scene(id),c=context(s);expect(growthOpportunity(s,s.jokers[0],c)!.status).toBe('waiting');expect(selectionExperience(s,s.jokers[0],c).readiness).toBe('pending');}});
it('hidden deck order and RNG changes cannot affect any of the eight public opportunities',()=>{for(const id of ['a06','e05','c05','e06','f05','e11','e12','f12']){const s=scene(id),c=context(s),before=JSON.stringify(s),other=structuredClone(s);other.drawPile.reverse();for(const r of Object.values(other.rng))r.state=(r.state+19)>>>0;expect(growthOpportunity(other,other.jokers[0],c)).toEqual(growthOpportunity(s,s.jokers[0],c));expect(JSON.stringify(s)).toBe(before);}});
it('saved hand change requires actual source events, and zero/reset is not positive growth',()=>{const s=scene('f05');const before=structuredClone(s),r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'PlayHand',selectedIds:firstGrowthIds}});expect(r.ok).toBe(true);if(!r.ok)return;expect(handGrowthChanges(before)).toEqual([]);expect(handGrowthChanges(r.state)).toEqual([]);const trace=structuredClone(r.state.lastTrace!);trace.events=[];expect(handGrowthChanges(r.state,trace)).toEqual([]);expect(Rational.fromJSON(r.state.jokers[0].growth.multiplier??{n:'0',d:'1'}).n).toBe(0n);});

it('committed purchase, sale and refresh give exact retained source deltas; missing identities are silent',()=>{
 for(const [id,type,key,want] of [['e05','BuyOffer','heat','8'],['e06','SellJoker','multiplier','1/2'],['e12','RerollShop','heat','3']] as const){
  const s=createRun({seed:'group-natural-17',runId:'unit/shop/'+id,characterId:'erxiang',rulesVersion:'r2',r2Profile:'group-upgrade-v1',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
  s.jokers=[r2CreateJoker(id,'unit/'+id,4,'none',s),r2CreateJoker('b03','unit/sold',4,'none',s)];
  const offer=s.shop!.offers[0];Object.assign(offer,{definitionId:'a05',price:r2Price('a05','none',s),edition:'none'});
  const action=type==='BuyOffer'?{type,offerId:offer.offerId}:type==='SellJoker'?{type,instanceId:'unit/sold'}:{type};
  const before=structuredClone(s),r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action});expect(r.ok).toBe(true);if(!r.ok)continue;
  const e=r.events.find(e=>e.type==='joker-transaction'&&e.definitionId===id);expect(e).toBeDefined();if(e?.type!=='joker-transaction')continue;
  const line=transactionGrowthChange(before,r.state,e)!;expect(line).toContain('已保存');expect(line).toContain('实际新增+');expect(Rational.fromJSON(r.state.jokers[0].growth[key]).toJSON()).toEqual(want==='1/2'?{n:'1',d:'2'}:{n:want,d:'1'});
  const missingBefore=structuredClone(before);missingBefore.jokers=[];expect(transactionGrowthChange(missingBefore,r.state,e)).toBeUndefined();const missingAfter=structuredClone(r.state);missingAfter.jokers=[];expect(transactionGrowthChange(before,missingAfter,e)).toBeUndefined();expect(s).toEqual(before);
 }
});
it('the old a06 identity has no new coefficient growth opportunity',()=>{const s=growthPlan('d03',true);s.jokers=[r2CreateJoker('a06','unit/old',4,'none',s)];s.stage!.initialJokerIds=['unit/old'];expect(growthOpportunity(s,s.jokers[0],context(s))).toBeUndefined();});
it('f05 real non-increase resets saved growth and reports a reduction without positive benefit',()=>{const s=scene('f05');s.stage!.previousHandScore='999999';s.jokers[0].growth.multiplier={n:'1',d:'1'};const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'PlayHand',selectedIds:firstGrowthIds}});expect(r.ok).toBe(true);if(!r.ok)return;expect(r.state.jokers[0].growth.multiplier).toEqual({n:'0',d:'1'});expect(handGrowthChanges(r.state)[0].line).toContain('实际减少1');});

it('e11/f12 actual clear growth is retained in trace and shared saved feedback',()=>{
 for(const id of ['e11','f12']){let s=scene(id);const main=['hearts-14','spades-14','clubs-14','diamonds-14'],weak=['hearts-2','spades-3','clubs-4'];const ids=[...main,...weak,'diamonds-5'];s.drawPile=[...s.drawPile,...s.handOrder].filter(x=>!ids.includes(x));s.handOrder=ids;
  const send=(selectedIds:string[])=>{const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'PlayHand',selectedIds}});expect(r.ok).toBe(true);if(r.ok)s=r.state;return r;};
  if(id==='f12')for(const x of weak)send([x]);const before=structuredClone(s),r=send(main);expect(s.phase).toBe('stage-cleared');expect(s.stage!.handsLeft).toBe(id==='f12'?0:3);expect(s.jokers[0].growth.coefficient).toEqual({n:'11',d:'10'});expect(handGrowthChanges(s)[0].line).toContain('×1→×1.1');if(!r.ok)continue;const e=r.events.find(e=>e.type==='joker-transaction'&&e.definitionId===id&&e.phase==='onStageClear');expect(e).toBeDefined();if(e?.type==='joker-transaction')expect(transactionGrowthChange(before,s,e)).toContain('过关后已保存 ×1→×1.1');
 }
});

it('consumed pending heat is a saved reduction, never newly grown heat',()=>{const s=scene('c05');s.jokers[0].growth.pendingHeat={n:'40',d:'1'};const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'PlayHand',selectedIds:firstGrowthIds}});expect(r.ok).toBe(true);if(!r.ok)return;expect(r.state.jokers[0].growth.pendingHeat).toEqual({n:'0',d:'1'});expect(handGrowthChanges(r.state)[0].line).toContain('实际减少40');});
