import {describe,it,expect} from 'vitest';
import {createRun,applyCommand,type R2RunState,type Action,type Command} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {stableHash} from '../src/domain/hash';
import {scoreR2Hand} from '../src/domain/scoreR2';
import {r2ScoreContext} from '../src/domain/r2Run';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {azaoChargeStep,emptyAzaoCharge} from '../src/domain/r2AzaoCharge';
import {SavedRun,type SaveStore,type SaveSlots} from '../src/application/SavedRun';
import {azaoChoice,savedAzaoCharge} from '../src/game/AzaoChargeCopy';
import {keyHighlight} from '../src/game/JokerKeyHighlight';
import {heroClimaxValue} from '../src/game/HeroClimax';
const main=['hearts-2','spades-2','clubs-14','diamonds-14'];
function start(){return createRun({seed:'group-natural-17',runId:'azao-charge',characterId:'azao',rulesVersion:'r2',r2Identity:newRunIdentity('azao','group'),openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});}
function send(s:R2RunState,action:Action,journal:Command[]=[]){const command={runId:s.runId,commandId:'c/'+s.commandSeq,expectedSeq:s.commandSeq,action},r=applyCommand(s,command);if(!r.ok)throw Error(r.code+JSON.stringify(r.diagnostic));journal.push(command);expect(readCheckpoint(makeCheckpoint(r.state,journal)).ok).toBe(true);return r.state;}
const entered=()=>send(send(start(),{type:'LeaveShop'}),{type:'EnterStage'});
function arranged(s:R2RunState,ids:string[]){s=structuredClone(s);s.handOrder=ids;s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!ids.includes(id)&&!s.playedPile.includes(id)&&!s.discardPile.includes(id));return s;}
function mutate(s:R2RunState,fn:(s:R2RunState)=>void){const cp=structuredClone(makeCheckpoint(s,[]));fn(cp.state);const {checksum,...body}=cp;return readCheckpoint({...body,checksum:stableHash(body)});}
function input(s:R2RunState,selectedIds:string[]){const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);return {rulesVersion:'r2' as const,runId:s.runId,rootId:s.runId+'/hand/test',hand,selectedIds,disabledIds:s.stage!.disabledIds,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),handLevels:s.handLevels,playIndex:s.stage!.playIndex+1,handsBeforePlay:s.stage!.handsLeft,previousHandType:s.stage!.previousHandType,wager:false,rng:s.rng.rule,...r2ScoreContext(s,hand,selectedIds)};}
describe('stage-local azao charge candidate',()=>{
 it('first ordinary two-pair gains one after commit; restore and duplicate do not gain twice',()=>{const s=entered();expect(s.handOrder).toEqual(expect.arrayContaining(main));const journal:Command[]=[],after=send(s,{type:'PlayHand',selectedIds:main},journal);expect(after.stage!.azaoCharge).toEqual({charge:1,previousQualifiedType:'two-pair'});expect(after.lastTrace!.events.filter(e=>e.sourceType==='character')).toEqual([]);const dup=applyCommand(after,journal[0]);expect(dup.ok&&dup.duplicate).toBe(true);if(dup.ok)expect(dup.state).toEqual(after);expect(readCheckpoint(makeCheckpoint(after,journal)).ok).toBe(true);});
 it('qualified repeat may release; holding the repeat clears both fields; discard preserves',()=>{let s=send(entered(),{type:'PlayHand',selectedIds:main});s=arranged(s,['spades-14','hearts-14','clubs-8','hearts-8','spades-3']);const discarded=send(s,{type:'DiscardHand',selectedIds:['spades-3']});expect(discarded.stage!.azaoCharge).toEqual(s.stage!.azaoCharge);const ids=['spades-14','hearts-14','clubs-8','hearts-8'];const hold=send(discarded,{type:'PlayHand',selectedIds:ids});expect(hold.lastTrace!.azaoCharge!.after).toEqual(emptyAzaoCharge());const release=send(discarded,{type:'PlayHand',selectedIds:ids,azaoRelease:true});expect(release.lastTrace!.azaoCharge!.before.charge).toBe(1);expect(release.lastTrace!.azaoCharge!.after).toEqual(emptyAzaoCharge());expect(release.lastTrace!.azaoCharge!.multiplier).toBe('1.5');expect(BigInt(release.lastTrace!.finalScore)).toBeGreaterThan(BigInt(hold.lastTrace!.finalScore));expect(release.lastTrace!.events.filter(e=>e.sourceType==='character').map(e=>e.operation)).toEqual(['multiply-multiplier']);});
 it('different adjacent qualified types cap at3; all release tiers use real scoring without old add1 or enhancements',()=>{let before=emptyAzaoCharge();for(const type of ['two-pair','three-kind','straight','flush'] as const)before=azaoChargeStep(type,{before,release:false},true).after;expect(before.charge).toBe(3);const s=entered(),base=input(s,main);for(const charge of [1,2,3] as const){const t=scoreR2Hand({...base,azaoCharge:{before:{charge,previousQualifiedType:'two-pair'},release:true}});expect(t.azaoCharge!.multiplier).toBe(['1.5','2.5','4'][charge-1]);expect(t.azaoCharge!.after).toEqual(emptyAzaoCharge());expect(t.events.filter(e=>e.sourceType==='character')).toHaveLength(1);expect(t.cards.some(c=>c.enhancement)).toBe(false);expect(t.events.length).toBeLessThanOrEqual(512);}});
 it('pair/high-card cannot release and holding clears; empty charge rejects without costing play or RNG',()=>{const s=entered();for(const ids of [main,['clubs-14'],['clubs-14','diamonds-14']]){const r=applyCommand(s,{runId:s.runId,commandId:'reject',expectedSeq:s.commandSeq,action:{type:'PlayHand',selectedIds:ids,azaoRelease:true}});expect(r.ok).toBe(false);expect(s.stage!.playIndex).toBe(0);expect(s.stage!.azaoCharge).toEqual(emptyAzaoCharge());}for(const type of ['pair','high-card'] as const){const intent={before:{charge:2 as const,previousQualifiedType:'straight' as const},release:false};expect(azaoChargeStep(type,intent,true).after).toEqual(emptyAzaoCharge());expect(()=>azaoChargeStep(type,{...intent,release:true},true)).toThrow('azao-release-unavailable');}});
 it('Q01 and B08 neither gain nor release; disabled release cannot spend a hand',()=>{const base=input(entered(),main);for(const disabled of [{...base,characterId:'neutral' as const},{...base,boss:{definitionId:'B08' as const,disabledSuit:null}}]){const t=scoreR2Hand(disabled);expect(t.azaoCharge!.after).toEqual(emptyAzaoCharge());expect(t.events.some(e=>e.sourceType==='character')).toBe(false);expect(()=>scoreR2Hand({...disabled,azaoCharge:{before:{charge:1,previousQualifiedType:'two-pair'},release:true}})).toThrow();}let q=createRun({seed:'challenge/q01/0',runId:'q',characterId:'azao',rulesVersion:'r2',r2Identity:newRunIdentity('azao','group'),openingRoute:'group',modeConfig:{mode:'challenge',difficulty:0,challengeId:'Q01',programsEnabled:false}});q=send(send(q,{type:'LeaveShop'}),{type:'EnterStage'});q=arranged(q,main);const after=send(q,{type:'PlayHand',selectedIds:main});expect(after.stage!.azaoCharge).toEqual(emptyAzaoCharge());expect(readCheckpoint(makeCheckpoint(after,[])).ok).toBe(true);});
 it('clear/next entry/abandon retain historical trace but clear live charge',()=>{const first=send(entered(),{type:'PlayHand',selectedIds:main});const second=arranged(first,['spades-14','hearts-14','clubs-8','hearts-8']);const cleared=send(second,{type:'PlayHand',selectedIds:second.handOrder,azaoRelease:true});expect(cleared.phase).toBe('stage-cleared');expect(cleared.stage!.azaoCharge).toEqual(emptyAzaoCharge());const next=send(send(send(cleared,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(next.stage!.azaoCharge).toEqual(emptyAzaoCharge());const abandon=send(first,{type:'AbandonRun'});expect(abandon.stage!.azaoCharge).toEqual(emptyAzaoCharge());expect(abandon.lastTrace!.azaoCharge!.after.charge).toBe(1);expect(savedAzaoCharge(abandon)).toContain('蓄势已清');});
 it('strict parsing rejects missing/live/transition/tier/character-event tampering',()=>{const first=send(entered(),{type:'PlayHand',selectedIds:main});for(const change of [(s:R2RunState)=>delete s.stage!.azaoCharge,(s:R2RunState)=>s.stage!.azaoCharge!.charge=3,(s:R2RunState)=>s.lastTrace!.azaoCharge!.before.charge=2,(s:R2RunState)=>s.lastTrace!.azaoCharge!.after.charge=3,(s:R2RunState)=>s.lastTrace!.azaoCharge!.multiplier='4'])expect(mutate(first,change).ok).toBe(false);});
 it('save failure holds original charge; retry same release candidate consumes once and restores',async()=>{let before=send(entered(),{type:'PlayHand',selectedIds:main});before=arranged(before,['spades-14','hearts-14','clubs-8','hearts-8']);let slots:SaveSlots={revision:1,current:makeCheckpoint(before,[]),previous:null},fail=true;const commits:string[]=[];const store:SaveStore={read:async()=>slots,commit:async(revision,cp,backup)=>{commits.push(JSON.stringify(cp));if(fail)throw Error('quota-exceeded');slots={revision:revision+1,current:cp,previous:backup};return slots.revision;}};const saved=SavedRun.restore(store,slots);const r=await saved.dispatch({type:'PlayHand',selectedIds:before.handOrder,azaoRelease:true});expect(r.ok).toBe(false);expect(saved.state).toEqual(before);fail=false;expect((await saved.retry()).ok).toBe(true);expect(commits[1]).toBe(commits[0]);expect(saved.state.stage!.azaoCharge!.charge).toBe(0);expect(SavedRun.restore(store,slots).state).toEqual(saved.state);expect((await saved.retry()).ok).toBe(false);});
 it('public choice needs selected qualification and shows consequence; saved repeat uses short hero cue',()=>{let before=send(entered(),{type:'PlayHand',selectedIds:main});expect(azaoChoice(before,'two-pair').available).toBe(true);expect(azaoChoice(before,'two-pair').hold).toContain('清空');expect(azaoChoice(before,'pair').available).toBe(false);before=arranged(before,['spades-14','hearts-14','clubs-8','hearts-8']);const after=send(before,{type:'PlayHand',selectedIds:before.handOrder,azaoRelease:true}),key=keyHighlight(after,after.lastTrace!,before.stage!.heat,undefined,false)!;expect(key.kind).toBe('multiply');expect(key.fact.title).toContain('主动爆发');expect(heroClimaxValue(after,after.lastTrace!,key)).toBeUndefined();});
});
