import {toolInfo} from '../src/game/r2ToolInfo';
import {expect,it} from 'vitest';
import {createRun,applyCommand,assertRunInvariants,type R2RunState,type Action} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {R2_ERXIANG_HANDOFF_HASH,R2_BASIC_TOOL_IDS,R2_TOOL_SUPPLY_HASH,R2_TOUYE_WAGER_VERSION,R2_TOUYE_WAGER_HASH} from '../src/domain/r2GroupUpgrade';
import {r2ToolPrice,r2ToolAcquisitionPool,drawR2BasicTool,r2BasicToolShelfStatus} from '../src/domain/r2Shop';
import {SeededRng} from '../src/core/SeededRng';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {SavedRun,type SaveSlots,type SaveStore} from '../src/application/SavedRun';
const start=()=>createRun({seed:'group-natural-17',runId:'basic-tools',characterId:'erxiang',rulesVersion:'r2',r2Identity:newRunIdentity('erxiang','group'),openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
const cmd=(s:R2RunState,action:Action)=>({runId:s.runId,commandId:'basic/'+s.commandSeq,expectedSeq:s.commandSeq,action});
const send=(s:R2RunState,a:Action)=>{const r=applyCommand(s,cmd(s,a));if(!r.ok)throw Error(r.code);assertRunInvariants(r.state);return r.state;};
it('normal six gold buys its four-gold route starter and a legal two-gold basic tool without restocking or capacity growth',()=>{const s=start();expect(s.contentHash).toBe(R2_ERXIANG_HANDOFF_HASH);expect(s.shop!.toolOffers).toHaveLength(2);expect(new Set(s.shop!.toolOffers.map(o=>o.definitionId)).size).toBe(2);const basic=s.shop!.toolOffers[1];expect(R2_BASIC_TOOL_IDS).toContain(basic.definitionId);expect(basic.price).toBe(2);const starter=s.shop!.offers.find(o=>o.definitionId==='mantangcai')!;const b=send(send(s,{type:'BuyOffer',offerId:starter.offerId}),{type:'BuyOffer',offerId:basic.offerId});expect(b.gold).toBe(0);expect(b.shop!.toolOffers.map(o=>o.offerId)).toEqual(s.shop!.toolOffers.map(o=>o.offerId));expect(b.shop!.toolOffers[1].consumed).toBe(true);expect(b.consumables).toHaveLength(1);expect(r2BasicToolShelfStatus(b)).toContain('已售罄');expect(readCheckpoint(makeCheckpoint(b,[]))).toMatchObject({ok:true});});
it('prices bind to the new identity; existing unsupported migration is not introduced and other tool prices remain unchanged',()=>{const s=start(),old={contentVersion:R2_TOUYE_WAGER_VERSION,contentHash:R2_TOUYE_WAGER_HASH};for(const id of R2_BASIC_TOOL_IDS){expect(r2ToolPrice(id,s)).toBe(2);expect(r2ToolPrice(id,old)).toBe(4);expect(toolInfo(id,s).cost).toContain('售价：2金');expect(toolInfo(id,old).cost).toContain('售价：4金');}expect(r2ToolPrice('T07',s)).toBe(6);expect(r2ToolPrice('T03',s)).toBe(4);});
it('basic acquisition excludes no-effect/end-point candidates, avoids duplicates and makes empty fallback explicit without a random draw',()=>{const s=start();s.deckInstances=s.deckInstances.slice(0,20).map(c=>({...c,rank:14,enhancement:'heat-paper'}));s.drawPile=s.deckInstances.map(c=>c.id);const pool=r2ToolAcquisitionPool(s);expect(pool.some(t=>t.id==='T02'||t.id==='T08'||t.id==='T10')).toBe(false);const rng=new SeededRng('basic-empty'),before=rng.snapshot();expect(drawR2BasicTool(rng,[])).toBeUndefined();expect(rng.snapshot()).toEqual(before);const only=pool.filter(t=>t.id==='T09');expect(drawR2BasicTool(rng,only,'T09')).toBeUndefined();expect(rng.snapshot()).toEqual(before);s.shop!.toolOffers=[];expect(r2BasicToolShelfStatus(s)).toContain('缺货');});
it('refresh remains two gold initially, saves distinct new IDs, retains items and replays deterministically',()=>{const s=start(),n=send(s,{type:'RerollShop'});expect(n.gold).toBe(4);expect(n.shop!.rerollCount).toBe(1);expect(n.shop!.toolOffers).toHaveLength(2);expect(n.shop!.itemOffers).toEqual(s.shop!.itemOffers);expect(n.shop!.toolOffers.map(o=>o.offerId)).not.toEqual(s.shop!.toolOffers.map(o=>o.offerId));expect(send(s,{type:'RerollShop'})).toEqual(n);expect(readCheckpoint(makeCheckpoint(n,[]))).toMatchObject({ok:true});});
it('rejects forged price, duplicate products and excess capacity in current saved shelves',()=>{for(const mutate of [(s:R2RunState)=>s.shop!.toolOffers[1].price=4,(s:R2RunState)=>s.shop!.toolOffers.push({...s.shop!.toolOffers[1],offerId:'third'}),(s:R2RunState)=>s.shop!.toolOffers[1]={...s.shop!.toolOffers[0],offerId:'duplicate'}]){const checkpoint=structuredClone(makeCheckpoint(start(),[]));mutate(checkpoint.state);expect(readCheckpoint(checkpoint).ok).toBe(false);}});
class Store implements SaveStore {slots:SaveSlots={revision:0,current:null,previous:null};fail=false;writes=0;async read(){return structuredClone(this.slots);}async commit(revision:number,current:ReturnType<typeof makeCheckpoint>,previous:ReturnType<typeof makeCheckpoint>|null){this.writes++;if(this.fail)throw Error('save-failed');if(revision!==this.slots.revision)throw Error('conflict');this.slots={revision:revision+1,current:structuredClone(current),previous:structuredClone(previous)};return revision+1;}}
for(const kind of ['buy','refresh'] as const)it('failed '+kind+' retains state and exact pending shelf across retry and duplicate',async()=>{const s=start(),store=new Store(),run=await SavedRun.start(store,s,await store.read()),before=run.state,slots=await store.read();store.fail=true;const c=cmd(before,kind==='buy'?{type:'BuyOffer',offerId:s.shop!.toolOffers[1].offerId}:{type:'RerollShop'});expect((await run.submit(c)).ok).toBe(false);expect(run.state).toBe(before);expect(await store.read()).toEqual(slots);const pending=run.exportJSON();store.fail=false;expect((await run.retry()).ok).toBe(true);expect(run.exportJSON()).toBe(pending);const writes=store.writes;expect(await run.submit(c)).toMatchObject({ok:true,duplicate:true});expect(store.writes).toBe(writes);expect(readCheckpoint(JSON.parse(pending))).toMatchObject({ok:true});});
