import {it,expect} from 'vitest';
import {buildJourneyPlan,journeySend} from '../harness/fixtures/build-journey';
import {buildJourneyFacts,cashDecision,currentBuildFocus,chooseBuildFocus,BUILD_FOCUS,jokerSupportsFocus} from '../src/game/BuildJourney';
import {r2PurchasePrice} from '../src/domain/r2Shop';
import {createRun} from '../src/domain/run';
it('a UI focus stays outside complete run/RNG and does not carry into another run',()=>{const s=buildJourneyPlan(),before=JSON.stringify(s);chooseBuildFocus(s.runId,'group');expect(currentBuildFocus(s.runId)).toBe('group');expect(currentBuildFocus('other-run')).toBeUndefined();expect(JSON.stringify(s)).toBe(before);});
it('three directions report current deck counts, compatible holdings and tools without future order',()=>{const s=buildJourneyPlan(),before=JSON.stringify(s);for(const f of BUILD_FOCUS){const facts=buildJourneyFacts(s,f);expect(facts.deckSize).toBe(52);expect(facts.owned.some(o=>o.title==='练对子')).toBe(true);expect(facts.composition).not.toContain('下一张');expect(facts.tools.map(t=>t.id)).toContain('controlled/T01');}expect(buildJourneyFacts(s,'flush').tools.map(t=>t.id)).toContain('controlled/T04');expect(buildJourneyFacts(s,'straight').tools.map(t=>t.id)).not.toContain('controlled/T04');expect(JSON.stringify(s)).toBe(before);});
it('comparison reads final discounted price and explains current cash tiers rather than promising income',()=>{const s=buildJourneyPlan();s.longTermItems=['U10'];s.shop!.purchases=0;s.purchaseCoupons=1;const f=buildJourneyFacts(s,'group');for(const o of f.offers){const raw=[...s.shop!.offers,...s.shop!.toolOffers,...s.shop!.itemOffers].find(r=>r.offerId===o.id)!;expect(o.title).toContain('实付'+r2PurchasePrice(s,raw));expect(o.body).toContain('不是现在到账或下场保证收入');}expect(cashDecision(s,11).afterTier).toBe(0);expect(cashDecision(s,100).after).toBe(-85);});
it('missing components and cash keep an honest alternate route and retain all ownership',()=>{const s=buildJourneyPlan(true),before=JSON.stringify(s);for(const focus of BUILD_FOCUS){const f=buildJourneyFacts(s,focus);expect(f.owned).toHaveLength(0);expect(f.tools).toHaveLength(0);expect(f.gaps).toHaveLength(2);expect(f.offers.every(o=>!o.affordable)).toBe(true);expect(f.gaps.join()).toContain('先看公开可成牌型');}expect(JSON.stringify(s)).toBe(before);});
it('using a real held tool changes only its committed public target and the next snapshot reports the result',()=>{const s=buildJourneyPlan(),target=s.deckInstances.find(c=>c.suit!=='diamonds')!,rng=structuredClone(s.rng),before=buildJourneyFacts(s,'flush').composition,used=journeySend(s,{type:'UseConsumable',instanceId:'controlled/T04',targetIds:[target.id]});expect(used.deckInstances.find(c=>c.id===target.id)!.suit).toBe('diamonds');expect(used.consumables.map(c=>c.instanceId)).not.toContain('controlled/T04');expect(buildJourneyFacts(used,'flush').composition).not.toBe(before);expect(used.rng).toEqual(rng);});
it('profile-bound holdings never borrow the new profile group contract for an old run',()=>{const s=createRun({seed:'old-build',runId:'old-build',characterId:'erxiang',rulesVersion:'r2'});expect(jokerSupportsFocus(s,'b06','group')).toBe(true);expect(jokerSupportsFocus(s,'b06','straight')).toBe(false);const newer=buildJourneyPlan();expect(buildJourneyFacts(newer,'straight').owned[0].body).toContain('成组');});
it('ordinary straight and flush really read carried growth without adding group growth',async()=>{const {buildTransitionPlan}=await import('../harness/fixtures/build-journey');for(const focus of ['straight','flush'] as const){const p=buildTransitionPlan(focus),played=journeySend(p.state,{type:'PlayHand',selectedIds:p.selected}),trace=played.lastTrace!;expect(trace.handType).toBe(focus);expect(trace.events.some(e=>e.sourceDefinitionId==='b10'&&e.operation==='read-growth'&&e.value.n==='20')).toBe(true);expect(trace.events.some(e=>e.sourceDefinitionId==='b10'&&e.operation==='add-growth')).toBe(false);expect(played.jokers.find(j=>j.definitionId==='b10')!.growth.heat).toEqual({n:'20',d:'1'});expect(buildJourneyFacts(played,focus).saved.some(c=>c.body.includes('读取已有 20 热度'))).toBe(true);}});

it('an unowned zero-growth source is not presented as a ready investment for a transfer lane',()=>{const s=buildJourneyPlan(true);expect(jokerSupportsFocus(s,'b10','group')).toBe(true);expect(jokerSupportsFocus(s,'b10','straight')).toBe(false);expect(jokerSupportsFocus(s,'b10','flush')).toBe(false);const held=buildJourneyPlan();expect(jokerSupportsFocus(held,'b10','flush')).toBe(true);});
it('existing per-card and repeat bridges remain available across route changes without inventing growth',async()=>{const {toolSupportsFocus}=await import('../src/game/BuildJourney');const s=buildJourneyPlan(true);for(const f of BUILD_FOCUS){expect(jokerSupportsFocus(s,'c02',f)).toBe(true);expect(jokerSupportsFocus(s,'c03',f)).toBe(true);expect(toolSupportsFocus('T15',f)).toBe(true);expect(toolSupportsFocus('T18',f)).toBe(true);}expect(jokerSupportsFocus(s,'c05','straight')).toBe(true);expect(jokerSupportsFocus(s,'c05','flush')).toBe(false);expect(jokerSupportsFocus(s,'c06','straight')).toBe(true); // Same-suit straight is an optional crossover, not ordinary-straight growth.
expect(toolSupportsFocus('P06','straight')).toBe(false);});
it('a late discovered chosen direction leads T01 choices while caps and other free choices remain',async()=>{const {focusedUpgradeTypes}=await import('../src/game/BuildJourney');const s=buildJourneyPlan();s.handLevels={'high-card':2,pair:3,straight:1,flush:30};const before=JSON.stringify(s);expect(focusedUpgradeTypes(s,'straight')).toEqual(['straight','high-card','pair']);expect(focusedUpgradeTypes(s,'flush')).toEqual(['high-card','pair','straight']);expect(focusedUpgradeTypes(s,undefined)).toEqual(['high-card','pair','straight']);expect(JSON.stringify(s)).toBe(before);});
