import {it,expect} from 'vitest';
import {buildJourneyPlan,buildTransitionPlan,journeySend} from '../harness/fixtures/build-journey';
import {buildGrowthProgress} from '../src/game/BuildGrowthProgress';
it('current holdings are authoritative without mutating state or inventing a saved gain',()=>{const s=buildJourneyPlan(),before=JSON.stringify(s),p=buildGrowthProgress(s)[0];expect(p.current).toBe('20');expect(p.before).toBeUndefined();expect(p.next).toContain('下手试');expect(JSON.stringify(s)).toBe(before);});
it('a non-growth hand keeps its real saved value and does not claim the hand caused growth',()=>{const p=buildTransitionPlan('straight'),s=journeySend(p.state,{type:'PlayHand',selectedIds:p.selected}),g=buildGrowthProgress(s)[0];expect(g.current).toBe('20');expect(g.cause).toBe('上手未新增，已存值保留');expect(g.before).toBeUndefined();});
it('sold and replacement instances cannot borrow saved source history',()=>{const p=buildTransitionPlan('flush'),s=journeySend(p.state,{type:'PlayHand',selectedIds:p.selected});s.jokers[0].instanceId='replacement';expect(buildGrowthProgress(s)[0].cause).toBe('从当前保存值继续培养');s.jokers=[];expect(buildGrowthProgress(s)).toEqual([]);});
it('zero is a readable start and each offer gives finite real cash and rule copy',()=>{const s=buildJourneyPlan();s.jokers[0].growth.heat={n:'0',d:'1'};expect(buildGrowthProgress(s)[0].metric).toContain('+0');});

it('an absent growth key starts at domain zero rather than hiding the owned source',()=>{const s=buildJourneyPlan();s.jokers[0].growth={};expect(buildGrowthProgress(s)[0].current).toBe('0');});
it('a real group hand records zero-to-ten separately from the current cumulative value',()=>{const p=buildTransitionPlan('straight');p.state.jokers[0].growth={};const ids=p.selected.slice(0,4);for(const [i,id] of ids.entries())p.state.deckInstances.find(c=>c.id===id)!.rank=i<2?7:8;const s=journeySend(p.state,{type:'PlayHand',selectedIds:ids}),before=JSON.stringify(s),g=buildGrowthProgress(s)[0];expect(g.before).toBe('0');expect(g.after).toBe('10');expect(g.current).toBe('10');expect(g.cause).toContain('两对');expect(JSON.stringify(s)).toBe(before);s.jokers[0].growth.heat={n:'25',d:'1'};expect(buildGrowthProgress(s)[0].current).toBe('25');expect(buildGrowthProgress(s)[0].cause).toContain('上手');});
