import type {R2ModeSelection} from '../src/content/r2Modes';
import {describe,it,expect,vi} from 'vitest';
import {createRun,applyCommand,type R2RunState,type Action,type Command} from '../src/domain/run';
import {newRunIdentity,launchIdentity} from '../src/game/RunLaunch';
import {r2CreateJoker,r2ScoreContext} from '../src/domain/r2Run';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {R2_TOOL_SUPPLY_VERSION,R2_TOOL_SUPPLY_HASH} from '../src/domain/r2GroupUpgrade';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {SavedRun,type SaveSlots,type SaveStore} from '../src/application/SavedRun';
import {stableHash} from '../src/domain/hash';
import {erxiangChoice,savedErxiangHandoff} from '../src/game/ErxiangHandoffCopy';
import {r2SelectionFacts} from '../src/domain/r2SelectionFacts';
import * as scoring from '../src/domain/scoreR2';
const mode={mode:'standard' as const,difficulty:0 as const,challengeId:null,programsEnabled:false};
const pair=['spades-8','hearts-8'];
const command=(s:R2RunState,action:Action):Command=>({runId:s.runId,commandId:'handoff/'+s.commandSeq,expectedSeq:s.commandSeq,action});
const send=(s:R2RunState,action:Action,journal:Command[]=[])=>{const c=command(s,action),r=applyCommand(s,c);if(!r.ok)throw Error(r.code+JSON.stringify(r.diagnostic));journal.push(c);const check=readCheckpoint(makeCheckpoint(r.state,journal));expect(check).toMatchObject({ok:true});return r.state;};
function start(config:R2ModeSelection=mode,identity=newRunIdentity('erxiang','group')){return createRun({seed:config.mode==='challenge'?'challenge/q01/0':'group-natural-17',runId:'handoff-test',characterId:'erxiang',rulesVersion:'r2',r2Identity:identity,openingRoute:'group',modeConfig:config});}
function entered(){return send(send(start(),{type:'LeaveShop'}),{type:'EnterStage'});}
function arrange(s:R2RunState,ids:string[]){s=structuredClone(s);s.handOrder=[...ids];s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!ids.includes(id)&&!s.playedPile.includes(id)&&!s.discardPile.includes(id));return s;}
function ready(){return arrange(entered(),[...pair,'clubs-2','diamonds-4','spades-6','hearts-9','clubs-11','diamonds-12']);}
function tamper(s:R2RunState,change:(s:R2RunState)=>void,journal:Command[]=[]){const cp=structuredClone(makeCheckpoint(s,journal));change(cp.state);const {checksum,...body}=cp;return readCheckpoint({...body,checksum:stableHash(body)});}
function score(s:R2RunState,ids:string[],targetId:string|null){const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);return scoring.scoreR2Hand({rulesVersion:'r2',runId:s.runId,rootId:'paper',hand,selectedIds:ids,disabledIds:s.stage!.disabledIds,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),handLevels:s.handLevels,playIndex:s.stage!.playIndex+1,handsBeforePlay:s.stage!.handsLeft,previousHandType:s.stage!.previousHandType,wager:false,rng:s.rng.rule,...r2ScoreContext(s,hand,ids),erxiangHandoff:{targetId,beforeUsed:s.stage!.erxiangHandoffUsed!}});}
describe('Erxiang first ordinary points handoff',()=>{
 it('ordinary88 commits430 with one source event and retains original102 without passive',()=>{const s=ready(),journal:Command[]=[],a=send(s,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]},journal);expect(a.lastTrace!.finalScore).toBe('430');expect(a.lastTrace!.accumulator).toEqual({H:{n:'43',d:'1'},M:{n:'10',d:'1'}});expect(a.lastTrace!.erxiangHandoff).toEqual({targetId:pair[0],beforeUsed:false,points:8,afterUsed:true});expect(a.lastTrace!.events.filter(e=>e.sourceType==='character')).toHaveLength(1);expect(a.phase).toBe('stage-cleared');expect(s.stage!.erxiangHandoffUsed).toBe(false);expect(score(s,pair,null).finalScore).toBe('102');expect(savedErxiangHandoff(a)).toContain('8点热度 → 倍率');const duplicate=applyCommand(a,journal[0]);expect(duplicate.ok&&duplicate.duplicate).toBe(true);if(duplicate.ok)expect(duplicate.state).toEqual(a);const next=send(send(send(a,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(next.stage!.erxiangHandoffUsed).toBe(false);});
 it('weak22 is148, remaining same-stage ordinary plays have no old passive, no second activation',()=>{const s=arrange(ready(),['spades-2','hearts-2',...pair,'clubs-4','diamonds-6','clubs-11','diamonds-12']),a=send(s,{type:'PlayHand',selectedIds:['spades-2','hearts-2'],erxiangTargetId:'spades-2'});expect(a.lastTrace!.finalScore).toBe('148');expect(a.phase).toBe('await-input');expect(applyCommand(a,command(a,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'erxiang-already-used'}});const b=send(a,{type:'PlayHand',selectedIds:pair});expect(b.lastTrace!.finalScore).toBe('102');expect(b.stage!.erxiangHandoffUsed).toBe(true);expect(b.lastTrace!.erxiangHandoff!.points).toBe(0);});
 for(const [name,ids,target] of [['straight',['spades-4','hearts-5','clubs-6','diamonds-7','hearts-8'],'clubs-6'],['flush',['clubs-2','clubs-4','clubs-7','clubs-9','clubs-13'],'clubs-7']] as const)it(name+' can use any final core without a rank pair',()=>{const s=arrange(ready(),[...ids]),base=score(s,[...ids],null),a=send(s,{type:'PlayHand',selectedIds:ids,erxiangTargetId:target});expect(a.lastTrace!.handType).toBe(name);const p=a.lastTrace!.erxiangHandoff!.points;expect(BigInt(a.lastTrace!.accumulator.H.n)).toBe(BigInt(base.accumulator.H.n)-BigInt(p));expect(BigInt(a.lastTrace!.accumulator.M.n)).toBe(BigInt(base.accumulator.M.n)+BigInt(p));});
 it('retrigger/edition/enhancement only redirect first ordinary execution; whole Joker and growth clocks unchanged',()=>{let s=ready();s.deckInstances.find(c=>c.id===pair[0])!.enhancement='encore-paper';s.deckInstances.find(c=>c.id===pair[0])!.edition='foil';s.jokers=[r2CreateJoker('b06','repeat',6,'none',s),r2CreateJoker('b10','grow',4,'none',s)];s.stage!.initialJokerIds=s.jokers.map(j=>j.instanceId);const base=score(s,pair,null),a=send(s,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]});const t=a.lastTrace!,ordinary=t.events.filter(e=>e.sourceType==='card'&&e.sourceDefinitionId==='rank-8'&&e.targetCardId===pair[0]);expect(ordinary.map(e=>[e.retriggerDepth,e.value.n])).toEqual([[0,'0'],[1,'8'],[1,'8']]);expect(t.events.filter(e=>e.reasonKey==='erxiang.handoff')).toHaveLength(1);expect(t.events.filter(e=>e.reasonKey.startsWith('edition.'))).toEqual(base.events.filter(e=>e.reasonKey.startsWith('edition.')).map((e,i)=>expect.objectContaining({value:e.value,operation:e.operation,targetCardId:e.targetCardId,retriggerDepth:e.retriggerDepth})));expect(t.jokers.map(j=>j.growth)).toEqual(base.jokers.map(j=>j.growth));expect(t.events.filter(e=>e.phase==='jokerScore').map(e=>[e.sourceInstanceId,e.operation,e.value])).toEqual(base.events.filter(e=>e.phase==='jokerScore').map(e=>[e.sourceInstanceId,e.operation,e.value]));});
 it('high card, held/attached/disabled target and actual zero points reject; ordinary legal scoring still works',()=>{const s=ready(),snapshot=structuredClone(s);for(const [ids,target] of [[pair,'clubs-2'],[[pair[0]],pair[0]],[[...pair,'clubs-2'],'clubs-2']] as const)expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:ids,erxiangTargetId:target}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'erxiang-invalid-core'}});const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);const i={rulesVersion:'r2' as const,runId:s.runId,rootId:'zero',characterId:'erxiang' as const,hand,selectedIds:pair,disabledIds:[],jokers:[],definitions:r2JokerDefinitionsFor(s),handLevels:{},playIndex:1,handsBeforePlay:4,previousHandType:null,wager:false,rng:s.rng.rule,erxiangHandoff:{targetId:pair[0],beforeUsed:false}};expect(()=>scoring.scoreR2Hand({...i,ordinaryPointsSuppressedIds:[pair[0]]})).toThrow('erxiang-zero-points');expect(()=>scoring.scoreR2Hand({...i,disabledIds:[pair[0]]})).toThrow('erxiang-invalid-core');expect(scoring.scoreR2Hand({...i,ordinaryPointsSuppressedIds:[pair[0]],erxiangHandoff:{targetId:null,beforeUsed:false}}).finalScore).toBe('86');expect(s).toEqual(snapshot);});
 it('B02 actual fourth core has zero points and cannot spend the once-stage handoff',()=>{let r=start();r.phase='stage-ready';r.stageIndex=2;r.seenBossIds=['B02'];r.boss={definitionId:'B02',disabledSuit:null};r.shop!.visitIndex=2;const ids=['spades-4','hearts-5','clubs-6','diamonds-7','hearts-8'],s=arrange(send(r,{type:'EnterStage'}),ids);expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:ids,erxiangTargetId:ids[3]}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'erxiang-zero-points'}});expect(s.stage!.erxiangHandoffUsed).toBe(false);const a=send(s,{type:'PlayHand',selectedIds:ids});expect(a.lastTrace!.events.filter(e=>e.operation==='ordinary-points-suppressed').map(e=>e.targetCardId)).toEqual(ids.slice(3));expect(a.stage!.erxiangHandoffUsed).toBe(false);});
 it('B08/Q01 block activation but allow ordinary play',()=>{let r=start();r.phase='stage-ready';r.chapter=3;r.stageIndex=8;r.seenBossIds=['B01','B02','B08'];r.boss={definitionId:'B08',disabledSuit:null};r.shop!.visitIndex=8;const boss=arrange(send(r,{type:'EnterStage'}),[...pair]);expect(applyCommand(boss,command(boss,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'erxiang-disabled'}});expect(send(boss,{type:'PlayHand',selectedIds:pair}).lastTrace!.events.filter(e=>e.sourceType==='character')).toEqual([]);const config={...mode,mode:'challenge' as const,challengeId:'Q01' as const},q=arrange(send(send(start(config),{type:'LeaveShop'}),{type:'EnterStage'}),[...pair]);expect(applyCommand(q,command(q,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'erxiang-disabled'}});expect(send(q,{type:'PlayHand',selectedIds:pair}).lastTrace!.finalScore).toBe('102');});
 it('score failure and malformed intent do not consume; existing identity refuses new action and retains178',()=>{const s=ready(),snapshot=structuredClone(s);expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:pair,erxiangTargetId:null as unknown as string}))).toMatchObject({ok:false,code:'invalid-erxiang-handoff'});const fault=vi.spyOn(scoring,'scoreR2Hand').mockImplementation(()=>{throw new scoring.ScoreFault('controlled',[]);});try{expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]}))).toMatchObject({ok:false,code:'score-diagnostic'});expect(s).toEqual(snapshot);}finally{fault.mockRestore();}const identity={contentVersion:R2_TOOL_SUPPLY_VERSION,contentHash:R2_TOOL_SUPPLY_HASH},old=arrange(send(send(start(mode,identity),{type:'LeaveShop'}),{type:'EnterStage'}),[...pair]);expect(send(old,{type:'PlayHand',selectedIds:pair}).lastTrace!.finalScore).toBe('178');expect(applyCommand(old,command(old,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]}))).toMatchObject({ok:false,code:'invalid-erxiang-handoff'});expect(launchIdentity('erxiang',{kind:'retry',run:old})).toEqual(identity);});
 it('quota failure exposes neither consumption nor result; retry exact candidate once, restore/replay do not consume again',async()=>{const s=ready();let slots:SaveSlots={revision:1,current:makeCheckpoint(s,[]),previous:null},fail=true;const candidates:string[]=[];const store:SaveStore={read:async()=>slots,commit:async(rev,cp,backup)=>{candidates.push(JSON.stringify(cp));if(fail)throw Error('quota-exceeded');slots={revision:rev+1,current:cp,previous:backup};return slots.revision;}};const saved=SavedRun.restore(store,slots);expect((await saved.dispatch({type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]})).ok).toBe(false);expect(saved.state).toEqual(s);fail=false;expect((await saved.retry()).ok).toBe(true);expect(candidates[1]).toEqual(candidates[0]);expect(saved.state.lastTrace!.finalScore).toBe('430');expect(SavedRun.restore(store,slots).state).toEqual(saved.state);expect((await saved.retry()).ok).toBe(false);});
 it('strict checkpoint rejects header, used flag, target, point, ordinary heat and source clock corruption',()=>{const s=ready(),a=send(s,{type:'PlayHand',selectedIds:pair,erxiangTargetId:pair[0]});for(const change of [(s:R2RunState)=>delete s.stage!.erxiangHandoffUsed,(s:R2RunState)=>s.stage!.erxiangHandoffUsed=false,(s:R2RunState)=>s.lastTrace!.erxiangHandoff!.points=7,(s:R2RunState)=>s.lastTrace!.erxiangHandoff!.targetId=pair[1],(s:R2RunState)=>s.lastTrace!.erxiangHandoff!.beforeUsed=true,(s:R2RunState)=>s.lastTrace!.events.find(e=>e.reasonKey==='erxiang.handoff')!.phase='characterScore',(s:R2RunState)=>s.lastTrace!.events.find(e=>e.targetCardId===pair[0]&&e.sourceDefinitionId==='rank-8')!.value.n='8'])expect(tamper(a,change).ok).toBe(false);});
 it('copy only offers actual valid cores; selected/cancel/used are explicit and no predicted total or state mutation',()=>{const s=ready(),before=structuredClone(s),hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!),facts=r2SelectionFacts({hand,selectedIds:pair,disabledIds:[],jokers:[],definitions:r2JokerDefinitionsFor(s)});expect(erxiangChoice(s,facts,pair[0]).sentence).toBe('这张的8点改加倍率，本场一次');expect(erxiangChoice(s,facts).selected).toBeUndefined();expect(erxiangChoice(s,{...facts,activeScoringIds:[pair[1]]},pair[0]).selected).toBeUndefined();expect(s).toEqual(before);});
});
