import {it,expect} from 'vitest';
import {growthAssistPlan,growthPlan,firstGrowthIds,secondGrowthIds} from '../harness/fixtures/growth-opportunity';
import {journeySend} from '../harness/fixtures/build-journey';
import {growthOpportunity} from '../src/game/GrowthOpportunity';
import {jokerSupportsFocus} from '../src/game/BuildJourney';
import {r2SelectionFacts} from '../src/domain/r2SelectionFacts';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {publicJokerMemoryContext} from '../src/game/JokerMemory';
import type {R2RunState} from '../src/domain/r2Run';
const context=(s:R2RunState,ids=firstGrowthIds,limited=false)=>publicJokerMemoryContext(s,{hand:s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!),facts:r2SelectionFacts({hand:s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!),selectedIds:ids,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),disabledIds:s.stage!.disabledIds}),scoringLimited:limited,deckSize:52,jokerSlots:5,jokerCount:s.jokers.length});
it('unowned d03 is discoverable in all three directions at zero growth',()=>{const s=growthPlan('d03');s.jokers=[];for(const f of ['group','straight','flush'] as const)expect(jokerSupportsFocus(s,'d03',f)).toBe(true);});
it('a05 first hand establishes same-type memory, actual second hand grows, next stage carries but resets memory',()=>{let s=growthPlan('a05');expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('prepare');s=journeySend(s,{type:'PlayHand',selectedIds:firstGrowthIds});const g=growthOpportunity(s,s.jokers[0],context(s,secondGrowthIds));expect(g!.status).toBe('ready');s=journeySend(s,{type:'PlayHand',selectedIds:secondGrowthIds});expect(s.lastTrace!.events.some(e=>e.sourceDefinitionId==='a05'&&e.operation==='add-growth'&&e.value.n==='6')).toBe(true);s=journeySend(journeySend(journeySend(s,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(s.jokers[0].growth.heat.n).toBe('6');expect(s.stage!.previousHandType).toBeNull();});
it('d03 public held count agrees with real after-hand growth and never mutates run/RNG',()=>{let s=growthPlan('d03'),before=JSON.stringify(s);const g=growthOpportunity(s,s.jokers[0],context(s));expect(g!.status).toBe('ready');expect(g!.body).toContain('实际保留4张');expect(JSON.stringify(s)).toBe(before);s=journeySend(s,{type:'PlayHand',selectedIds:firstGrowthIds});expect(s.jokers[0].growth.heat.n).toBe('4');expect(s.lastTrace!.events.some(e=>e.sourceDefinitionId==='d03'&&e.operation==='add-growth')).toBe(true);});
it('no next hand is promised on last-hand setup, and cap clipping reports only remaining growth',()=>{let s=growthPlan('a05');s.stage!.handsLeft=1;expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('unmet');s=growthPlan('d03');s.jokers[0].growth.heat={n:'59',d:'1'};expect(growthOpportunity(s,s.jokers[0],context(s))!.body).toContain('最多新增+1');s.jokers[0].growth.heat.n='60';expect(growthOpportunity(s,s.jokers[0],context(s))!.status).toBe('capped');});
it('scoring suppression is distinct from after-hand growth, and old a05 still uses its old single-card contract',()=>{const s=growthPlan('d03');expect(growthOpportunity(s,s.jokers[0],context(s,firstGrowthIds,true))!.status).toBe('ready');expect(growthOpportunity(s,s.jokers[0],context(s,firstGrowthIds,true))!.body).toContain('成长仍按独立阶段');const old=growthPlan('a05',true);expect(growthOpportunity(old,old.jokers[0],context(old,[old.handOrder[0]]))!.status).toBe('ready');expect(growthOpportunity(old,old.jokers[0],context(old,old.handOrder.slice(0,2)))!.status).toBe('unmet');});

it('hidden order and RNG cursors cannot change a public opportunity',()=>{const s=growthPlan('d03'),h=structuredClone(s);h.drawPile.reverse();for(const r of Object.values(h.rng))r.state=(r.state+19)>>>0;expect(growthOpportunity(h,h.jokers[0],context(h))).toEqual(growthOpportunity(s,s.jokers[0],context(s)));});

it('assist-consumed cards are not held cards for d03 growth',async()=>{const {assistCandidates}=await import('../src/game/AssistSelection');const s=growthAssistPlan(),hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);let found=false;for(let mask=1;mask<1<<hand.length;mask++){const selectedIds=hand.filter((_,i)=>mask&(1<<i)).map(c=>c.id);if(selectedIds.length!==5)continue;const input={hand,selectedIds,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),disabledIds:[]};const assisted=assistCandidates(input,true).find(a=>a.assistIds.length===2);if(!assisted)continue;const c={...context(s,selectedIds),facts:assisted};expect(assisted.heldIds.length).toBeLessThan(3);expect(growthOpportunity(s,s.jokers[0],c)!.status).toBe('unmet');expect(growthOpportunity(s,s.jokers[0],context(s,selectedIds))!.status).toBe('ready');found=true;break;}expect(found).toBe(true);});
