import {it,expect} from 'vitest';
import {keyHighlightPlan} from '../harness/fixtures/key-highlight';
import {experiencePlan} from '../harness/fixtures/joker-experience';
import {giftSend} from '../harness/fixtures/stage-gift';
import {keyHighlight,keyHighlightBeat,savedGrowthStamp} from '../src/game/JokerKeyHighlight';
import {scoreBeat} from '../src/game/scorePresentation';
it('picks one real multiplication in event order without mutating committed state',()=>{const p=keyHighlightPlan(),s=giftSend(p.state,{type:'PlayHand',selectedIds:p.first}),before=JSON.stringify(s),k=keyHighlight(s,s.lastTrace!)!;expect(k.kind).toBe('multiply');expect(k.fact.definitionId).toBe('f09');expect(k.landing).toContain('倍率');expect(JSON.stringify(s)).toBe(before);const e=s.lastTrace!.events.find(e=>e.eventId===k.eventId)!;expect(e.operation).toBe('multiply-multiplier');const b=keyHighlightBeat(scoreBeat(e));expect(b.windup).toBe(100);expect(b.windup+b.flight+b.impact+b.rest).toBeLessThanOrEqual(700);expect(keyHighlightBeat(b,true).windup).toBe(0);});
it('ordinary growth reads do not get a full scene; saved new growth goes to next hand',()=>{const p=experiencePlan(),s=giftSend(p.state,{type:'PlayHand',selectedIds:p.first});expect(keyHighlight(s,s.lastTrace!,'0','999999')).toBeUndefined();const e=s.lastTrace!.events.find(e=>e.operation==='add-growth'&&e.sourceDefinitionId==='b10')!;expect(savedGrowthStamp(s,s.lastTrace!,e)).toContain('该手后已存 20');expect(savedGrowthStamp(s,s.lastTrace!,e)).toContain('下手按条件读取');});
it('zero/capped/sealed events cannot select or stamp, same-source repeats keep one identity',()=>{const p=keyHighlightPlan(),s=giftSend(p.state,{type:'PlayHand',selectedIds:p.first}),t=s.lastTrace!,k=keyHighlight(s,t)!;const no={...t,events:t.events.map(e=>({...e,after:e.before,value:{n:'0',d:'1'}}))};expect(keyHighlight(s,no)).toBeUndefined();expect(keyHighlight(s,{...t,events:[...t.events,...t.events]})).toEqual(k);const capped=experiencePlan(true),cs=giftSend(capped.state,{type:'PlayHand',selectedIds:capped.first});for(const e of cs.lastTrace!.events.filter(e=>e.operation==='add-growth'))expect(savedGrowthStamp(cs,cs.lastTrace!,e)).toBeUndefined();});
