import {describe,it,expect} from 'vitest';
import {createRun,applyCommand,type R2RunState,type Action,type Command} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {SavedRun,type SaveStore,type SaveSlots} from '../src/application/SavedRun';
import {r2CreateJoker,r2ScoreContext} from '../src/domain/r2Run';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {scoreR2Hand} from '../src/domain/scoreR2';
import {stableHash} from '../src/domain/hash';
const start=()=>createRun({seed:'group-natural-17',runId:'lao-test',characterId:'laohuan',rulesVersion:'r2',r2Identity:newRunIdentity('laohuan','group'),openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
const cmd=(s:R2RunState,action:Action):Command=>({runId:s.runId,commandId:'test/'+s.commandSeq,expectedSeq:s.commandSeq,action});
function send(s:R2RunState,action:Action,journal:Command[]=[]){const c=cmd(s,action),r=applyCommand(s,c);if(!r.ok)throw Error(r.code+JSON.stringify(r.diagnostic));journal.push(c);const read=readCheckpoint(makeCheckpoint(r.state,journal));expect(read,JSON.stringify(read)).toMatchObject({ok:true});return r.state;}
const entered=()=>send(send(start(),{type:'LeaveShop'}),{type:'EnterStage'});
const trick=(s:R2RunState,j:Command[]=[])=>send(s,{type:'DiscardHand',selectedIds:['diamonds-5'],laohuanTrick:true},j);
function short(s:R2RunState,n:number){s=structuredClone(s);s.playedPile.push(...s.drawPile.splice(0,s.drawPile.length-n));return s;}
function corrupt(s:R2RunState,f:(s:R2RunState)=>void){const cp=structuredClone(makeCheckpoint(s,[]));f(cp.state);const{checksum,...p}=cp;return readCheckpoint({...p,checksum:stableHash(p)});}
describe('laohuan real discard and fixed refill',()=>{
 it('commits one discard and unique candidate zone, choice moves rejects to used without second hooks',()=>{const before=entered(),j:Command[]=[],p=trick(before,j);expect(before.stage!.laohuanTrickUsed).toBe(false);expect(p.phase).toBe('pending-refill');expect(p.stage!.discardsUsed).toBe(1);expect(p.stage!.discardsLeft).toBe(2);expect(p.stage!.playIndex).toBe(0);expect(p.discardPile).toEqual(['diamonds-5']);expect(p.pendingRefill!.candidateIds).toHaveLength(3);expect(p.pendingRefill!.required).toBe(1);const chosen=p.pendingRefill!.candidateIds[1],rejected=p.pendingRefill!.candidateIds.filter(id=>id!==chosen),c=cmd(p,{type:'ChooseRefill',selectedIds:[chosen]}),r=applyCommand(p,c);expect(r.ok).toBe(true);if(!r.ok)return;expect(r.events).toEqual([]);j.push(c);expect(readCheckpoint(makeCheckpoint(r.state,j))).toMatchObject({ok:true});expect(r.state.handOrder).toContain(chosen);expect(r.state.playedPile).toEqual(rejected);expect(r.state.discardPile).toEqual(p.discardPile);expect(r.state.stage!.discardsUsed).toBe(1);expect(r.state.stage!.laohuanTrickUsed).toBe(true);expect(r.state.pendingRefill).toBe(null);const repeated=applyCommand(r.state,c);expect(repeated.ok&&repeated.duplicate).toBe(true);expect(applyCommand(r.state,cmd(r.state,{type:'DiscardHand',selectedIds:[chosen],laohuanTrick:true}))).toMatchObject({ok:false,code:'laohuan-already-used'});});
 it('pending blocks ordinary mutations, malformed selection preserves original and abandon never refunds',()=>{const p=trick(entered()),snapshot=structuredClone(p);for(const action of [{type:'PlayHand',selectedIds:p.handOrder.slice(0,1)},{type:'DiscardHand',selectedIds:p.handOrder.slice(0,1)},{type:'UseConsumable',instanceId:'none',targetIds:[]},{type:'ReorderHand',ids:p.handOrder}] as Action[])expect(applyCommand(p,cmd(p,action))).toMatchObject({ok:false,code:'refill-pending'});for(const selectedIds of [[],['none'],p.pendingRefill!.candidateIds])expect(applyCommand(p,cmd(p,{type:'ChooseRefill',selectedIds}))).toMatchObject({ok:false,code:'invalid-refill-selection'});expect(p).toEqual(snapshot);const ended=send(p,{type:'AbandonRun'});expect(ended.gold).toBe(p.gold);expect(ended.stage!.discardsLeft).toBe(p.stage!.discardsLeft);expect(ended.playedPile).toEqual(p.pendingRefill!.candidateIds);expect(ended.pendingRefill).toBe(null);});
 it('N+1 remains choice, N/short/zero auto finish, zero selection cannot burn',()=>{const p=trick(short(entered(),2));expect(p.pendingRefill!.candidateIds).toHaveLength(2);for(const n of [1,0]){const a=trick(short(entered(),n));expect(a.phase).toBe('await-input');expect(a.pendingRefill).toBe(null);expect(a.stage!.laohuanTrickUsed).toBe(true);expect(a.handOrder).toHaveLength(7+n);}const b=entered();expect(applyCommand(b,cmd(b,{type:'DiscardHand',selectedIds:[],laohuanTrick:true}))).toMatchObject({ok:false,code:'empty-selection'});expect(b.stage!.laohuanTrickUsed).toBe(false);let s=short(entered(),2);const a=send(s,{type:'DiscardHand',selectedIds:s.handOrder.slice(0,5),laohuanTrick:true});expect(a.pendingRefill).toBe(null);expect(a.handOrder).toHaveLength(5);let empty=short(entered(),0);empty.playedPile.push(...empty.handOrder.splice(5));const lost=send(empty,{type:'DiscardHand',selectedIds:empty.handOrder,laohuanTrick:true});expect(lost.phase).toBe('run-lost');expect(lost.pendingRefill).toBe(null);const five=send(entered(),{type:'DiscardHand',selectedIds:entered().handOrder.slice(0,5),laohuanTrick:true});expect(five.pendingRefill!.required).toBe(5);const finished=send(five,{type:'ChooseRefill',selectedIds:[...five.pendingRefill!.candidateIds.slice(0,5)].reverse()});expect(finished.handOrder.slice(-5)).toEqual(five.pendingRefill!.candidateIds.slice(0,5));});
 it('two save failures retry exact candidate without revealing or redrawing and restore both phases',async()=>{const before=entered();let slots:SaveSlots={revision:1,current:makeCheckpoint(before,[]),previous:null},fail=true;const written:string[]=[];const store:SaveStore={read:async()=>slots,commit:async(rev,cp,backup)=>{written.push(JSON.stringify(cp));if(fail)throw Error('quota-exceeded');slots={revision:rev+1,current:cp,previous:backup};return slots.revision;}};const run=SavedRun.restore(store,slots);expect((await run.dispatch({type:'DiscardHand',selectedIds:['diamonds-5'],laohuanTrick:true})).ok).toBe(false);expect(run.state).toEqual(before);fail=false;expect((await run.retry()).ok).toBe(true);expect(written[0]).toBe(written[1]);const p=run.state;expect(SavedRun.restore(store,slots).state).toEqual(p);fail=true;const chosen=p.pendingRefill!.candidateIds[0];expect((await run.dispatch({type:'ChooseRefill',selectedIds:[chosen]})).ok).toBe(false);expect(run.state).toEqual(p);fail=false;expect((await run.retry()).ok).toBe(true);expect(written[2]).toBe(written[3]);expect(SavedRun.restore(store,slots).state).toEqual(run.state);expect(run.state.stage!.discardsUsed).toBe(1);});
 it('Q01 refuses, B08 permits non-scoring selection and B14 increases once',()=>{let q=createRun({seed:'challenge/q01/0',runId:'q-lao',characterId:'laohuan',rulesVersion:'r2',r2Identity:newRunIdentity('laohuan','group'),openingRoute:'group',modeConfig:{mode:'challenge',difficulty:0,challengeId:'Q01',programsEnabled:false}});q=send(send(q,{type:'LeaveShop'}),{type:'EnterStage'});expect(applyCommand(q,cmd(q,{type:'DiscardHand',selectedIds:q.handOrder.slice(0,1),laohuanTrick:true}))).toMatchObject({ok:false,code:'laohuan-disabled'});for(const id of ['B08','B14'] as const){let r=start();r.phase='stage-ready';r.chapter=id==='B14'?7:3;r.stageIndex=r.chapter*3-1;r.shop!.visitIndex=r.stageIndex;r.seenBossIds=id==='B14'?['B01','B02','B03','B04','B05','B06',id]:['B01','B02',id];r.boss={definitionId:id,disabledSuit:null};r=send(r,{type:'EnterStage'});const p=send(r,{type:'DiscardHand',selectedIds:r.handOrder.slice(0,1),laohuanTrick:true});const a=send(p,{type:'ChooseRefill',selectedIds:p.pendingRefill!.candidateIds.slice(0,1)});expect(a.stage!.targetHeat).toBe(p.stage!.targetHeat);expect(a.stage!.discardsUsed).toBe(1);if(id==='B14')expect(BigInt(a.stage!.targetHeat)-BigInt(r.stage!.targetHeat)).toBe((BigInt(r.stage!.initialTargetHeat)+19n)/20n);}});
 it('only actual discarded card triggers a07 refund, rejects never add count or clear first-discard record',()=>{let s=entered();s.jokers=[r2CreateJoker('a07','a07',4,'none',s),r2CreateJoker('f10','f10',8,'none',s)];s.stage!.initialJokerIds=s.jokers.map(j=>j.instanceId);const p=trick(s),a=send(p,{type:'ChooseRefill',selectedIds:p.pendingRefill!.candidateIds.slice(0,1)});expect(a.jokers).toEqual(p.jokers);expect(a.stage!.discardsLeft).toBe(p.stage!.discardsLeft);expect(a.stage!.openingDiscard).toEqual(p.stage!.openingDiscard);expect(a.stage!.discardsUsed).toBe(1);});
 it('new ability removes old120 in real score/AI context, next entry resets used',()=>{const s=entered(),hand=['hearts-10','clubs-11','diamonds-12','spades-13','hearts-14'].map(id=>s.deckInstances.find(c=>c.id===id)!);const i={rulesVersion:'r2' as const,runId:s.runId,rootId:s.runId+'/hand/check',hand,selectedIds:hand.map(c=>c.id),disabledIds:[],jokers:[],definitions:r2JokerDefinitionsFor(s),handLevels:{},playIndex:1,handsBeforePlay:4,previousHandType:null,wager:false,rng:s.rng.rule,...r2ScoreContext(s,hand,hand.map(c=>c.id))};const t=scoreR2Hand(i),old=scoreR2Hand({...i,laohuanTrick:undefined});expect(t.events.some(e=>e.sourceType==='character')).toBe(false);expect(old.events.find(e=>e.sourceType==='character')!.value.n).toBe('120');let a=trick(s);a=send(a,{type:'ChooseRefill',selectedIds:a.pendingRefill!.candidateIds.slice(0,1)});a=structuredClone(a);const ids=['hearts-14','spades-14','clubs-14','hearts-13','spades-13'];a.handOrder=ids;a.drawPile=a.deckInstances.map(c=>c.id).filter(id=>!ids.includes(id)&&!a.playedPile.includes(id)&&!a.discardPile.includes(id));a=send(a,{type:'PlayHand',selectedIds:ids});expect(a.phase).toBe('stage-cleared');a=send(send(send(a,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(a.stage!.laohuanTrickUsed).toBe(false);});
 it.each([false,true])('cold f10 remains armed through fixed refill (ordinary first=%s), then next real play consumes once',ordinaryFirst=>{let s=entered();const cold=['spades-2','hearts-4','clubs-6','diamonds-8','spades-10','hearts-12','clubs-14','diamonds-3'];s=structuredClone(s);s.handOrder=cold;s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!cold.includes(id));s.jokers=[r2CreateJoker('f10','cold/f10',8,'none',s)];s.stage!.initialJokerIds=['cold/f10'];const journal:Command[]=[];if(ordinaryFirst){s=send(s,{type:'DiscardHand',selectedIds:[cold[0]]},journal);expect(s.jokers[0].counters).toEqual({rescueArmed:true});}const p=send(s,{type:'DiscardHand',selectedIds:[s.handOrder[0]],laohuanTrick:true},journal);expect(p.phase).toBe('pending-refill');expect(p.jokers[0].counters).toEqual({rescueArmed:true});const cp=makeCheckpoint(p,journal),read=readCheckpoint(cp);expect(read).toMatchObject({ok:true});let a=send(p,{type:'ChooseRefill',selectedIds:p.pendingRefill!.candidateIds.slice(0,1)},journal);expect(a.jokers[0].counters).toEqual({rescueArmed:true});a=send(a,{type:'PlayHand',selectedIds:[a.handOrder[0]]},journal);expect(a.jokers[0].counters).toEqual({rescueArmed:false});expect(a.lastTrace!.events.filter(e=>e.operation==='consume-rescue')).toHaveLength(1);});
 it('pending preserves active pointer, challenge/boss snapshot and live joker identity strictness',()=>{const p=trick(entered());for(const f of [(s:R2RunState)=>s.stageIndex=1,(s:R2RunState)=>s.stage!.challengeDisabledJokerId='f10',(s:R2RunState)=>{s.jokers=[r2CreateJoker('f07','unowned',8,'none',s)];}])expect(corrupt(p,f).ok).toBe(false);let s=start();s.phase='stage-ready';s.stageIndex=2;s.shop!.visitIndex=2;s.seenBossIds=['B01'];s.boss={definitionId:'B01',disabledSuit:null};s=send(s,{type:'EnterStage'});const b=send(s,{type:'DiscardHand',selectedIds:s.handOrder.slice(0,1),laohuanTrick:true});expect(corrupt(b,s=>s.boss={definitionId:'B02',disabledSuit:null}).ok).toBe(false);});
 it('strict current parsing refuses phase/gap/duplicate/cost-marker corruption',()=>{const p=trick(entered());for(const f of [(s:R2RunState)=>s.pendingRefill!.required=2,(s:R2RunState)=>s.pendingRefill!.candidateIds.push(s.handOrder[0]),(s:R2RunState)=>s.stage!.laohuanTrickUsed=false,(s:R2RunState)=>s.pendingRefill!.discardCommandId='none',(s:R2RunState)=>s.phase='await-input',(s:R2RunState)=>delete s.pendingRefill])expect(corrupt(p,f).ok).toBe(false);});
});
