import {it,expect} from 'vitest';import {readFileSync} from 'node:fs';
import {applyCommand,type R2RunState} from '../src/domain/run';import {stageGiftPlan,giftSend} from '../harness/fixtures/stage-gift';
import {r2ItemPrice} from '../src/domain/r2Shop';import {purchasePaymentFacts,purchaseDiscountStatus} from '../src/game/PurchasePaymentFacts';
const initial=()=>{const s=JSON.parse(readFileSync('docs/production/evidence/w1-inputs-2026-10-07/controlled-shop.json','utf8')).state as R2RunState;s.gold=100;s.jokers=[];s.consumables=[];s.longTermItems=['U10'];s.shop!.purchases=0;s.purchaseCoupons=0;return s;};
function buy(s:R2RunState,id:string){const o=s.shop!.offers.concat(s.shop!.toolOffers,s.shop!.itemOffers).find(o=>o.offerId===id)!;const r=applyCommand(s,{runId:s.runId,commandId:'payment/'+s.commandSeq,expectedSeq:s.commandSeq,action:{type:'BuyOffer',offerId:id}});if(!r.ok)throw Error(r.code);return {state:r.state,facts:purchasePaymentFacts(s,r.state,o)!};}
it('all three shelves use the same saved first-purchase calculation',()=>{for(const shelf of ['offers','toolOffers','itemOffers'] as const){const s=initial(),before=JSON.stringify(s),r=buy(s,s.shop![shelf][0].offerId);expect(r.facts.saved).toBe(1);expect(r.facts.sources[0].name).toBe('采购证');expect(r.facts.body).toContain('实付');expect(r.facts.body).toContain('本店首购资格已用');expect(JSON.stringify(s)).toBe(before);}});
it('second purchase gets no first discount and new shop restores eligibility',()=>{const s=initial(),first=buy(s,s.shop!.toolOffers[0].offerId),second=buy(first.state,first.state.shop!.offers[0].offerId);expect(second.facts.saved).toBe(0);expect(second.facts.sources).toHaveLength(0);expect(second.facts.body).toContain('没有实际折扣收益');const route=stageGiftPlan();route.state.jokers=[];route.state.longTermItems=['U10'];const clear=giftSend(giftSend(route.state,{type:'PlayHand',selectedIds:route.first}),{type:'PlayHand',selectedIds:route.second});const nextShop=giftSend(clear,{type:'OpenShop'});expect(purchaseDiscountStatus(nextShop)).toContain('资格可用');const nextBuy=buy(nextShop,nextShop.shop!.offers[0].offerId);expect(nextBuy.facts.saved).toBe(1);});
it('buying the discount item itself does not claim its new modifier',()=>{const s=initial();s.longTermItems=[];s.shop!.itemOffers=[{offerId:'self/U10',definitionId:'U10',price:r2ItemPrice('U10'),consumed:false}];const r=buy(s,'self/U10');expect(r.facts.saved).toBe(0);expect(r.facts.sources).toHaveLength(0);expect(r.facts.body).toContain('本店首购资格已用');});
it('stacked nominal amounts never each claim the floor-truncated total',()=>{const s=initial();s.jokers=[{instanceId:'held/e02',definitionId:'e02',paidPrice:4,growth:{}}];s.purchaseCoupons=2;const r=buy(s,s.shop!.offers[0].offerId);expect(r.facts.paid).toBe(1);expect(r.facts.saved).toBe(r.facts.original-1);expect(r.facts.sources.map(x=>x.nominal)).toEqual([1,1,2]);expect(r.facts.sources[0]).toMatchObject({kind:'joker',definitionId:'e02',instanceId:'held/e02'});expect(r.facts.sources[1]).toMatchObject({kind:'item',definitionId:'U10'});expect(r.facts.sources[2].kind).toBe('coupon');expect(r.facts.summary).toContain('第1笔支付');expect(r.facts.body).toContain('未记录逐来源实际分摊');expect(r.facts.body).toContain('剩余1张');});
it('failed/uncommitted and duplicate states create no payment fact',()=>{const s=initial(),o=s.shop!.offers[0];expect(purchasePaymentFacts(s,s,o)).toBeUndefined();expect(purchasePaymentFacts(s,{...s,commandSeq:s.commandSeq+1},o)).toBeUndefined();const r=buy(s,o.offerId);expect(purchasePaymentFacts(r.state,r.state,r.state.shop!.offers[0])).toBeUndefined();});
