import{expect,it}from'vitest';import type{PlayingCard,Rank,Suit}from'../src/cards/types';import{R2_JOKERS}from'../src/content/r2Schema';import{r2DisabledCards}from'../src/domain/r2Chapter';import{r2CreateJoker}from'../src/domain/r2Run';import{r2SelectionFacts}from'../src/domain/r2SelectionFacts';import{selectionCardCopy}from'../src/game/SelectionCopy';import{jokerMemory,jokerMemoryAbility,r2ConditionDescription,type JokerMemoryContext}from'../src/game/JokerMemory';import{r2ScoreConditionMatches,r2TransactionConditionMatches,type R2ScoreConditionContext}from'../src/domain/r2Conditions';
const card=(id:string,rank:Rank,suit:Suit='spades'):PlayingCard=>({id,rank,suit});const definition=(id:string)=>R2_JOKERS.find(d=>d.id===id)!;
const hand=[card('a',7),card('b',7,'hearts'),card('c',7,'clubs'),card('d',2),card('e',4,'hearts'),card('held',11)];
const facts=(disabledIds:string[]=[],ordinaryPointsSuppressedIds:string[]=[])=>r2SelectionFacts({hand,selectedIds:hand.slice(0,5).map(c=>c.id),jokers:[],definitions:R2_JOKERS,disabledIds,ordinaryPointsSuppressedIds});
const context=(extra:Partial<JokerMemoryContext>={}):JokerMemoryContext=>({inStage:true,hand,facts:facts(),disabledIds:[],scoringLimited:false,gold:3,handsLeft:4,playIndex:0,discardsUsed:0,previousHandType:null,stageHeat:'0',target:'1000',transaction:{gold:3,handsAfter:4,playIndex:0,discardsUsed:0,handType:null,discarded:[],hasStage:true,maxPlayedCount:0,ordinaryStraightSeen:false,ordinaryFlushSeen:false,jokerSold:false,traceType:null,heat:'0',target:'1000'},deckSize:40,entryHandLimit:10,jokerSlots:5,jokerCount:2,...extra});
it('singlecard role uses actual B03 disabled core/accompanying sets and B02 ordinary-zero independently',()=>{const disabled=r2DisabledCards({definitionId:'B03',disabledSuit:'hearts'},2,hand),f=facts(disabled);expect(selectionCardCopy(f,'held')).toBe('未选择');expect(selectionCardCopy(f,'a')).toBe('计分牌');expect(selectionCardCopy(f,'b')).toBe('成型核心但计分停用');expect(selectionCardCopy(f,'c')).toBe('计分牌');expect(selectionCardCopy(f,'d')).toBe('附带牌');expect(selectionCardCopy(f,'e')).toContain('附带牌；本场效果停用');expect(selectionCardCopy(facts([],['d','e']),'e')).toBe('附带牌\n普通点数0，其他效果保留');});
it('all72 hooks/modifiers have schema-derived timing/object/condition/mechanism and safe entry without forecasts',()=>{
 const kinds=new Set();for(const d of R2_JOKERS){const j=r2CreateJoker(d.id,d.id,0),before=structuredClone(j),memory=jokerMemory(d,j,context()),copy=jokerMemoryAbility(d,j,context());expect(memory.short.length).toBeGreaterThan(0);expect(copy.condition.length).toBeGreaterThan(0);expect(copy.value.length).toBeGreaterThan(0);expect(copy.state).toBeTruthy();expect(j).toEqual(before);for(const h of d.hooks){kinds.add(h.condition.kind);expect(r2ConditionDescription(h.condition)?.length).toBeGreaterThan(0);}for(const h of memory.hooks){expect(h.timing).toBeTruthy();expect(h.condition).toBeTruthy();expect(h.mechanism).toBeTruthy();}for(const field of['events','accumulator','scoreRange','finalScore','rng','possibleScores'])expect(memory).not.toHaveProperty(field);}expect(kinds.size).toBe(29);
});
it('no0-card eligibility; whole held/static rules survive scoring-only restriction; conditions precede individual values',()=>{expect(jokerMemory(definition('a09'),r2CreateJoker('a09','a',0),context({facts:undefined})).hooks[0].status).toBe('待选牌');const c09=jokerMemory(definition('c09'),r2CreateJoker('c09','c',0),context({scoringLimited:true}));expect(c09.short).toBe('4张同花');expect(c09.status).toBe('计分受限');expect(c09.staticRules).toEqual(['4张普通同花；同花顺仍5张']);expect(jokerMemoryAbility(definition('c09'),undefined,context({scoringLimited:true,inStage:false})).state).toContain('静态／资源／经济与结算后效果按条件保留');});
it('strict f10 quarter / changing target, f04 startinggold<=3, f09 discard history unchanged by refund',()=>{const status=(id:string,ctx:JokerMemoryContext)=>jokerMemory(definition(id),r2CreateJoker(id,id,0),ctx).hooks[0].status;expect(status('f10',context({stageHeat:'249'}))).toBe('条件满足');expect(status('f10',context({stageHeat:'250'}))).toBe('当前未满足');expect(status('f10',context({stageHeat:'250',target:'1001'}))).toBe('条件满足');expect(status('f04',context({gold:3}))).toBe('条件满足');expect(status('f04',context({gold:4}))).toBe('当前未满足');expect(status('f09',context({discardsUsed:1}))).toBe('当前未满足');expect(status('huimaqiang',context({playIndex:2}))).toBe('条件满足');});
it('all result-dependent and probabilistic mechanisms stay event-time; lifetime and coefficients reflect saved instance',()=>{
 for(const id of['f05','f11','b12','f07','d09']){const memory=jokerMemory(definition(id),r2CreateJoker(id,id,0),context());expect(memory.hooks.filter(h=>h.status==='事件时检查').length).toBeGreaterThan(0);}
 const f06=r2CreateJoker('f06','life',0);f06.counters={...(f06.counters??{}),handsScored:2};expect(jokerMemory(definition('f06'),f06,context()).remaining).toBe(2);expect(jokerMemoryAbility(definition('f08'),undefined,context()).value).toContain('正式执行才检查随机');
 for(const size of[40,41]){const a04=jokerMemory(definition('a04'),r2CreateJoker('a04','a',0),context({deckSize:size}));expect(a04.status).toBe('入场已锁定');expect(a04.staticRules[0]).toContain('入场已锁定上限10');expect(a04.staticRules[0]).toContain('当前牌组'+size+'张');}
});
it('score and transaction clocks are intentionally separate; actual histories do not count unsent currenthand',()=>{
 const score:R2ScoreConditionContext={played:hand.slice(0,5),active:hand.slice(0,3),held:[hand[5]],validHeld:[hand[5]],scoringIds:['a','b','c'],handType:'three-kind',previousHandType:null,gold:3,handsAfter:3,playIndex:1,discardsUsed:0,extraExecutions:0,resolvedFinal:null,stageHeatBefore:'0',stageTargetHeat:'1000'};
 expect(r2ScoreConditionMatches({kind:'resource',resource:'hands-after',equals:3},score)).toBe(true);expect(r2TransactionConditionMatches({kind:'resource',resource:'hands-after',equals:3},context().transaction)).toBe(false);
 expect(r2ScoreConditionMatches({kind:'played-count',equals:5},score)).toBe(true);expect(r2ScoreConditionMatches({kind:'paired-rank',minimum:3},score,hand[0])).toBe(true);expect(r2ScoreConditionMatches({kind:'all-played-active',minimum:1},score)).toBe(false);
 expect(r2TransactionConditionMatches({kind:'stage-hand-types-all',values:['straight','flush']},context().transaction)).toBe(false);expect(r2TransactionConditionMatches({kind:'no-joker-sale-this-stage'},{...context().transaction,jokerSold:true})).toBe(false);
 const lost={...score,active:[hand[0],hand[2]],scoringIds:['a','b','c']};expect(r2ScoreConditionMatches({kind:'scoring-position',position:'third-original'},lost,hand[2])).toBe(true);const thirdGone={...score,active:[hand[0],hand[1]]};expect(thirdGone.active.some(c=>r2ScoreConditionMatches({kind:'scoring-position',position:'third-original'},thirdGone,c))).toBe(false);expect(r2ScoreConditionMatches({kind:'scoring-position',position:'last'},lost,hand[2])).toBe(true);
 const held=[card('h1',11),card('h2',2),card('h3',11)],heldCtx={...score,held,validHeld:held.slice(1)};expect(r2ScoreConditionMatches({kind:'held-count',minimum:3},heldCtx)).toBe(true);expect(r2ScoreConditionMatches({kind:'held-rank-first',values:[11],limit:1},heldCtx,held[2])).toBe(true);expect(r2ScoreConditionMatches({kind:'held-rank-first',values:[11],limit:1},heldCtx,held[0])).toBe(false);
});
