import{expect,it}from'vitest';import type{PlayingCard,Rank,Suit}from'../src/cards/types';import{R2_JOKERS}from'../src/content/r2Schema';import{r2DisabledCards}from'../src/domain/r2Chapter';import{r2CreateJoker}from'../src/domain/r2Run';import{scoreR2Hand}from'../src/domain/scoreR2';import{r2SelectionFacts}from'../src/domain/r2SelectionFacts';import{selectionCardCopy}from'../src/game/SelectionCopy';import{jokerMemory,jokerMemoryAbility,r2ConditionDescription,type JokerMemoryContext}from'../src/game/JokerMemory';import{r2ScoreConditionMatches,r2TransactionConditionMatches,type R2ScoreConditionContext}from'../src/domain/r2Conditions';
const card=(id:string,rank:Rank,suit:Suit='spades'):PlayingCard=>({id,rank,suit});const definition=(id:string)=>R2_JOKERS.find(d=>d.id===id)!;
const hand=[card('a',7),card('b',7,'hearts'),card('c',7,'clubs'),card('d',2),card('e',4,'hearts'),card('held',11)];
const facts=(disabledIds:string[]=[],ordinaryPointsSuppressedIds:string[]=[])=>r2SelectionFacts({hand,selectedIds:hand.slice(0,5).map(c=>c.id),jokers:[],definitions:R2_JOKERS,disabledIds,ordinaryPointsSuppressedIds});
const context=(extra:Partial<JokerMemoryContext>={}):JokerMemoryContext=>({inStage:true,hand,facts:facts(),disabledIds:[],scoringLimited:false,gold:3,handsLeft:4,playIndex:0,discardsUsed:0,quadRefundUsed:false,previousHandType:null,stageHeat:'0',target:'1000',transaction:{gold:3,handsAfter:4,playIndex:0,discardsUsed:0,handType:null,discarded:[],hasStage:true,maxPlayedCount:0,ordinaryStraightSeen:false,ordinaryFlushSeen:false,jokerSold:false,traceType:null,heat:'0',target:'1000'},deckSize:40,entryHandLimit:10,jokerSlots:5,jokerCount:2,...extra});
it('singlecard role uses actual B03 disabled core/accompanying sets and B02 ordinary-zero independently',()=>{const disabled=r2DisabledCards({definitionId:'B03',disabledSuit:'hearts'},2,hand),f=facts(disabled);expect(selectionCardCopy(f,'held')).toBe('未选择');expect(selectionCardCopy(f,'a')).toBe('计分牌');expect(selectionCardCopy(f,'b')).toBe('成型核心但计分停用');expect(selectionCardCopy(f,'c')).toBe('计分牌');expect(selectionCardCopy(f,'d')).toBe('附带牌');expect(selectionCardCopy(f,'e')).toContain('附带牌；本场计分效果停用');expect(selectionCardCopy(facts([],['d','e']),'e')).toBe('附带牌\n普通点数0，其他效果保留');});
it('all72 hooks/modifiers have schema-derived timing/object/condition/mechanism and safe entry without forecasts',()=>{
 const kinds=new Set();for(const d of R2_JOKERS){const j=r2CreateJoker(d.id,d.id,0),before=structuredClone(j),memory=jokerMemory(d,j,context()),copy=jokerMemoryAbility(d,j,context());expect(memory.short.length).toBeGreaterThan(0);expect(copy.condition.length).toBeGreaterThan(0);expect(copy.playerCopy).toBe(true);expect(copy.state).toBeTruthy();expect(j).toEqual(before);for(const h of d.hooks){kinds.add(h.condition.kind);expect(r2ConditionDescription(h.condition)?.length).toBeGreaterThan(0);}for(const h of memory.hooks){expect(h.timing).toBeTruthy();expect(h.condition).toBeTruthy();expect(h.mechanism).toBeTruthy();}for(const field of['events','accumulator','scoreRange','finalScore','rng','possibleScores'])expect(memory).not.toHaveProperty(field);}expect(kinds.size).toBe(29);
});
it('no0-card eligibility; whole held/static rules survive scoring-only restriction; conditions precede individual values',()=>{expect(jokerMemory(definition('a09'),r2CreateJoker('a09','a',0),context({facts:undefined})).hooks[0].status).toBe('待选牌');const c09=jokerMemory(definition('c09'),r2CreateJoker('c09','c',0),context({scoringLimited:true}));expect(c09.short).toBe('4张同花');expect(c09.status).toBe('计分受限');expect(c09.staticRules).toEqual(['4张普通同花；同花顺仍5张']);expect(jokerMemoryAbility(definition('c09'),undefined,context({scoringLimited:true,inStage:false})).state).toBe('尚未购买，买入后才会生效');expect(jokerMemoryAbility(definition('c09'),r2CreateJoker('c09','c',0),context({scoringLimited:true})).value).toContain('只暂停计分与版次效果，其他效果仍按各自规则');});
it('strict f10 quarter / changing target, f04 startinggold<=3, f09 discard history unchanged by refund',()=>{const status=(id:string,ctx:JokerMemoryContext)=>jokerMemory(definition(id),r2CreateJoker(id,id,0),ctx).hooks[0].status;expect(status('f10',context({stageHeat:'249'}))).toBe('条件满足');expect(status('f10',context({stageHeat:'250'}))).toBe('当前未满足');expect(status('f10',context({stageHeat:'250',target:'1001'}))).toBe('条件满足');expect(status('f04',context({gold:3}))).toBe('条件满足');expect(status('f04',context({gold:4}))).toBe('当前未满足');expect(status('f09',context({discardsUsed:1}))).toBe('当前未满足');expect(status('huimaqiang',context({playIndex:2}))).toBe('条件满足');});
it('all result-dependent and probabilistic mechanisms stay event-time; lifetime and coefficients reflect saved instance',()=>{
 for(const id of['f05','f11','b12','f07','d09']){const memory=jokerMemory(definition(id),r2CreateJoker(id,id,0),context());expect(memory.hooks.filter(h=>h.status==='事件时检查').length).toBeGreaterThan(0);}
 const f06=r2CreateJoker('f06','life',0);f06.counters={...(f06.counters??{}),handsScored:2};expect(jokerMemory(definition('f06'),f06,context()).remaining).toBe(2);expect(jokerMemoryAbility(definition('f08'),undefined,context()).condition).toContain('1/3');expect(jokerMemoryAbility(definition('f08'),r2CreateJoker('f08','f',0),context()).state).toContain('出牌时揭晓');
 for(const size of[40,41]){const a04=jokerMemory(definition('a04'),r2CreateJoker('a04','a',0),context({deckSize:size}));expect(a04.status).toBe('入场已锁定');expect(a04.staticRules[0]).toContain('入场已锁定上限10');expect(a04.staticRules[0]).toContain('当前牌组'+size+'张');}
});
it('score and transaction clocks are intentionally separate; actual histories do not count unsent currenthand',()=>{
 const score:R2ScoreConditionContext={played:hand.slice(0,5),active:hand.slice(0,3),held:[hand[5]],validHeld:[hand[5]],scoringIds:['a','b','c'],handType:'three-kind',previousHandType:null,gold:3,handsAfter:3,playIndex:1,discardsUsed:0,extraExecutions:0,resolvedFinal:null,stageHeatBefore:'0',stageTargetHeat:'1000'};
 expect(r2ScoreConditionMatches({kind:'resource',resource:'hands-after',equals:3},score)).toBe(true);expect(r2TransactionConditionMatches({kind:'resource',resource:'hands-after',equals:3},context().transaction)).toBe(false);
 expect(r2ScoreConditionMatches({kind:'played-count',equals:5},score)).toBe(true);expect(r2ScoreConditionMatches({kind:'paired-rank',minimum:3},score,hand[0])).toBe(true);expect(r2ScoreConditionMatches({kind:'all-played-active',minimum:1},score)).toBe(false);
 expect(r2TransactionConditionMatches({kind:'stage-hand-types-all',values:['straight','flush']},context().transaction)).toBe(false);expect(r2TransactionConditionMatches({kind:'no-joker-sale-this-stage'},{...context().transaction,jokerSold:true})).toBe(false);
 const lost={...score,active:[hand[0],hand[2]],scoringIds:['a','b','c']};expect(r2ScoreConditionMatches({kind:'scoring-position',position:'third-original'},lost,hand[2])).toBe(true);const thirdGone={...score,active:[hand[0],hand[1]]};expect(thirdGone.active.some(c=>r2ScoreConditionMatches({kind:'scoring-position',position:'third-original'},thirdGone,c))).toBe(false);expect(r2ScoreConditionMatches({kind:'scoring-position',position:'last'},lost,hand[2])).toBe(true);
 const held=[card('h1',11),card('h2',2),card('h3',11)],heldCtx={...score,held,validHeld:held.slice(1)};expect(r2ScoreConditionMatches({kind:'held-count',minimum:3},heldCtx)).toBe(true);expect(r2ScoreConditionMatches({kind:'held-rank-first',values:[11],limit:1},heldCtx,held[2])).toBe(true);expect(r2ScoreConditionMatches({kind:'held-rank-first',values:[11],limit:1},heldCtx,held[0])).toBe(false);
});
it('random operations retain event-time status before and after legal selection; deterministic hooks still match',()=>{for(const f of [undefined,facts()]){const m=jokerMemory(definition('f08'),r2CreateJoker('f08','random',0),context({facts:f}));expect(m.hooks[0].status).toBe('事件时检查');expect(m.status).toBe('事件时检查');expect(m.hooks[0].status).not.toBe('条件满足');}expect(jokerMemory(definition('f04'),r2CreateJoker('f04','heat',0),context()).hooks[0].status).toBe('条件满足');});
it('both c11 transition directions summarize the satisfied route without claiming all hooks match',()=>{
 for(const [current,previous]of[['straight','flush'],['flush','straight'],['three-kind','flush']]as const){const chosen=current==='straight'?[card('s8',8),card('s9',9,'clubs'),card('s10',10,'hearts'),card('s11',11),card('s12',12)]:current==='flush'?[card('f2',2,'hearts'),card('f5',5,'hearts'),card('f8',8,'hearts'),card('f11',11,'hearts'),card('f13',13,'hearts')]:hand.slice(0,5),f=r2SelectionFacts({hand:chosen,selectedIds:chosen.map(c=>c.id),jokers:[],definitions:R2_JOKERS,disabledIds:[]}),ctx=context({hand:chosen,facts:f,previousHandType:previous}),m=jokerMemory(definition('c11'),r2CreateJoker('c11','transition',0),ctx),yes=m.hooks.filter(h=>h.status==='条件满足');if(current==='three-kind'){expect(m.status).toBe('当前未满足');expect(yes).toHaveLength(0);}else{expect(yes).toHaveLength(1);expect(m.status).toBe('部分条件满足');expect(m.statusDetail).toContain(yes[0].condition);expect(m.hooks.filter(h=>h.status==='当前未满足')).toHaveLength(1);expect(jokerMemoryAbility(definition('c11'),r2CreateJoker('c11','t',0),ctx).state).toContain('上手'+(previous==='flush'?'同花':'顺子')+' → 本手'+(current==='straight'?'顺子':'同花')+'符合条件');}const score=scoreR2Hand({rulesVersion:'r2',runId:'c11-memory',rootId:'c11-memory/'+current,hand:chosen,disabledIds:[],selectedIds:chosen.map(c=>c.id),jokers:[r2CreateJoker('c11','transition',0)],definitions:R2_JOKERS,characterId:'neutral',handLevels:{},playIndex:2,handsBeforePlay:4,previousHandType:previous,wager:false,rng:{algorithm:'fnv1a-mulberry32-v1',state:41}});expect(score.events.filter(e=>e.sourceDefinitionId==='c11')).toHaveLength(current==='three-kind'?0:1);}
});
it('first discard and quad refund expose one/zero remaining attempts from stage history, including next-stage reset',()=>{
 for(const id of ['d05','b12'])for(const used of [false,true]){const ctx=context({discardsUsed:used?1:0,quadRefundUsed:used}),m=jokerMemory(definition(id),r2CreateJoker(id,id,0),ctx);expect(m.remainingUses).toBe(used?0:1);expect(m.short).toBe(used?'余0次':'余1次');expect(m.savedShort).toBe(m.short);expect(jokerMemoryAbility(definition(id),r2CreateJoker(id,id,0),ctx).state).toContain('本场还可用 '+(used?0:1)+' 次');expect(m.hooks[0].status).toBe('事件时检查');const next=jokerMemory(definition(id),r2CreateJoker(id,id,0),context({discardsUsed:0,quadRefundUsed:false}));expect(next.remainingUses).toBe(1);}
 const refunded=context({discardsUsed:1,handsLeft:4,quadRefundUsed:true});expect(jokerMemory(definition('d05'),r2CreateJoker('d05','d',0),refunded).remainingUses).toBe(0);expect(jokerMemory(definition('b12'),r2CreateJoker('b12','b',0),refunded).remainingUses).toBe(0);
});
