import {describe,it,expect} from 'vitest';
import {numberImpact,numberPulse,impactBeat} from '../src/game/ScoreEnergy';
import {freshOpeningShow,recordOpeningShow} from '../src/domain/openingShow';
import {createRun,applyCommand,type Action,type R2RunState} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {keyHighlight} from '../src/game/JokerKeyHighlight';
import type {ScoreEvent,ScoreTrace} from '../src/domain/scoreR2';
const fraction=(n:number)=>({n:String(n),d:'1'});
const event=(operation='add-heat',beforeM=4,afterM=4):ScoreEvent=>({eventId:'energy/hand/1/event/1',rootId:'energy/hand/1',rootEventId:'energy/hand/1/event/1',phase:'jokerScore',sourceType:'joker',sourceDefinitionId:'mantangcai',sourceInstanceId:'owned/joker',operation:operation as ScoreEvent['operation'],value:fraction(2),before:{H:fraction(20),M:fraction(beforeM)},after:{H:fraction(25),M:fraction(afterM)},reasonKey:'controlled',visibleCondition:{kind:'always'},retriggerDepth:0});
const trace=(events:ScoreEvent[],score='35')=>({rootId:'energy/hand/1',events:[...events,{...event(),eventId:'energy/hand/1/event/9',phase:'finalScore'}],finalScore:score} as ScoreTrace);
describe('committed numeric energy without bookkeeping hype',()=>{
 it('ordinary and quarter-target contributions have different short beat and one clean color',()=>{const ordinary=numberImpact(event(),'400')!;expect(ordinary.kind).toBe('add');expect(ordinary.color).toBe('#26313a');const key=numberImpact({...event(),after:{H:fraction(60),M:fraction(4)}},'400')!;expect(key.kind).toBe('key');expect(key.color).toBe('#b8473a');});
 it('actual 4→8 and 8→24 show ×2/×3, with chain progression and deep warm gold',()=>{const two=numberImpact(event('multiply-multiplier',4,8),'400',1)!,three=numberImpact(event('multiply-multiplier',8,24),'400',2)!;expect(two.factor).toBe('2');expect(three.factor).toBe('3');expect(three.peak).toBeGreaterThan(two.peak);expect(three.color).toBe('#80551f');expect(numberImpact(event('multiply-multiplier',4,8),'400',3)!.tier).toBe(3);});
 it('zero, falling multiplier and hand-after growth cannot become a numeric burst',()=>{expect(numberImpact({...event(),after:event().before},'400')).toBeUndefined();expect(numberImpact({...event('multiply-multiplier',4,3),after:{H:fraction(20),M:fraction(3)}},'400')).toBeUndefined();expect(numberImpact({...event('add-growth'),phase:'afterHand'},'400')).toBeUndefined();});
 it('held compression releases once and finishes at stable center/scale',()=>{expect(numberPulse(.15,'multiply',1.4).scale).toBe(.82);expect(numberPulse(.44,'multiply',1.4).scale).toBeCloseTo(1.4);expect(numberPulse(1,'multiply',1.4)).toEqual({scale:1,lift:0});const b=impactBeat({windup:140,flight:120,impact:210,rest:130,strength:'medium'},numberImpact(event(),'400'));expect(b.windup+b.flight+b.impact+b.rest).toBe(300);});
 it('no fixed third hand; fifth actual final-score fallback stamps once and resumes without recount',()=>{let show=freshOpeningShow();for(let n=1;n<=4;n++){show=recordOpeningShow(show,trace([]),undefined,'400');expect(show.rootId).toBeNull();}show=recordOpeningShow(show,trace([]),undefined,'400');expect(show.reason).toBe('score');expect(show.eventId).toBe('energy/hand/1/event/9');expect(recordOpeningShow(show,{...trace([]),rootId:'later'},undefined,'400')).toEqual({...show,handsScored:6});});
 it('real route growth can earn source cue without pretending current M changed; real multiplier wins earlier',()=>{const growth={...event('add-growth'),phase:'afterHand' as const};expect(recordOpeningShow(freshOpeningShow(),trace([growth]),growth,'400').reason).toBe('starter');expect(recordOpeningShow(freshOpeningShow(),trace([event('multiply-multiplier',4,8)]),undefined,'400').reason).toBe('multiply');});
 it('early game ending uses its actual final score without claiming a victory or route trigger',()=>{const show=recordOpeningShow(freshOpeningShow(),trace([]),undefined,'400',true);expect(show.handsScored).toBe(1);expect(show.reason).toBe('score');expect(show.eventId).toBe('energy/hand/1/event/9');});
 it('current actual commands count saved plays only, duplicate replay and discard do not count',()=>{
  let s=createRun({seed:'route-first-4',runId:'energy/current',characterId:'amo',rulesVersion:'r2',r2Identity:newRunIdentity('amo','flush'),openingRoute:'flush',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
  const send=(a:Action)=>{const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:a});expect(r.ok).toBe(true);if(r.ok)s=r.state;};send({type:'LeaveShop'});send({type:'EnterStage'});send({type:'DiscardHand',selectedIds:[s.handOrder[0]]});expect(s.openingShow!.handsScored).toBe(0);
  const command={runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action:{type:'PlayHand' as const,selectedIds:[s.handOrder[0]]}},r=applyCommand(s,command);expect(r.ok).toBe(true);if(!r.ok)return;s=r.state;expect(s.openingShow!.handsScored).toBe(1);const duplicate=applyCommand(s,command);expect(duplicate.ok&&duplicate.state.openingShow).toEqual(s.openingShow);expect(readCheckpoint(makeCheckpoint(s,[])).ok).toBe(true);
 });
});
