import {savedBenefit} from '../src/game/JokerExperience';
import {touyeChoice,TOUYE_RISK,savedTouyeWager} from '../src/game/TouyeWagerCopy';
import {rankAiHandCandidates,aiHandKey} from '../src/game/AiHandCandidates';
import {describe,it,expect} from 'vitest';
import {createRun,applyCommand,type R2RunState,type Action,type Command} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {SavedRun,type SaveStore,type SaveSlots} from '../src/application/SavedRun';
import {r2ScoreContext,r2CreateJoker} from '../src/domain/r2Run';
import {stableHash} from '../src/domain/hash';
import {touyeReachableTypes,touyeTargetReached,touyeSnapshotToken,TOUYE_TARGETS,type TouyeTarget} from '../src/domain/r2TouyeWager';
import {readR2Modifiers} from '../src/content/r2Schema';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import {scoreR2Hand} from '../src/domain/scoreR2';
const main=['clubs-12','hearts-13','hearts-2','spades-2','diamonds-11','diamonds-5','clubs-14','diamonds-14'];
const selected=['clubs-12','hearts-13','diamonds-11','diamonds-5'];
const start=()=>createRun({seed:'touye-public-20261008',runId:'touye-fixture',characterId:'touye',rulesVersion:'r2',r2Identity:newRunIdentity('touye','group'),openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
const cmd=(s:R2RunState,action:Action):Command=>({runId:s.runId,commandId:'test/'+s.commandSeq,expectedSeq:s.commandSeq,action});
function send(s:R2RunState,action:Action,j:Command[]=[]){const c=cmd(s,action),r=applyCommand(s,c);if(!r.ok)throw Error(r.code+JSON.stringify(r.diagnostic));j.push(c);expect(readCheckpoint(makeCheckpoint(r.state,j))).toMatchObject({ok:true});return r.state;}
const entered=()=>send(send(start(),{type:'LeaveShop'}),{type:'EnterStage'});
function hand(s:R2RunState,winning=false){s=structuredClone(s);s.handOrder=main;s.playedPile=[];s.discardPile=[];const incoming=winning?['hearts-14','clubs-2','clubs-6','spades-9']:['clubs-3','spades-5','hearts-9','spades-11'];s.drawPile=[...s.deckInstances.map(c=>c.id).filter(id=>!main.includes(id)&&!incoming.includes(id)),...incoming.reverse()];return s;}
function bet(s:R2RunState,target:TouyeTarget='three-kind',ids=selected):Action{const cards=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!),m=readR2Modifiers(s.jokers,r2JokerDefinitionsFor(s));return{type:'DiscardHand',selectedIds:ids,touyeBet:{target,snapshotToken:touyeSnapshotToken(cards,{fourStraight:m.fourStraight,fourFlush:m.fourFlush},s.stage!.index,s.stage!.playIndex+1,s.commandSeq)}};}
function corrupt(s:R2RunState,f:(s:R2RunState)=>void){const cp=structuredClone(makeCheckpoint(s,[]));f(cp.state);const{checksum,...p}=cp;return readCheckpoint({...p,checksum:stableHash(p)});}
describe('Touye public pre-discard commitment',()=>{
 it('uses whole hand and explicit upgrade sets without score or hidden inputs',()=>{const s=hand(entered()),cards=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);expect(new Set(touyeReachableTypes(cards,{}))).toEqual(new Set(['high-card','pair','two-pair']));expect(touyeTargetReached('three-kind','full-house')).toBe(true);expect(touyeTargetReached('three-kind','flush')).toBe(false);expect(touyeTargetReached('two-pair','four-kind')).toBe(false);expect(touyeTargetReached('flush','straight-flush')).toBe(true);expect(applyCommand(s,cmd(s,bet(s,'two-pair')))).toMatchObject({ok:false,code:'touye-target-already-reachable'});expect(s.stage!.touyeWager!.resolution).toBe('unused');});
 it('four-card inventory rules affect eligibility while disabled cards still classify',()=>{const s=hand(entered()),cards=['hearts-2','spades-3','clubs-4','diamonds-5'].map(id=>s.deckInstances.find(c=>c.id===id)!);expect(touyeReachableTypes(cards,{})).not.toContain('straight');expect(touyeReachableTypes(cards,{fourStraight:true})).toContain('straight');const flush=['hearts-2','hearts-4','hearts-6','hearts-8'].map(id=>s.deckInstances.find(c=>c.id===id)!);expect(touyeReachableTypes(flush,{fourFlush:true})).toContain('flush');});
 it('stale snapshot and invalid target/empty discard are rejected without spending',()=>{const s=hand(entered()),a=bet(s),reordered=send(s,{type:'ReorderHand',ids:[...s.handOrder].reverse()});expect(applyCommand(reordered,cmd(reordered,a))).toMatchObject({ok:false,code:'touye-stale-snapshot'});expect(applyCommand(s,cmd(s,{...a,selectedIds:[]} as Action))).toMatchObject({ok:false,code:'empty-selection'});expect(applyCommand(s,cmd(s,{...a,touyeBet:{target:'pair',snapshotToken:'x'}} as unknown as Action))).toMatchObject({ok:false,code:'invalid-touye-bet'});expect(applyCommand(s,cmd(s,{type:'SetWager',enabled:true}))).toMatchObject({ok:false,code:'touye-use-discard-bet'});expect(s.stage!.discardsUsed).toBe(0);});
 it.each([false,true])('actual next hand settles one deterministic role multiplier (winning=%s)',winning=>{const s=hand(entered(),winning);s.jokers=[r2CreateJoker('mantangcai','group-clock',4,'none',s)];s.stage!.initialJokerIds=['group-clock'];const j:Command[]=[],p=send(s,bet(s),j);expect(p.gold).toBe(s.gold);expect(p.stage!.discardsUsed).toBe(1);expect(p.stage!.discardsLeft).toBe(2);expect(p.stage!.touyeWager!.resolution).toBe('pending');expect(p.rng.rule).toEqual(s.rng.rule);const ids=winning?['clubs-14','diamonds-14','hearts-14','hearts-2','spades-2']:['clubs-14','diamonds-14','hearts-2','spades-2'],a=send(p,{type:'PlayHand',selectedIds:ids},j),t=a.lastTrace!;expect(t.touyeWager).toMatchObject({outcome:winning?'won':'lost',multiplier:winning?'2':'0.85'});expect(savedTouyeWager(t)).toContain(winning?'达成×2':'未成×0.85');const receipt=savedBenefit(a,t,t.events.find(e=>e.sourceType==='character')!);expect(receipt?.effect).toContain(winning?'达成×2':'未成×0.85');expect(receipt?.title).toBe('骰爷 · 赌约已结算');expect(t.events.filter(e=>e.sourceType==='character')).toHaveLength(1);expect(t.events.find(e=>e.sourceType==='character')!.value).toEqual(winning?{n:'2',d:'1'}:{n:'17',d:'20'});expect(t.rng).toEqual(p.rng.rule);expect(a.stage!.touyeWager!.resolution).toBe('played');expect(a.stage!.playIndex).toBe(1);const before=t.events.findIndex(e=>e.sourceType==='character'),joker=t.events.findIndex(e=>e.phase==='jokerScore');expect(joker).toBeGreaterThan(before);const repeated=applyCommand(a,j.at(-1)!);expect(repeated.ok&&repeated.duplicate).toBe(true);if(a.phase==='await-input')expect(applyCommand(a,cmd(a,bet(a,'three-kind',[a.handOrder[0]])))).toMatchObject({ok:false,code:'touye-already-used'});else{const next=send(send(send(a,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(next.stage!.touyeWager).toEqual({commit:null,resolution:'unused'});}});
 it('ordinary next low card really loses, no free postponement, then ordinary 1.15 returns',()=>{const p=send(hand(entered()),bet(hand(entered()))),a=send(p,{type:'PlayHand',selectedIds:['clubs-3']});expect(a.lastTrace!.touyeWager!.outcome).toBe('lost');const b=send(a,{type:'PlayHand',selectedIds:[a.handOrder[0]]});expect(b.lastTrace!.touyeWager).toEqual({commit:null,outcome:'ordinary',multiplier:'1.15'});});
 it('pending rejects further discard, target, tools and joker changes; hand sort/restore/abandon preserve costs',()=>{const p=send(hand(entered()),bet(hand(entered()))),snapshot=structuredClone(p);for(const a of [{type:'DiscardHand',selectedIds:p.handOrder.slice(0,1)},{type:'SetWager',enabled:false},{type:'UseConsumable',instanceId:'none',targetIds:[]},{type:'DestroyConsumable',instanceId:'none'},{type:'ReorderJokers',ids:[]} ] as Action[])expect(applyCommand(p,cmd(p,a))).toMatchObject({ok:false,code:'touye-next-hand-locked'});expect(p).toEqual(snapshot);const sorted=send(p,{type:'ReorderHand',ids:[...p.handOrder].reverse()});expect(sorted.stage!.touyeWager).toEqual(p.stage!.touyeWager);const a=send(sorted,{type:'AbandonRun'});expect(a.gold).toBe(p.gold);expect(a.stage!.discardsLeft).toBe(p.stage!.discardsLeft);expect(a.stage!.playIndex).toBe(0);expect(a.stage!.touyeWager!.resolution).toBe('abandoned');expect(a.lastTrace).toBe(null);expect(corrupt(a,s=>s.stageIndex++).ok).toBe(false);});
 it('both saving failures retry exact fixed candidates, preserve commitment and never repeat payouts',async()=>{const s=hand(entered());let slots:SaveSlots={revision:1,current:makeCheckpoint(s,[]),previous:null},fail=true;const writes:string[]=[];const store:SaveStore={read:async()=>slots,commit:async(rev,cp,backup)=>{writes.push(JSON.stringify(cp));if(fail)throw Error('quota');slots={revision:rev+1,current:cp,previous:backup};return slots.revision;}};const run=SavedRun.restore(store,slots);expect((await run.dispatch(bet(s))).ok).toBe(false);expect(run.state).toEqual(s);fail=false;expect((await run.retry()).ok).toBe(true);expect(writes[0]).toBe(writes[1]);const p=run.state;expect(SavedRun.restore(store,slots).state).toEqual(p);fail=true;expect((await run.dispatch({type:'PlayHand',selectedIds:['clubs-3']})).ok).toBe(false);expect(run.state).toEqual(p);fail=false;expect((await run.retry()).ok).toBe(true);expect(writes[2]).toBe(writes[3]);expect(SavedRun.restore(store,slots).state).toEqual(run.state);expect(run.state.stage!.playIndex).toBe(1);});
 it('Q01/B08 refuse, B01/B07 original costs and B14 only one actual discard remain',()=>{let q=createRun({seed:'challenge/q01/0',runId:'q-touye',characterId:'touye',rulesVersion:'r2',r2Identity:newRunIdentity('touye','group'),openingRoute:'group',modeConfig:{mode:'challenge',difficulty:0,challengeId:'Q01',programsEnabled:false}});q=hand(send(send(q,{type:'LeaveShop'}),{type:'EnterStage'}));expect(applyCommand(q,cmd(q,bet(q)))).toMatchObject({ok:false,code:'touye-disabled'});for(const id of ['B01','B07','B08','B14'] as const){let s=start();s.phase='stage-ready';s.chapter=id==='B14'?7:3;s.stageIndex=s.chapter*3-1;s.shop!.visitIndex=s.stageIndex;s.seenBossIds=id==='B14'?['B01','B02','B03','B04','B05','B06',id]:['B02','B03',id];s.boss={definitionId:id,disabledSuit:null};s=hand(send(s,{type:'EnterStage'}));if(id==='B08'){expect(applyCommand(s,cmd(s,bet(s)))).toMatchObject({ok:false,code:'touye-disabled'});continue;}const p=send(s,bet(s));expect(s.stage!.discardsLeft-p.stage!.discardsLeft).toBe(id==='B01'?2:1);expect(s.gold-p.gold).toBe(id==='B07'?1:0);expect(p.stage!.discardsUsed).toBe(1);if(id==='B14')expect(BigInt(p.stage!.targetHeat)-BigInt(s.stage!.targetHeat)).toBe((BigInt(s.stage!.initialTargetHeat)+19n)/20n);}});
 it('only actual onDiscard executes and cold f10 stays armed through pending',()=>{let s=entered();s=structuredClone(s);const cold=['spades-2','hearts-4','clubs-6','diamonds-8','spades-10','hearts-12','clubs-14','diamonds-3'];s.handOrder=cold;s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!cold.includes(id));s.jokers=[r2CreateJoker('a07','a07',4,'none',s),r2CreateJoker('f10','f10',8,'none',s)];s.stage!.initialJokerIds=['a07','f10'];const p=send(s,bet(s,'three-kind',[cold[0]]));expect(p.jokers[1].counters!.rescueArmed).toBe(true);expect(p.jokers[0].counters!.singleDiscards).toBe(1);const a=send(p,{type:'PlayHand',selectedIds:[p.handOrder[0]]});expect(a.lastTrace!.events.filter(e=>e.operation==='consume-rescue')).toHaveLength(1);});
 it('score faults keep original pending transaction and resources',()=>{const p=send(hand(entered()),bet(hand(entered()))),invalid=structuredClone(p);invalid.handLevels['high-card']=31;const before=structuredClone(invalid),r=applyCommand(invalid,cmd(invalid,{type:'PlayHand',selectedIds:['clubs-3']}));expect(r).toMatchObject({ok:false,code:'score-diagnostic'});expect(invalid).toEqual(before);});
 it('public choice shows risk and why a whole-hand attainable goal cannot be wagered without reading hidden cards/RNG',()=>{const s=hand(entered());s.drawPile=new Proxy(s.drawPile,{get(t,key){if(key==='length')return t.length;throw Error('hidden draw access');}});Object.defineProperty(s,'rng',{get(){throw Error('private RNG');}});const c=touyeChoice(s,selected);expect(TOUYE_RISK).toBe('只赌下一手，不能再弃牌；未成倍率×0.85');expect(c.choices.find(c=>c.target==='two-pair')).toMatchObject({available:false,reason:'当前整手已可达，不能押'});expect(c.choices.find(c=>c.target==='three-kind')!.available).toBe(true);});
 it('existing AI selection uses deterministic public wager context without changing state or exposing scores',()=>{const s=send(hand(entered()),bet(hand(entered()))),handCards=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!),context=r2ScoreContext(s,handCards,[]),input={hand:handCards,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),disabledIds:s.stage!.disabledIds,handRules:context.handRules,boss:s.stage!.boss,stageIndex:s.stageIndex,sealedJokerIds:[],challengeDisabledJokerId:null,resources:{gold:s.gold,handsLeft:s.stage!.handsLeft,playIndex:s.stage!.playIndex,discardsUsed:s.stage!.discardsUsed,stageHeat:s.stage!.heat,target:s.stage!.targetHeat},contentVersion:s.contentVersion,score:{...context,handLevels:s.handLevels,previousHandType:s.stage!.previousHandType,wager:false}},before=structuredClone(s),result=rankAiHandCandidates(input);expect(result.status).toBe('ready');expect(result.ordered.length).toBeGreaterThan(0);expect(aiHandKey(input)).not.toBe(aiHandKey({...input,score:{...input.score,touyeWager:undefined}}));expect(s).toEqual(before);for(const f of result.ordered)for(const key of ['score','scoreRange','events','rng','finalScore'])expect(f).not.toHaveProperty(key);expect(touyeChoice(s).pending?.target).toBe('three-kind');});
 it('strict parsing rejects source/target/token/stage/due/once/trace tampering',()=>{const p=send(hand(entered()),bet(hand(entered())));for(const f of [(s:R2RunState)=>s.stageIndex++,(s:R2RunState)=>s.stage!.touyeWager!.commit!.duePlayIndex++,(s:R2RunState)=>s.stage!.touyeWager!.commit!.target='two-pair',(s:R2RunState)=>s.stage!.touyeWager!.commit!.discardCommandId='fake',(s:R2RunState)=>s.stage!.touyeWager!.commit!.snapshotToken='fake',(s:R2RunState)=>s.stage!.touyeWager!.resolution='unused',(s:R2RunState)=>s.stage!.wagerSelected=true])expect(corrupt(p,f).ok).toBe(false);const a=send(p,{type:'PlayHand',selectedIds:['clubs-3']});for(const f of [(s:R2RunState)=>s.lastTrace!.touyeWager!.outcome='won',(s:R2RunState)=>s.lastTrace!.touyeWager!.multiplier='2',(s:R2RunState)=>s.lastTrace!.touyeWager!.commit=null,(s:R2RunState)=>s.stage!.touyeWager={commit:null,resolution:'unused'}])expect(corrupt(a,f).ok).toBe(false);});
});
