import {describe,it,expect,vi} from 'vitest';
import {createRun,applyCommand,type R2RunState,type Action,type Command} from '../src/domain/run';
import {newRunIdentity} from '../src/game/RunLaunch';
import {makeCheckpoint,readCheckpoint} from '../src/application/checkpoint';
import {SavedRun,type SaveStore,type SaveSlots} from '../src/application/SavedRun';
import {stableHash} from '../src/domain/hash';
import {r2CreateJoker,r2ScoreContext} from '../src/domain/r2Run';
import {r2JokerDefinitionsFor} from '../src/domain/r2ContentProfiles';
import * as scoring from '../src/domain/scoreR2';
import {xiemuChoice,savedXiemuBurn} from '../src/game/XiemuBurnCopy';
import {R2_AZAO_CHARGE_HASH,R2_AZAO_CHARGE_VERSION} from '../src/domain/r2GroupUpgrade';
const ids=['hearts-2','spades-2','clubs-14','diamonds-14'];
function start(){return createRun({seed:'group-natural-17',runId:'xiemu-test',characterId:'xiemu',rulesVersion:'r2',r2Identity:newRunIdentity('xiemu','group'),openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});}
function command(s:R2RunState,action:Action):Command{return{runId:s.runId,commandId:'c/'+s.commandSeq,expectedSeq:s.commandSeq,action};}
function send(s:R2RunState,action:Action,journal:Command[]=[]){const c=command(s,action),r=applyCommand(s,c);if(!r.ok)throw Error(r.code+JSON.stringify(r.diagnostic));journal.push(c);expect(readCheckpoint(makeCheckpoint(r.state,journal))).toMatchObject({ok:true});return r.state;}
function entered(cash=12){let s=send(send(start(),{type:'LeaveShop'}),{type:'EnterStage'});s=structuredClone(s);s.gold=cash;return s;}
function arrange(s:R2RunState,hand:string[]){s=structuredClone(s);s.handOrder=hand;s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!hand.includes(id)&&!s.playedPile.includes(id)&&!s.discardPile.includes(id));return s;}
function input(s:R2RunState){const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)!);return{rulesVersion:'r2' as const,runId:s.runId,rootId:s.runId+'/hand/test',hand,selectedIds:ids,disabledIds:s.stage!.disabledIds,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),handLevels:s.handLevels,playIndex:s.stage!.playIndex+1,handsBeforePlay:s.stage!.handsLeft,previousHandType:s.stage!.previousHandType,wager:false,rng:s.rng.rule,...r2ScoreContext(s,hand,ids)};}
function tamper(s:R2RunState,change:(s:R2RunState)=>void){const cp=structuredClone(makeCheckpoint(s,[]));change(cp.state);const{checksum,...body}=cp;return readCheckpoint({...body,checksum:stableHash(body)});}
describe('xiemu bounded pay/score/clear transaction',()=>{
 it('cost and used marker commit once, duplicate and next stage do not replay',()=>{const before=entered(),journal:Command[]=[],after=send(before,{type:'PlayHand',selectedIds:ids,xiemuBurn:10},journal);expect(before.gold).toBe(12);expect(before.stage!.xiemuBurnUsed).toBe(false);expect(after.gold).toBe(2);expect(after.stage!.xiemuBurnUsed).toBe(true);expect(after.lastTrace!.xiemuBurn).toEqual({cost:10,goldBefore:12,goldAfter:2,beforeUsed:false,afterUsed:true,multiplier:2});const repeat=applyCommand(after,journal[0]);expect(repeat.ok&&repeat.duplicate).toBe(true);if(repeat.ok)expect(repeat.state).toEqual(after);expect(applyCommand(after,command(after,{type:'PlayHand',selectedIds:after.handOrder.slice(0,1),xiemuBurn:10}))).toMatchObject({ok:false,code:'xiemu-already-used'});const abandoned=send(after,{type:'AbandonRun'});expect(abandoned.gold).toBe(2);expect(abandoned.stage!.xiemuBurnUsed).toBe(true);});
 it('all three tiers multiply at character clock before Joker, no free old last-hand effect',()=>{const s=entered(35);for(const [cost,m] of [[10,2],[20,3],[30,4]] as const){const after=send(s,{type:'PlayHand',selectedIds:ids,xiemuBurn:cost});expect(after.lastTrace!.xiemuBurn!.goldAfter).toBe(35-cost);const e=after.lastTrace!.events.find(e=>e.sourceType==='character'&&e.phase==='characterScore')!;expect(e.value).toEqual({n:String(m),d:'1'});}const i=input(s),hold=scoring.scoreR2Hand({...i,handsBeforePlay:1}),old=scoring.scoreR2Hand({...i,xiemuBurn:undefined,handsBeforePlay:1});expect(hold.events.filter(e=>e.sourceType==='character')).toEqual([]);expect(BigInt(old.finalScore)).toBe(BigInt(hold.finalScore)*2n);});
 it('insufficient/malformed/low main refuse whole transaction and never downgrade',()=>{const s=entered(18),snapshot=structuredClone(s);for(const cost of [20,30] as const)expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:ids,xiemuBurn:cost}))).toMatchObject({ok:false,code:'insufficient-gold'});for(const selectedIds of [ids.slice(0,1),ids.slice(0,2)])expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds,xiemuBurn:10}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'xiemu-unqualified'}});expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:ids,xiemuBurn:15 as 10}))).toMatchObject({ok:false,code:'invalid-xiemu-burn'});expect(s).toEqual(snapshot);});
 it('held money hooks read paid balance, old free x2/+2 are replaced, cap interest reads pre-reward',()=>{let s=entered(25);s.jokers=[r2CreateJoker('e03','held/e03',6,'none',s),r2CreateJoker('e08','held/e08',8,'none',s)];s.stage!.initialJokerIds=s.jokers.map(j=>j.instanceId);const after=send(s,{type:'PlayHand',selectedIds:ids,xiemuBurn:10});expect(after.lastTrace!.events.find(e=>e.sourceDefinitionId==='e03')!.value).toEqual({n:'30',d:'1'});expect(after.lastTrace!.events.some(e=>e.sourceDefinitionId==='e08')).toBe(false);expect(after.lastTrace!.events.findIndex(e=>e.phase==='characterScore')).toBeLessThan(after.lastTrace!.events.findIndex(e=>e.phase==='jokerScore'));});
 it('successful burn reward clock is paid money, stage reset and idempotent clear',()=>{let s=arrange(entered(20),['hearts-14','spades-14','clubs-14','hearts-13','spades-13']);const journal:Command[]=[],after=send(s,{type:'PlayHand',selectedIds:s.handOrder,xiemuBurn:10},journal);expect(after.phase).toBe('stage-cleared');expect(after.lastTrace!.combo!.goldBeforeRewards).toBe(10);const interest=after.lastTrace!.events.find(e=>e.sourceDefinitionId==='xiemu'&&e.phase==='onStageClear')!;expect(interest.value).toEqual({n:'2',d:'1'});expect(interest.goldBeforeRewards).toBe(10);expect(after.gold).toBe(10+4+3+2+2);expect(savedXiemuBurn(after)).toContain('奖励前本金10');const duplicate=applyCommand(after,journal[0]);expect(duplicate.ok&&duplicate.duplicate).toBe(true);const next=send(send(send(after,{type:'OpenShop'}),{type:'LeaveShop'}),{type:'EnterStage'});expect(next.stage!.xiemuBurnUsed).toBe(false);expect(next.gold).toBe(after.gold);});
 it('last-hand success earns only new capital interest, not the former plus2 reward',()=>{let s=entered(5);for(let n=0;n<3;n++){const id=s.handOrder.find(id=>s.deckInstances.find(c=>c.id===id)!.rank<=10)!;s=send(s,{type:'PlayHand',selectedIds:[id]});}s=arrange(s,['hearts-14','spades-14','clubs-14','hearts-13','spades-13']);const after=send(s,{type:'PlayHand',selectedIds:s.handOrder});expect(after.phase).toBe('stage-cleared');expect(after.stage!.handsLeft).toBe(0);expect(after.gold).toBe(5+4+1+1);expect(after.lastTrace!.events.filter(e=>e.sourceType==='character').map(e=>[e.phase,e.value.n])).toEqual([['onStageClear','1']]);});
 it('B08 blocks burn keeps resource interest; Q01 disables both',()=>{let ready=start();ready.phase='stage-ready';ready.chapter=3;ready.stageIndex=8;ready.seenBossIds=['B01','B02','B08'];ready.boss={definitionId:'B08',disabledSuit:null};ready.shop!.visitIndex=8;ready.gold=10;ready.handLevels['full-house']=30;let s=arrange(send(ready,{type:'EnterStage'}),['hearts-14','spades-14','clubs-14','hearts-13','spades-13']);expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:s.handOrder,xiemuBurn:10}))).toMatchObject({ok:false,code:'xiemu-disabled'});const r=applyCommand(s,command(s,{type:'PlayHand',selectedIds:s.handOrder}));expect(r.ok).toBe(true);if(r.ok)expect(r.state.lastTrace!.events.find(e=>e.sourceType==='character'&&e.phase==='onStageClear')!.value.n).toBe('2');let q=createRun({seed:'challenge/q01/0',runId:'q',characterId:'xiemu',rulesVersion:'r2',r2Identity:newRunIdentity('xiemu','group'),openingRoute:'group',modeConfig:{mode:'challenge',difficulty:0,challengeId:'Q01',programsEnabled:false}});q=send(send(q,{type:'LeaveShop'}),{type:'EnterStage'});q=arrange(q,['hearts-14','spades-14','clubs-14','hearts-13','spades-13']);q.gold=20;expect(applyCommand(q,command(q,{type:'PlayHand',selectedIds:q.handOrder,xiemuBurn:10}))).toMatchObject({ok:false,code:'xiemu-disabled'});const a=send(q,{type:'PlayHand',selectedIds:q.handOrder});expect(a.lastTrace!.events.some(e=>e.sourceType==='character')).toBe(false);});
 it('score fault keeps original cash and eligibility',()=>{const s=entered(),before=structuredClone(s),fault=vi.spyOn(scoring,'scoreR2Hand').mockImplementation(()=>{throw new scoring.ScoreFault('controlled-score-fault',[]);});try{expect(applyCommand(s,command(s,{type:'PlayHand',selectedIds:ids,xiemuBurn:10}))).toMatchObject({ok:false,code:'score-diagnostic',diagnostic:{code:'controlled-score-fault'}});expect(s).toEqual(before);}finally{fault.mockRestore();}});
 it('save failure retries exact paid candidate once and restores',async()=>{const before=entered();let slots:SaveSlots={revision:1,current:makeCheckpoint(before,[]),previous:null},fail=true;const candidates:string[]=[];const store:SaveStore={read:async()=>slots,commit:async(revision,cp,backup)=>{candidates.push(JSON.stringify(cp));if(fail)throw Error('quota-exceeded');slots={revision:revision+1,current:cp,previous:backup};return slots.revision;}};const saved=SavedRun.restore(store,slots);expect((await saved.dispatch({type:'PlayHand',selectedIds:ids,xiemuBurn:10})).ok).toBe(false);expect(saved.state).toEqual(before);fail=false;expect((await saved.retry()).ok).toBe(true);expect(candidates[1]).toEqual(candidates[0]);expect(saved.state.gold).toBe(2);expect(saved.state.stage!.xiemuBurnUsed).toBe(true);expect(SavedRun.restore(store,slots).state).toEqual(saved.state);expect((await saved.retry()).ok).toBe(false);});
 it('strict current parsing rejects paid clock/tier/used/effect/extra interest corruption',()=>{let s=arrange(entered(20),['hearts-14','spades-14','clubs-14','hearts-13','spades-13']);const a=send(s,{type:'PlayHand',selectedIds:s.handOrder,xiemuBurn:10});for(const change of [(s:R2RunState)=>delete s.stage!.xiemuBurnUsed,(s:R2RunState)=>s.stage!.xiemuBurnUsed=false,(s:R2RunState)=>s.lastTrace!.xiemuBurn!.goldAfter=11,(s:R2RunState)=>s.lastTrace!.xiemuBurn!.cost=20,(s:R2RunState)=>s.lastTrace!.events.find(e=>e.phase==='characterScore')!.value.n='3',(s:R2RunState)=>s.lastTrace!.events.find(e=>e.sourceDefinitionId==='xiemu'&&e.phase==='onStageClear')!.goldBeforeRewards=20])expect(tamper(a,change).ok).toBe(false);});
 it('public costs are explicit and choice/cancel cannot debit; original identity is preserved',()=>{const s=entered(18),before=structuredClone(s),copy=xiemuChoice(s,'straight',10);expect(copy.choices[0].details).toContain('花后8金');expect(copy.choices[0].details).toContain('常规息少2、角色息少1');expect(copy.choices[1].reason).toContain('金币不足');expect(xiemuChoice(s,'high-card').choices[0].available).toBe(false);expect(s).toEqual(before);const old=createRun({seed:'group-natural-17',runId:'old',characterId:'xiemu',rulesVersion:'r2',r2Identity:{contentVersion:R2_AZAO_CHARGE_VERSION,contentHash:R2_AZAO_CHARGE_HASH},openingRoute:'group',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});expect(old.contentVersion).toBe(R2_AZAO_CHARGE_VERSION);expect(readCheckpoint(makeCheckpoint(old,[])).ok).toBe(true);});
});
