/** Two finite controlled terminal commands; software output, never natural campaign/device acceptance. */
import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {chromium} from 'playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {tapUI,waitScene} from './ui.mjs';
import {installOutputTap,startClip} from './native-clip.mjs';
const root=process.env.FINALE_ROOT??process.cwd(),before=!!process.env.FINALE_BEFORE,out=process.env.FINALE_OUTPUT??'/tmp/finale',review=process.env.FINALE_REVIEW;
const prior=review?JSON.parse(await readFile(review,'utf8')):undefined;
await mkdir(out,{recursive:true});const server=await createServer({root,mode:'e2e',server:{host:'127.0.0.1',port:5567,strictPort:true},logLevel:'error'});await server.listen();
const {makeCheckpoint,readCheckpoint}=await server.ssrLoadModule('/src/application/checkpoint.ts'),{finaleReady}=await server.ssrLoadModule('/harness/fixtures/finale.ts'),{heroClimaxFixture,energySend}=await server.ssrLoadModule('/harness/fixtures/hero-climax.ts'),{applyCommand}=await server.ssrLoadModule('/src/domain/run.ts');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']}),report={head:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),before,reviewSource:prior?.head,scope:review?'Readonly import of exact terminal states from the earlier native command report; only final visual corrections and controls reviewed. No new scoring/audio transaction or natural campaign claim.':'Existing controlled C04 final-stage entry plus one real final PlayHand, and existing failure last hand. Actual UI/save/audio and finite software frames; not naturally acquired eight chapters, GPU/FPS, hearing or human acceptance.',cases:[]};
const readState=p=>p.evaluate(()=>window.__harness.game.registry.get('runController').state);
async function importState(p,s){const cp=makeCheckpoint(s,[]);assert.ok(readCheckpoint(cp).ok);await p.goto('http://127.0.0.1:5567/?harness=1');await waitScene(p,'title');await p.locator('.run-menu-toggle').click();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').click();const chooser=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await chooser).setFiles({name:'finale.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});}
async function snapshot(p,row,key,viewport){await p.setViewportSize(viewport);await p.waitForTimeout(240);const regions=await p.evaluate(()=>{const s=window.__harness.game.scene.getScene('intermission'),all=[],walk=l=>{for(const o of l){all.push(o);if(o.list)walk(o.list);}};walk(s.view.root.list);const stage=all.find(o=>o.name==='result-art/stage').getData('bounds');return {stage,texts:all.filter(o=>o.type==='Text'&&/^result\//.test(o.name)).map(o=>({name:o.name,text:o.text,bounds:o.getBounds()})),art:all.filter(o=>/^result-art\/(hero|source)$/.test(o.name)).map(o=>({name:o.name,bounds:o.getBounds()}))};});row.views.push({key,viewport,regions});await p.screenshot({path:out+'/'+key+'.png',scale:'css'});assert.deepEqual(await readState(p),row.after);for(const x of [...regions.texts,...regions.art]){assert.ok(x.bounds.y>=0&&x.bounds.y+x.bounds.height<=viewport.height,x.name+' in viewport');if(['result/score','result/gap','result/last-hand','result/failure-reason'].includes(x.name))assert.ok(x.bounds.y+x.bounds.height<=regions.stage.y+regions.stage.height+1,x.name+' in stage');}return regions;}
try{for(const kind of ['win','failure']){const viewport=kind==='win'?{width:1366,height:768}:{width:390,height:740},touch=viewport.width<800,p=await browser.newPage({viewport,hasTouch:touch,deviceScaleFactor:1}),row={kind,errors:[],views:[]};report.cases.push(row);p.setDefaultTimeout(24000);p.on('dialog',d=>d.accept());p.on('pageerror',e=>row.errors.push(e.stack));await installOutputTap(p,{music:.30,sfx:.80});try{
 const f=kind==='win'?{state:finaleReady(),assistIds:[]}:heroClimaxFixture('failure'),selectedIds=kind==='win'?f.state.handOrder.slice(0,5):f.selectedIds,action={type:'PlayHand',selectedIds};row.before=f.state;
 if(before||review){row.after=review?prior.cases.find(r=>r.kind===kind).after:energySend(f.state,action);await importState(p,row.after);await waitScene(p,'intermission');await p.waitForTimeout(1100);}
 else{await importState(p,f.state);await waitScene(p,'game');await p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.ready&&!s.playing&&!s.presentation;});if(await p.getByRole('button',{name:'开始出牌',exact:true}).isVisible())await p.getByRole('button',{name:'开始出牌',exact:true}).click();if(await p.locator('.detail-dialog[open]').count())await p.getByRole('button',{name:'关闭',exact:true}).click();for(const id of selectedIds)await tapUI(p,'game','card/'+id,touch);const clip=await startClip(p,out,kind);await tapUI(p,'game','action/play',touch);await waitScene(p,'intermission');row.after=await readState(p);const receipt=row.after.receipts.find(r=>r.seq===row.after.commandSeq),result=applyCommand(f.state,{runId:f.state.runId,commandId:receipt.commandId,expectedSeq:f.state.commandSeq,action});assert.ok(result.ok);assert.deepEqual(row.after,result.state);await p.screenshot({path:out+'/'+kind+'-entrance.png',scale:'css'});await p.waitForTimeout(1100);row.clip=await clip.stop();assert.ok(row.clip.audioBytes>1000);}
 assert.equal(row.after.phase,kind==='win'?'run-won':'run-lost');await snapshot(p,row,kind+'-'+viewport.width+'x'+viewport.height,viewport);
 if(!before){await tapUI(p,'intermission','action/last-hand',touch);await p.getByRole('heading',{name:/留影 · 最终构筑/}).waitFor();assert.ok(await p.locator('.detail-dialog').innerText().then(t=>t.includes('余额 '+row.after.gold+' 金')));await p.screenshot({path:out+'/'+kind+'-keepsake.png',scale:'css'});await p.getByRole('button',{name:'关闭',exact:true}).click();assert.deepEqual(await readState(p),row.after);
 for(const v of kind==='win'?[{width:1280,height:720},{width:1920,height:1080},{width:390,height:660}]:[{width:320,height:740},{width:740,height:390},{width:390,height:660},{width:1366,height:768}])await snapshot(p,row,kind+'-'+v.width+'x'+v.height,v);
 await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.emulateMedia({reducedMotion:'reduce'});await p.setViewportSize(viewport);await p.waitForTimeout(150);assert.deepEqual(await readState(p),row.after);row.motion=await p.evaluate(()=>{const s=window.__harness.game.scene.getScene('intermission');return s.view.root.list.filter(o=>/result\/(victory|failure)-motion/.test(o.name)).length;});assert.equal(row.motion,0);
 if(kind==='win'){await tapUI(p,'intermission','action/continue-endless',touch);await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await readState(p),row.after);}
 }assert.deepEqual(row.errors,[]);row.status='PASS';}catch(e){row.status='FAIL';row.error=e.stack;await p.screenshot({path:out+'/'+kind+'-FAIL.png'});throw e;}finally{await p.close();}}report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;}finally{await browser.close();await server.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,error:report.error,cases:report.cases.map(r=>({kind:r.kind,status:r.status,phase:r.after?.phase,views:r.views.map(v=>v.key),clip:r.clip?.duration}))}));}
