/** Finite current-identity two-hand proof; only the non-starter shelf ID is controlled. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createServer,build,preview} from 'vite';
import {chromium} from 'playwright';
import {tapUI,waitScene,tapMenuAction} from './ui.mjs';
const dir=process.env.PAYOFF_DIR||'shots/growth-payoff',baseline=!!process.env.PAYOFF_BASELINE,root=process.env.PAYOFF_ROOT||process.cwd();await mkdir(dir,{recursive:true});
const report={source:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),baseline,scope:'Controlled non-starter shelf ID b10 only. Current identity cash, public deals, purchases and two real hands unchanged. Software Chromium, no human/device/FPS/audio acceptance.',cases:[]};
const ssr=await createServer({server:{middlewareMode:true},logLevel:'error'});let cp,expected=[],ids=[];
try {const {createRun,applyCommand}=await ssr.ssrLoadModule('/src/domain/run.ts'),{newRunIdentity}=await ssr.ssrLoadModule('/src/game/RunLaunch.ts'),{r2Price}=await ssr.ssrLoadModule('/src/domain/r2Shop.ts'),{makeCheckpoint,readCheckpoint}=await ssr.ssrLoadModule('/src/application/checkpoint.ts'),{evaluateR2Hand}=await ssr.ssrLoadModule('/src/domain/evaluateR2.ts');
const send=(s,action)=>{const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action});assert.ok(r.ok,r.code);assert.ok(readCheckpoint(makeCheckpoint(r.state,[])).ok);return r.state;};
let s=createRun({seed:'group-natural-17',runId:'growth-payoff',characterId:'erxiang',rulesVersion:'r2',r2Identity:newRunIdentity('erxiang','group'),openingRoute:'group'});const o=s.shop.offers.find(o=>o.definitionId!=='mantangcai');Object.assign(o,{definitionId:'b10',price:r2Price('b10','none',s),edition:'none'});s=send(s,{type:'BuyOffer',offerId:o.offerId});s=send(send(s,{type:'LeaveShop'}),{type:'EnterStage'});cp=makeCheckpoint(s,[]);
for(let step=0;step<2;step++){const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id));let chosen;for(let m=1;m<1<<hand.length;m++){const cards=hand.filter((_,i)=>m&(1<<i));if(cards.length===4&&evaluateR2Hand(cards,{}).type==='two-pair'){chosen=cards.map(c=>c.id);break;}}assert.ok(chosen);ids.push(chosen);s=send(s,{type:'PlayHand',selectedIds:chosen});expected.push(s);}assert.equal(expected[0].lastTrace.finalScore,'182');assert.equal(expected[1].lastTrace.finalScore,'186');await writeFile(dir+'/fixture.json',JSON.stringify({checkpoint:cp,ids,expected},null,2));}finally{await ssr.close();}
await build({root,mode:'e2e',build:{outDir:root+'/'+dir+'/build'},logLevel:'error'});const server=await preview({root,build:{outDir:root+'/'+dir+'/build'},preview:{host:'127.0.0.1',port:5401,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});report.browser=browser.version();
const state=p=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),saved=p=>p.evaluate(async()=>{const c=window.__harness.game.registry.get('runController');return {state:c.state,journal:c.journal,storage:await c.store.read()};}),settled=p=>p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s?.scene.isActive()&&s.ready&&!s.playing&&!s.presentation&&s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container));});
const inspect=p=>p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game'),walk=list=>list.flatMap(o=>[o,...(o.list?walk(o.list):[])]),all=walk(s.children.list),receipt=all.find(o=>o.name==='growth/payoff');return {receipt:receipt?.getData('receipt'),area:receipt?(()=>{const b=receipt.getData('bounds'),m=receipt.getWorldTransformMatrix(),a=m.transformPoint(0,0);return{x:a.x,y:a.y,width:b.width*m.scaleX,height:b.height*m.scaleY};})():undefined,texts:all.filter(o=>o.name?.startsWith('growth/')).map(o=>({name:o.name,text:o.text,bounds:o.getBounds(),font:o.style?.fontSize})),controls:all.filter(o=>o.input?.enabled&&o.name?.startsWith('action/')).map(o=>({name:o.name,bounds:o.getBounds()}))};});
const importSave=async p=>{await p.locator('.run-menu-toggle').click();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').click();const fc=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await fc).setFiles({name:'growth.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});await waitScene(p,'game');await settled(p);const intro=p.getByRole('button',{name:'开始出牌',exact:true});if(await intro.count())await intro.click();await settled(p);};
const shot=(p,name)=>p.screenshot({path:dir+'/'+name+'.png',scale:'css',fullPage:true});
try {for(const spec of [{width:1366,height:768},{width:390,height:740}])for(const mode of (baseline?['reduced']:['normal','fast','reduced'])){if(process.env.PAYOFF_CASES&&!process.env.PAYOFF_CASES.split(',').includes(spec.width+'-'+mode))continue;const row={spec,mode,status:'RUNNING'};report.cases.push(row);const p=await browser.newPage({viewport:spec,reducedMotion:mode==='reduced'?'reduce':'no-preference',hasTouch:spec.width<800});p.on('dialog',d=>d.accept());try{await p.goto('http://127.0.0.1:5401/?harness=1');await waitScene(p,'title');await importSave(p);assert.deepEqual(await state(p),cp.state);row.hands=[];
for(let step=0;step<2;step++){for(const id of ids[step])await tapUI(p,'game','card/'+id);if(!baseline)assert.equal((await inspect(p)).receipt,undefined,'selection replaces receipt');await tapUI(p,'game','action/play');await p.waitForFunction(seq=>window.__harness.game.registry.get('runController').state.commandSeq>seq,cp.state.commandSeq+step);
if(mode==='fast')await tapMenuAction(p,'快进当前手');
if(mode==='normal'&&!baseline){try{await p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return [...s.jokerViews.values()].some(v=>v.getData('valueLabel')?.getData('growthPayoff'));},null,{timeout:25000,polling:50});await shot(p,spec.width+'-'+mode+'-stamp-'+step);row.stampObserved=true;}catch(e){row.stampObserved=false;throw e;}}
await settled(p);assert.deepEqual(await state(p),expected[step],'full authoritative state');const detail=await inspect(p);row.lastInspection=detail;if(!baseline){assert.ok(detail.receipt,'actual readable receipt rendered');assert.equal(detail.receipt.readValue,step?'+10':'+0');assert.equal(detail.receipt.after,step?'20':'10');for(const t of detail.texts.filter(t=>t.text)){assert.ok(t.bounds.y>=detail.area.y-1&&t.bounds.y+t.bounds.height<=detail.area.y+95,t.name+' vertical bounds');for(const c of detail.controls)assert.ok(!(t.bounds.x<c.bounds.x+c.bounds.width&&c.bounds.x<t.bounds.x+t.bounds.width&&t.bounds.y<c.bounds.y+c.bounds.height&&c.bounds.y<t.bounds.y+t.bounds.height),t.name+' control overlap');}}
row.hands.push({saved:await saved(p),detail});await shot(p,spec.width+'-'+mode+'-hand-'+(step+1));}
const final=await saved(p);await p.reload();await waitScene(p,'title');assert.deepEqual(await saved(p),final,'reload keeps state journal and storage');await tapUI(p,'title','action/title-continue');await settled(p);assert.deepEqual(await saved(p),final);if(!baseline&&mode==='reduced'&&spec.width===390)for(const viewport of [{width:320,height:740},{width:740,height:390}]){await p.setViewportSize(viewport);await settled(p);await p.waitForTimeout(200);row['boundary'+viewport.width]=await inspect(p);await shot(p,viewport.width+'-same-state');assert.deepEqual(await saved(p),final);await tapUI(p,'game','card/'+expected[1].handOrder[0]);assert.equal((await inspect(p)).receipt,undefined);await tapUI(p,'game','card/'+expected[1].handOrder[0]);assert.deepEqual(await saved(p),final);}
row.final=final;row.status='PASS';}catch(e){row.status='FAIL';row.error=String(e);await shot(p,spec.width+'-'+mode+'-FAIL');throw e;}finally{await p.close();await writeFile(dir+'/report.json',JSON.stringify(report,null,2));}}
report.status='PASS';}catch(e){report.status='FAIL';report.error=String(e);process.exitCode=1;}finally{await writeFile(dir+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,error:report.error,cases:report.cases.map(r=>({spec:r.spec,mode:r.mode,status:r.status,error:r.error}))}));await browser.close();await new Promise(resolve=>server.httpServer.close(resolve));}
