import assert from 'node:assert/strict';
import {build,preview,createServer} from 'vite';
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {tapUI,waitScene,confirmHeroRoute} from './ui.mjs';
const base=process.env.HAND_PATH_OUTPUT??'shots/w6-hand-path';
await mkdir(base,{recursive:true});
const ssr=await createServer({optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true},logLevel:'error'});let send;
try{const domain=await ssr.ssrLoadModule('/src/domain/run.ts');send=(s,action)=>{const r=domain.applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action});assert.ok(r.ok,JSON.stringify(r));return r.state;};}finally{await ssr.close();}
await build({mode:'e2e',build:{outDir:base+'/build'},logLevel:'error'});
const server=await preview({build:{outDir:base+'/build'},preview:{host:'127.0.0.1',port:5425,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});
const completed=[];
try{for(const device of [{name:'pc',width:1366,height:768},{name:'phone',width:390,height:740},{name:'narrow',width:320,height:740}].filter(d=>!process.env.HAND_PATH_CASE||d.name===process.env.HAND_PATH_CASE)){
 const dir=base+'/'+device.name;await mkdir(dir,{recursive:true});const p=await browser.newPage({viewport:device,hasTouch:device.name!=='pc',reducedMotion:device.name==='pc'?'no-preference':'reduce'}),tap=(scene,name)=>tapUI(p,scene,name,device.name!=='pc'),state=()=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),draft=()=>p.evaluate(()=>{const g=window.__harness.game.scene.getScene('game');return{selected:[...g.selectedIds],assist:[...g.assistIds]};}),shot=name=>p.screenshot({path:dir+'/'+name+'.png',scale:'css'}),close=()=>p.getByRole('button',{name:'关闭',exact:true}).click();
 const settle=()=>p.waitForFunction(()=>{const h=window.__harness.game,s=h.registry.get('runController').state;if(s.phase==='shop')return h.scene.getScene('shop').ready;if(s.phase==='stage-cleared'||s.phase==='run-lost')return h.scene.isActive('intermission');const g=h.scene.getScene('game');return g.ready&&!g.presentation&&g.candidates.result?.status==='ready'&&g.cardViews.every(v=>!v.dealing&&!g.tweens.isTweening(v.container));});
 const report={head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),device,scope:'Existing single seed, natural shop purchase/public hand/real actions. Designer software route, NOT human discovery or willingness.',steps:[]};
 const command=async(before,actions,note)=>{await p.waitForFunction(seq=>window.__harness.game.registry.get('runController').state.commandSeq===seq,before.commandSeq+actions.length);await settle();const after=await state();let expected=before;for(const action of actions)expected=send(expected,action);assert.deepEqual(after,expected);report.steps.push({note,actions,before,after});return after;};
 const openCandidates=async()=>{await tap('game','selection/hand-rules');assert.ok(await p.getByRole('button',{name:'看当前手牌怎么凑',exact:true}).isVisible());await p.getByRole('button',{name:'看当前手牌怎么凑',exact:true}).click();await p.getByLabel('想尝试的组合',{exact:true}).waitFor();};
 const goal=async value=>{await p.getByLabel('想尝试的组合',{exact:true}).selectOption(value);await p.waitForFunction(value=>document.querySelector('dialog[open] select[aria-label="想尝试的组合"]')?.value===value,value);};
 const reference=()=>p.locator('dialog[open] details[data-route-reference="true"]').first();
 const retainIds=()=>reference().locator('.candidate-card-face').evaluateAll(xs=>xs.map(e=>e.dataset.cardId));
 const recordView=async note=>{report.steps.push({note,copy:await p.locator('dialog[open]').innerText(),view:await p.locator('dialog[open]').evaluate(d=>{const footer=d.querySelector('.dialog-actions').getBoundingClientRect(),heading=d.querySelector('h2').getBoundingClientRect(),bounds=d.getBoundingClientRect();return{bounds:bounds.toJSON(),heading:heading.toJSON(),scrollTop:d.scrollTop,footer:footer.toJSON(),controls:[...d.querySelectorAll('button,select')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent,height:e.getBoundingClientRect().height})),faces:[...d.querySelectorAll('.candidate-card-face')].filter(e=>e.getClientRects().length).map(e=>({id:e.dataset.cardId,text:e.textContent,bounds:e.getBoundingClientRect().toJSON()}))};})});const view=report.steps.at(-1).view;if(await p.locator('dialog[open]').evaluate(d=>d.classList.contains('hand-candidate-dialog')))assert.ok(view.heading.y>=view.bounds.y&&view.heading.y+view.heading.height<=view.footer.y,'fixed candidate heading must stay inside actual modal');};
 try{
  await p.goto('http://127.0.0.1:5425/?harness=1&seed=group-natural-17');await waitScene(p,'title');await tap('title','action/title-start');await waitScene(p,'character-select');await tap('character-select','character/amo');await confirmHeroRoute(p,true);await waitScene(p,'shop');await settle();let s=await state();report.initial=s;
  await tap('shop','action/chapter');await p.getByRole('button',{name:'选择节目单',exact:true}).click();await p.getByRole('button',{name:'本章不接',exact:true}).click();s=await command(s,[{type:'ChooseProgram',programId:null}],'Real optional program decision');
  const offer=s.shop.toolOffers.find(o=>o.definitionId==='T06');assert.ok(offer&&offer.price<=s.gold);if(device.name!=='pc')await tap('shop','action/shelf-tools');await tap('shop','offer/'+offer.offerId);await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await state(),s);await tap('shop','offer/'+offer.offerId);await p.getByRole('button',{name:'确认购买',exact:true}).click();s=await command(s,[{type:'BuyOffer',offerId:offer.offerId}],'Real four-gold black-suit dye purchase, no assumed future hand');
  await tap('shop','action/start-stage');await waitScene(p,'game');s=await command(s,[{type:'LeaveShop'},{type:'EnterStage'}],'Real entry with natural opening hand');
  await openCandidates();await goal('group');assert.ok(await p.locator('.candidate-choice[data-type="pair"]').isVisible());assert.equal(await p.locator('[data-route-reference]').count(),0);await recordView('Existing complete group candidates, not fabricated partials');await p.locator('.candidate-choice[data-type="pair"]').click();assert.deepEqual(await state(),s);await p.getByRole('button',{name:'换为这组',exact:true}).click();const selected=await draft();assert.equal(selected.selected.length,2);assert.deepEqual(await state(),s);
  await openCandidates();await goal('straight');assert.ok((await reference().innerText()).includes('还缺 10'));assert.equal(await reference().locator('small').filter({hasText:'★'}).count(),0);const keep=await retainIds();assert.equal(keep.length,4);assert.deepEqual(await draft(),selected);assert.deepEqual(await state(),s);await recordView('Natural JQKA missing10; reference viewing preserves the current pair draft');await shot('straight-reference');
  if(device.name==='phone'){await p.setViewportSize({width:740,height:390});await p.waitForTimeout(250);assert.deepEqual(await state(),s);assert.deepEqual(await draft(),selected);await p.setViewportSize({width:device.width,height:device.height});await p.waitForTimeout(250);}
  await reference().getByRole('button',{name:'查公开牌组',exact:true}).click();await p.getByLabel('牌组范围',{exact:true}).selectOption('all');assert.ok((await p.locator('dialog[open]').innerText()).includes('不展示抽牌顺序'));await recordView('Existing public deck composition, no draw-order information');await close();assert.deepEqual(await state(),s);assert.deepEqual(await draft(),selected);
  await openCandidates();await goal('flush');assert.ok((await reference().innerText()).includes('还差 2'));await recordView('Natural three-diamond alternative, not a guaranteed replacement');await shot('flush-reference');await p.getByRole('button',{name:/^工具包/}).click();await p.getByRole('button',{name:/黑桃染/}).click();
  const targets=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)).filter(c=>c.suit!=='spades').slice(0,3).map(c=>c.id);for(const id of targets)await p.getByLabel(id,{exact:true}).check();await recordView('Owned tool uses current targets and real before/after confirmation');await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await state(),s);assert.deepEqual(await draft(),selected);
  await openCandidates();await goal('flush');await p.getByRole('button',{name:/^工具包/}).click();await p.getByRole('button',{name:/黑桃染/}).click();for(const id of targets)await p.getByLabel(id,{exact:true}).check();await p.getByRole('button',{name:'确认使用',exact:true}).click();s=await command(s,[{type:'UseConsumable',instanceId:s.consumables[0].instanceId,targetIds:targets}],'Real dye consumes once and keeps ranks/RNG; four spades still do not guarantee flush');
  await openCandidates();await goal('flush');assert.ok((await reference().innerText()).includes('还差 1'));assert.equal((await retainIds()).length,4);await recordView('Guidance recomputes from actual modified hand: four spades missing one');await shot('after-real-tool');await close();const committed=s;await p.reload();await waitScene(p,'title');assert.deepEqual(await state(),committed);await tap('title','action/title-continue');await waitScene(p,'game');await settle();assert.deepEqual(await state(),committed);s=await state();
  for(let i=0;i<2;i++){const before=s,ids=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)).sort((a,b)=>b.rank-a.rank||['spades','hearts','clubs','diamonds'].indexOf(a.suit)-['spades','hearts','clubs','diamonds'].indexOf(b.suit)).map(c=>c.id);await tap('game','action/sort-rank');s=await command(before,[{type:'ReorderHand',ids}],'Explicit repeated rank sorting');}
  await p.waitForFunction(()=>window.__harness.game.scene.getScene('game').aiButton.input.enabled);for(let i=0;i<2;i++)await tap('game','selection/switch-type');assert.deepEqual(await state(),s);const ai=await draft();await openCandidates();await goal('flush');assert.deepEqual(await draft(),ai);const retained=await retainIds();await reference().getByRole('button',{name:'回牌桌自己选牌',exact:true}).click();assert.deepEqual(await draft(),ai);assert.deepEqual(await state(),s);
  for(const id of ai.selected)await tap('game','card/'+id);const others=s.handOrder.filter(id=>!retained.includes(id)).slice(0,5);for(const id of others)await tap('game','card/'+id);const beforeDiscard=s;await tap('game','action/discard');s=await command(beforeDiscard,[{type:'DiscardHand',selectedIds:others}],'Player explicitly selects other public cards and discards once; no promised draw');await openCandidates();await goal('flush');await recordView('After real replacement: only current hand facts, no preset outcome');await shot('after-real-replacement');await close();report.final=s;report.status='PASS';completed.push(s);
 }catch(e){report.status='FAIL';report.error=String(e);await shot('FAIL');process.exitCode=1;}finally{await writeFile(dir+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({device:device.name,status:report.status,error:report.error,seq:report.final?.commandSeq}));await p.close();}
}}
finally{await browser.close();await new Promise(r=>server.httpServer.close(r));}
for(const final of completed.slice(1))assert.deepEqual(final,completed[0],'same public decisions persist identical PC/phone states');
