import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {tapUI,waitScene,tapMenuAction} from './ui.mjs';
const out=process.env.HERO_CLIMAX_OUTPUT??'/tmp/hero-climax-native';await mkdir(out,{recursive:true});
const server=await createServer({mode:'e2e',server:{host:'127.0.0.1',port:5444,strictPort:true},logLevel:'error'});await server.listen();
const {heroClimaxFixture,energySend}=await server.ssrLoadModule('/harness/fixtures/hero-climax.ts'),{makeCheckpoint,readCheckpoint}=await server.ssrLoadModule('/src/application/checkpoint.ts');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});
const specs=[{width:1366,height:768},{width:390,height:740},{width:320,height:740},{width:740,height:390},...['growth','fifth','failure'].map(kind=>({width:390,height:740,kind})),...['reduce','mid-reduce','fast','skip','exit','resize'].map(mode=>({width:390,height:740,mode}))];
const report={head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'Finite current-version native import/selection/play; full state equals canonical committed commands. Multiply/fifth public snapshots controlled; growth and failure snapshots produced by legal domain commands. Render-loop captures and WebAudio output only; not physical FPS, subjective hearing or user acceptance.',cases:[]};
try{for(const spec of specs){const kind=spec.kind??'multiply',mode=spec.mode??'normal',key=`${spec.width}-${kind}-${mode}`;if(process.env.HERO_CLIMAX_CASE&&!process.env.HERO_CLIMAX_CASE.split(',').includes(key))continue;const touch=spec.width<800,context=await browser.newContext({viewport:{width:spec.width,height:spec.height},hasTouch:touch,deviceScaleFactor:1,reducedMotion:mode==='reduce'?'reduce':'no-preference'}),p=await context.newPage();p.setDefaultTimeout(18000);const row={key,spec,errors:[]};report.cases.push(row);p.on('pageerror',e=>row.errors.push(String(e)));p.on('dialog',d=>d.accept());
 const state=()=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),hit=name=>tapUI(p,'game',name,touch),settle=()=>p.waitForFunction(()=>{const g=window.__harness.game,s=g.scene.getScene('game');return g.scene.isActive('intermission')||s.ready&&!s.presentation&&!s.playing&&s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container));});
 try{
  await p.addInitScript(()=>{window.__captureShapes=[];const create=AudioContext.prototype.createWaveShaper;AudioContext.prototype.createWaveShaper=function(...args){const node=create.apply(this,args);window.__captureShapes.push(node);return node;};});
  await p.goto('http://127.0.0.1:5444/?harness=1');await waitScene(p,'title');const f=heroClimaxFixture(kind),checkpoint=makeCheckpoint(f.state,[]);assert.ok(readCheckpoint(checkpoint).ok);row.before=f.state;
  await p.locator('.run-menu-toggle').click();const details=p.getByText('进度与存档',{exact:true}).locator('..');if(!await details.evaluate(e=>e.open))await details.locator('summary').click();const choose=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await choose).setFiles({name:'current-hero.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(checkpoint))});await waitScene(p,'game');await settle();assert.deepEqual(await state(),f.state);
  if(await p.locator('.detail-dialog[open]').count())await p.getByRole('button',{name:'关闭',exact:true}).click();if(mode==='fast'||mode==='mid-reduce'){await p.locator('.run-menu-toggle').click();await p.getByText('画面与声音',{exact:true}).click();if(mode==='fast')await p.getByLabel('演出速度').selectOption('4');await p.locator('.run-menu-toggle').click();}for(const id of f.selectedIds)await hit('card/'+id);if(f.assistIds.length)await hit('selection/assist-'+f.assistIds.join('+'));
  await p.waitForFunction(async()=>{const {AudioEngine}=await import('/src/audio/AudioEngine.ts');return AudioEngine.shared.scoreSamples.size===5;});
  const capture=mode==='normal'&&kind==='multiply'&&[1366,390].includes(spec.width);
  await p.evaluate(async capture=>{
   const {AudioEngine}=await import('/src/audio/AudioEngine.ts'),engine=AudioEngine.shared,ctx=engine.context;window.__heroFrames=[];window.__heroImages=[];window.__heroIds=[];window.__scoreHits=[];window.__captureActive=true;window.__mediaRequested=performance.getEntriesByType('resource').filter(r=>/audio\/p06|serenade/.test(r.name)).map(r=>r.name);
   const original=engine.scoreImpact.bind(engine);engine.scoreImpact=(...args)=>{window.__scoreHits.push({eventId:args[1],kind:args[2],tier:args[3],time:ctx.currentTime});return original(...args);};
   let lastImage=-1000;window.__harness.game.events.on('poststep',()=>{const g=window.__harness.game,s=g.scene.getScene('game'),stage=s.heroClimax?.group;if(!window.__captureActive||!stage?.active)return;const board=stage.list.find(x=>x.type==='Container'),hero=board?.list.find(x=>x.name==='hero/climax-portrait'),value=board?.list.find(x=>x.name==='hero/climax-value'),time=ctx.currentTime,id=stage.getData('eventId');if(!window.__heroIds.includes(id))window.__heroIds.push(id);
    window.__heroFrames.push({time,eventId:id,phase:stage.getData('phase'),x:hero?.x,y:hero?.y,scale:hero?.scaleX,boardX:board?.x,alpha:board?.alpha,value:value?.text,playing:s.playing,ready:s.ready});if(capture&&time-lastImage>=.1&&window.__heroImages.length<16){lastImage=time;window.__heroImages.push({time,phase:stage.getData('phase'),png:g.canvas.toDataURL('image/png')});}
   });
   if(capture){const dest=ctx.createMediaStreamDestination();window.__captureShapes[0].connect(dest);window.__soundChunks=[];window.__soundRecorder=new MediaRecorder(dest.stream,{mimeType:'audio/webm;codecs=opus'});window.__soundRecorder.ondataavailable=e=>window.__soundChunks.push(e.data);window.__soundRecorder.start();}
  },capture);
  const expected=energySend(f.state,f.assistIds.length?{type:'PlayAssistedHand',selectedIds:f.selectedIds,assistIds:f.assistIds}:{type:'PlayHand',selectedIds:f.selectedIds});row.expected=expected;await hit('action/play');
  if(kind==='failure'){
   await p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.scoreTotal.getData('eventPhase')==='award';});assert.deepEqual(await state(),expected);row.failureFrame=await p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game');return {stage:!!s.heroClimax,caption:s.view.root.list.find(x=>x.name==='joker/key-focus')?.getData('benefit')?.title};});assert.equal(row.failureFrame.stage,false);assert.match(row.failureFrame.caption,/本局结束/);await p.screenshot({path:out+'/'+key+'.png',scale:'css'});
  }else{
   await p.waitForFunction(()=>window.__harness.game.scene.getScene('game').heroClimax?.group.getData('phase')==='strike');assert.deepEqual(await state(),expected);
   row.impact=await p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game'),stage=s.heroClimax.group,board=stage.list.find(x=>x.type==='Container');return {eventId:stage.getData('eventId'),phase:stage.getData('phase'),ready:s.ready,playing:s.playing,hero:board.list.find(x=>x.name==='hero/climax-portrait').getBounds(),text:board.list.filter(x=>x.text!==undefined).map(x=>({name:x.name,text:x.text,bounds:x.getBounds()}))};});
   assert.equal(row.impact.eventId,expected.openingShow.eventId);assert.equal(row.impact.ready,false);assert.equal(row.impact.playing,true);assert.ok(row.impact.hero.height>=spec.height*.38);
   // Stable key facts remain inside the viewport, including narrow/short modes.
   for(const t of row.impact.text.filter(x=>['hero/climax-value','hero/climax-source-title','hero/climax-landing'].includes(x.name))){assert.ok(t.bounds.x>=-1&&t.bounds.x+t.bounds.width<=spec.width+1&&t.bounds.y>=0&&t.bounds.y+t.bounds.height<=spec.height,JSON.stringify(t));}
   await p.screenshot({path:out+'/'+key+'.png',scale:'css'});
   if(mode==='mid-reduce'){await p.locator('.run-menu-toggle').click();await p.getByLabel('减少动态').check();await p.locator('.run-menu-toggle').click();}if(mode==='skip')await tapMenuAction(p,'快进当前手',touch);
   if(mode==='exit'){await tapMenuAction(p,'保存并退出',touch);await waitScene(p,'character-select');}
   if(mode==='resize')await p.setViewportSize({width:740,height:390});
  }
  if(mode!=='exit')await settle();assert.deepEqual(await state(),expected);await p.waitForTimeout(320);assert.deepEqual(await state(),expected);
  if(capture){const images=await p.evaluate(()=>window.__heroImages);row.images=images.map(({time,phase},i)=>({time,phase,path:key+'-frame-'+String(i).padStart(2,'0')+'.png'}));for(let i=0;i<images.length;i++)await writeFile(out+'/'+row.images[i].path,Buffer.from(images[i].png.split(',')[1],'base64'));const bytes=await p.evaluate(()=>new Promise(resolve=>{window.__soundRecorder.onstop=async()=>resolve([...new Uint8Array(await new Blob(window.__soundChunks,{type:'audio/webm'}).arrayBuffer())]);window.__soundRecorder.stop();}));await writeFile(out+'/'+key+'-audio.webm',Buffer.from(bytes));row.audioBytes=bytes.length;assert.ok(bytes.length>1000);}
  row.frames=await p.evaluate(()=>window.__heroFrames);row.hits=await p.evaluate(()=>window.__scoreHits);const ids=await p.evaluate(()=>window.__heroIds);assert.equal(ids.length,kind==='failure'?0:1);
  if(kind!=='failure'){assert.ok(row.frames.length>1);const impact=row.frames.find(x=>x.phase==='strike');assert.ok(impact);const body=row.hits.find(x=>x.eventId===impact.eventId&&x.kind!=='flight'||kind==='fifth'&&x.kind==='award');assert.ok(body);assert.ok(Math.abs(body.time-impact.time)<.15,'real recorded sound aligns to the committed strike');if(mode==='normal')assert.ok(row.frames.some(x=>x.phase==='release'));if(mode==='reduce')assert.ok(row.frames.every(x=>x.scale===row.frames[0].scale&&x.boardX===0));}
  row.cleanup=await p.evaluate(async()=>{const {AudioEngine}=await import('/src/audio/AudioEngine.ts'),s=window.__harness.game.scene.getScene('game');return {stage:!!s.heroClimax,groups:s.view.root.active?s.view.root.list.filter(x=>x.getData?.('heroClimax')).length:0,voices:[...AudioEngine.shared.voices].filter(v=>v.scoreAccent).length,musicAvailable:AudioEngine.shared.musicAvailable,musicElement:!!AudioEngine.shared.musicElement,mediaRequests:window.__mediaRequested};});assert.equal(row.cleanup.stage,false);assert.equal(row.cleanup.groups,0);assert.equal(row.cleanup.voices,0);assert.equal(row.cleanup.musicAvailable,false);assert.equal(row.cleanup.musicElement,false);assert.deepEqual(row.cleanup.mediaRequests,[]);
  // Same current run's next saved hand keeps the old opening mark and cannot re-enter the full stage.
  if(spec.width===390&&kind==='multiply'&&mode==='normal'){
   let next=expected;await tapUI(p,'intermission','action/continue-stage',touch);await waitScene(p,'shop');next=energySend(next,{type:'OpenShop'});await p.waitForFunction(()=>window.__harness.game.scene.getScene('shop').ready);await tapUI(p,'shop','action/start-stage',touch);await waitScene(p,'game');await settle();next=energySend(energySend(next,{type:'LeaveShop'}),{type:'EnterStage'});assert.deepEqual(await state(),next);await hit('card/'+next.handOrder[0]);await hit('action/play');const paid=energySend(next,{type:'PlayHand',selectedIds:[next.handOrder[0]]});await settle();assert.deepEqual(await state(),paid);assert.equal(await p.evaluate(()=>window.__heroIds.length),1);assert.equal(paid.openingShow.rootId,expected.openingShow.rootId);row.repeat={before:next,after:paid,fullStageIds:await p.evaluate(()=>window.__heroIds)};
  }
  await p.evaluate(()=>window.__captureActive=false);row.after=await state();assert.equal(row.errors.length,0);row.status='PASS';
 }catch(error){row.failure=String(error);await p.screenshot({path:out+'/'+key+'-FAIL.png'});throw error;}finally{await context.close();}
}}
catch(error){report.status='FAIL';report.error=String(error);process.exitCode=1;}
finally{report.status??='PASS';await browser.close();await server.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,error:report.error,cases:report.cases.map(x=>({key:x.key,status:x.status,failure:x.failure}))}));}
