import assert from 'node:assert/strict';
import {createServer} from '/workspace/dachoupai/node_modules/vite/dist/node/index.js';
import {chromium} from '/workspace/dachoupai/node_modules/playwright/index.mjs';
import {waitScene,tapUI,confirmHeroRoute,buyOffer} from '/workspace/dachoupai/harness/ui.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
const root=process.env.NATIVE_ROOT??'/workspace/dachoupai',label=process.env.NATIVE_LABEL??'after',w=Number(process.env.NATIVE_WIDTH??1366),h=w===390?740:768,touch=w===390,out='/tmp/opening-120/'+label+'-'+w;await mkdir(out,{recursive:true});
const v=await createServer({root,mode:'e2e',server:{host:'127.0.0.1',port:5515,strictPort:true},logLevel:'error'});await v.listen();const {applyCommand}=await v.ssrLoadModule('/src/domain/run.ts');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--autoplay-policy=no-user-gesture-required']});const p=await browser.newPage({viewport:{width:w,height:h},hasTouch:touch,deviceScaleFactor:1});p.setDefaultTimeout(20000);p.on('dialog',d=>d.accept());const report={label,root,w,h,source:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),errors:[],steps:[],shots:[],scope:'One fixed seed, native title/hero/route/shop/card/play inputs; actual saved state against canonical command; software page frames and actual final WebAudio output. Not physical FPS, human hearing or subjective acceptance.'};p.on('pageerror',e=>report.errors.push(String(e)));
const frames=[],cdp=await p.context().newCDPSession(p);cdp.on('Page.screencastFrame',async e=>{frames.push({timestamp:e.metadata.timestamp,data:e.data});await cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId});});
const state=()=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),shot=async name=>{await p.screenshot({path:out+'/'+name+'.png',scale:'css'});report.shots.push(name);},settle=()=>p.waitForFunction(()=>{const g=window.__harness.game,s=g.registry.get('runController')?.state;if(!s)return false;if(s.phase==='stage-cleared'||s.phase==='run-lost')return g.scene.isActive('intermission');if(s.phase==='shop')return g.scene.getScene('shop').ready;const a=g.scene.getScene('game');return a.ready&&!a.presentation&&!a.playing&&a.cardViews.every(x=>!x.dealing&&!a.tweens.isTweening(x.container));});
async function exact(before,actions){const after=await state();let expected=before;for(let i=0;i<actions.length;i++){const seq=expected.commandSeq,receipt=after.receipts.find(r=>r.seq===seq+1)??after.receipts[i];const command={runId:expected.runId,commandId:receipt?.commandId??expected.runId+'/command/'+(seq+1),expectedSeq:seq,action:actions[i]};const r=applyCommand(expected,command);assert.ok(r.ok,JSON.stringify(r));expected=r.state;}assert.deepEqual(after,expected);report.steps.push({actions,before,after,canonical:true});}
try{
 await p.addInitScript(()=>{localStorage.setItem('dachoupai-audio-v2',JSON.stringify({version:2,music:.30,sfx:.80}));window.__audioChunks=[];const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(dest,...args){const result=connect.call(this,dest,...args);if(dest===this.context.destination&&!window.__audioRecorder){const capture=this.context.createMediaStreamDestination();connect.call(this,capture);window.__audioStarted=(performance.timeOrigin+performance.now())/1000;const rec=new MediaRecorder(capture.stream,{mimeType:'audio/webm;codecs=opus'});rec.ondataavailable=e=>window.__audioChunks.push(e.data);rec.start();window.__audioRecorder=rec;}return result;};});
 await cdp.send('Page.startScreencast',{format:'jpeg',quality:76,maxWidth:w,maxHeight:h,everyNthFrame:4});await p.goto('http://127.0.0.1:5515/?harness=1&seed=group-natural-17');await waitScene(p,'title');await p.waitForTimeout(180);await shot('title-entrance');await p.waitForTimeout(620);await shot('title-settled');await tapUI(p,'title','action/title-start',touch);await waitScene(p,'character-select');await p.waitForTimeout(label==='after'?330:50);await shot('ink-cover');await p.waitForTimeout(700);
 await tapUI(p,'character-select','character/erxiang',touch);await p.waitForTimeout(520);await shot('hero-selected');await tapUI(p,'character-select','action/confirm-character',touch);await shot('route-choice');await tapUI(p,'character-select','route/group',touch);await shot('route-selected');await tapUI(p,'character-select','action/confirm-character',touch);await waitScene(p,'shop');await settle();await p.waitForTimeout(360);await shot('shop-reveal');await p.waitForTimeout(680);report.initial=await state();
 if(report.initial.program&&!report.initial.program.choiceMade){const before=await state();await tapUI(p,'shop','action/chapter',touch);await p.getByRole('button',{name:'选择节目单',exact:true}).click();await p.getByRole('button',{name:'本章不接',exact:true}).click();await settle();await exact(before,[{type:'ChooseProgram',programId:null}]);}
 const shop=await state(),offer=shop.shop.offers.find(o=>o.definitionId==='mantangcai'&&o.price<=shop.gold);if(offer){await buyOffer(p,offer.offerId,touch);await settle();await exact(shop,[{type:'BuyOffer',offerId:offer.offerId}]);}

 if(label==='after'){
  const beforeTool=await state(),offer=beforeTool.shop.toolOffers.find(o=>o.definitionId==='T10'&&!o.consumed);assert.ok(offer&&offer.price<=beforeTool.gold);
  await shot('first-shop-step');await tapUI(p,'shop','first-guide/shop-open',touch);assert.ok((await p.locator('dialog[open]').innerText()).includes('倍率纸'));await p.getByRole('button',{name:'购买 · 2 金',exact:true}).click();await settle();await exact(beforeTool,[{type:'BuyOffer',offerId:offer.offerId}]);await p.getByRole('button',{name:'立即使用',exact:true}).click();const beforeUse=await state(),item=beforeUse.consumables.find(c=>c.definitionId==='T10');assert.ok(item);for(const id of ['hearts-2','spades-2'])await p.locator('input[value="'+id+'"]').check();await shot('first-tool-preview');await p.getByRole('button',{name:'确认使用',exact:true}).click();await p.locator('.tool-saved-result').waitFor();await exact(beforeUse,[{type:'UseConsumable',instanceId:item.instanceId,targetIds:['spades-2','hearts-2']}]);await shot('first-tool-saved');await p.getByRole('button',{name:'回到经营',exact:true}).click();await settle();
 }
 const beforeStage=await state();await tapUI(p,'shop','action/start-stage',touch);await waitScene(p,'game');await settle();if(await p.getByRole('button',{name:'开始出牌',exact:true}).isVisible())await p.getByRole('button',{name:'开始出牌',exact:true}).click();await exact(beforeStage,[{type:'LeaveShop'},{type:'EnterStage'}]);
 const before=await state(),selected=['hearts-2','spades-2','clubs-14','diamonds-14'];for(const id of selected){assert.ok(before.handOrder.includes(id));await tapUI(p,'game','card/'+id,touch);}
 await p.evaluate(async()=>{const {AudioEngine}=await import('/src/audio/AudioEngine.ts');await AudioEngine.shared.scoreSampleTask;window.__prefs={music:AudioEngine.shared.getVolume('music'),sfx:AudioEngine.shared.getVolume('sfx'),stored:localStorage.getItem('dachoupai-audio-v2')};window.__heroFrames=[];window.__harness.game.events.on('poststep',()=>{const s=window.__harness.game.scene.getScene('game'),stage=s.heroClimax?.group;if(stage?.active){const board=stage.list.find(x=>x.type==='Container'),hero=board.list.find(x=>x.name==='hero/climax-portrait');window.__heroFrames.push({time:performance.now(),phase:stage.getData('phase'),event:stage.getData('eventId'),heroX:hero.x,heroY:hero.y,scale:hero.scaleX,boardX:board.x});}});});
 if(label==='after'){await tapUI(p,'game','hero/erxiang-handoff',touch);await p.getByRole('button',{name:'A♣ · 11点改加倍率',exact:true}).click();}
 await shot('selected');await tapUI(p,'game','action/play',touch);await p.waitForFunction(()=>window.__harness.game.scene.getScene('game').heroClimax?.group.getData('phase')==='strike');await p.waitForTimeout(85);await shot('hero-strike');await exact(before,[{type:'PlayHand',selectedIds:selected,...(label==='after'?{erxiangTargetId:'clubs-14'}:{})}]);await settle();await p.waitForTimeout(450);await shot('settled');report.final=await state();report.frames=await p.evaluate(()=>window.__heroFrames);report.preferences=await p.evaluate(()=>window.__prefs);assert.equal(report.preferences.music,.30);assert.equal(report.preferences.sfx,.80);assert.ok(report.frames.some(f=>f.phase==='strike'));assert.equal(new Set(report.frames.map(f=>f.event)).size,1);assert.deepEqual(report.errors,[]);
 report.audioStart=await p.evaluate(()=>window.__audioStarted);const bytes=await p.evaluate(()=>new Promise(resolve=>{window.__audioRecorder.onstop=async()=>resolve([...new Uint8Array(await new Blob(window.__audioChunks,{type:'audio/webm'}).arrayBuffer())]);window.__audioRecorder.stop();}));await writeFile(out+'/actual-output.webm',Buffer.from(bytes));assert.ok(bytes.length>2000);report.audioBytes=bytes.length;report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);report.stack=e.stack;report.savedAtFailure=await state().catch(()=>null);report.dialogs=await p.locator('dialog[open]').allTextContents();await shot('FAIL').catch(()=>{});process.exitCode=1;}finally{
 await cdp.send('Page.stopScreencast');report.frameCount=frames.length;if(frames.length){report.start=frames[0].timestamp;report.end=frames.at(-1).timestamp;for(let i=0;i<frames.length;i++)await writeFile(out+'/f'+String(i).padStart(4,'0')+'.jpg',Buffer.from(frames[i].data,'base64'));await writeFile(out+'/frames.txt',frames.map((f,i)=>`file '${out}/f${String(i).padStart(4,'0')}.jpg'\nduration ${Math.max(.001,(frames[i+1]?.timestamp??f.timestamp+.08)-f.timestamp)}`).join('\n')+'\n');}
 await writeFile(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,error:report.error,dialogs:report.dialogs,source:report.source,score:report.final?.lastTrace?.finalScore,frames:frames.length,duration:report.end-report.start,audioStart:report.audioStart-report.start}));await browser.close();await v.close();
}
