/** Approved a11 replacement; legal owned-card fixture and deliberately warmed old browser URLs. */
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createServer,build,preview} from 'vite';
import {chromium} from 'playwright';
import {tapUI,waitScene} from './ui.mjs';
const dir='shots/p08-a11-v2',base='/a11-review/',manifest=JSON.parse(await readFile('public/assets/handdrawn-p08/manifest.json')),asset=manifest.assets.find(a=>a.id==='a11'),output=purpose=>asset.outputs.find(o=>o.purpose===purpose),url=purpose=>base+'assets/handdrawn-p08/'+output(purpose).path,oldUrls=['thumbnail','detail'].map(p=>base+'assets/handdrawn-p08/cards/a11.'+p+'.webp'),oldBytes=Object.fromEntries(['thumbnail','detail'].map((p,i)=>[oldUrls[i],execFileSync('git',['show','7d37d23347ddbfee344a00355de9741b34c67e76:public/assets/handdrawn-p08/cards/a11.'+p+'.webp'])]));
await mkdir(dir,{recursive:true});const ssr=await createServer({server:{middlewareMode:true},optimizeDeps:{noDiscovery:true,include:[]},logLevel:'error'});let fixture;
try{const {createRun,applyCommand}=await ssr.ssrLoadModule('/src/domain/run.ts'),{r2CreateJoker}=await ssr.ssrLoadModule('/src/domain/r2Run.ts'),{makeCheckpoint,readCheckpoint}=await ssr.ssrLoadModule('/src/application/checkpoint.ts');let state=createRun({seed:'p08-a11-v2',runId:'fixture/p08-a11-v2',characterId:'amo',rulesVersion:'r2',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});state.jokers=[r2CreateJoker('a11','reviewed/a11',0)];for(const type of ['LeaveShop','EnterStage']){const r=applyCommand(state,{runId:state.runId,commandId:type,expectedSeq:state.commandSeq,action:{type}});assert.ok(r.ok);state=r.state;}const cp=makeCheckpoint(state,[]);assert.ok(readCheckpoint(cp).ok);fixture=JSON.stringify(cp);}finally{await ssr.close();}
const fingerprint=createHash('sha256');for(const p of execFileSync('git',['ls-files','--cached','--others','--exclude-standard','src'],{encoding:'utf8'}).trim().split('\n').sort()){fingerprint.update(p+'\0');fingerprint.update(await readFile(p));fingerprint.update('\0');}
await build({mode:'e2e',base,build:{outDir:dir+'/build'},logLevel:'error'});let oldServed=0;
const server=await preview({base,plugins:[{name:'private-old-a11-cache-fixture',configurePreviewServer(s){s.middlewares.use((req,res,next)=>{const bytes=oldBytes[req.url];if(!bytes)return next();oldServed++;res.setHeader('content-type','image/webp');res.setHeader('cache-control','public,max-age=31536000,immutable');res.end(bytes);});}}],build:{outDir:dir+'/build'},preview:{host:'127.0.0.1',port:5297,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']}),context=await browser.newContext({viewport:{width:390,height:740},deviceScaleFactor:1,hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),requests=[],errors=[];
page.on('request',r=>{if(r.url().includes('handdrawn-p08'))requests.push(new URL(r.url()).pathname);});page.on('pageerror',e=>errors.push(String(e)));page.on('dialog',d=>d.accept());
const previous=existsSync(dir+'/report.json')?JSON.parse(await readFile(dir+'/report.json')):null;
const report={taskId:'P08',status:'IN_PROGRESS',sourceFingerprint:fingerprint.digest('hex'),assetCommit:asset.sourceCommit,runtimeManifestSHA256:createHash('sha256').update(await readFile('public/assets/handdrawn-p08/manifest.json')).digest('hex'),build:JSON.parse(await readFile(dir+'/build/build-info.json')),viewport:{width:390,height:740},DPR:1,safeInset:{top:0,bottom:0,left:0,right:0},renderer:'Chromium software Canvas;GPU/software rasterizer disabled',base,fixture:'Validator-approved imported owned a11 entry; no natural purchase. Native tap/detail/close/reopen/reload. Old canonical a11 browser URLs deliberately warmed with immutable cached v1 bytes; new content paths must render v2.',requests,errors,checks:[]};
function expected(actual,purpose){for(const k of ['bytes','sha256','width','height'])assert.equal(actual[k],output(purpose)[k]);}
async function warm(){return page.evaluate(async paths=>{const out=[];for(const path of paths){const b=await(await fetch(path)).arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',b);out.push({path,bytes:b.byteLength,sha256:[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('')});}return out;},oldUrls);}
async function foreground(){return page.locator('.detail-dialog[open] img').evaluate(async i=>{const b=await(await fetch(i.src)).arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',b),r=i.getBoundingClientRect();return {width:i.naturalWidth,height:i.naturalHeight,bytes:b.byteLength,sha256:[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join(''),fit:getComputedStyle(i).objectFit,rect:{width:r.width,height:r.height}};});}
async function openHD(){await tapUI(page,'game','joker/reviewed/a11',true);await page.waitForFunction(()=>document.querySelector('.detail-dialog[open] img')?.naturalWidth===615);}
async function close(){await page.getByRole('button',{name:'关闭',exact:true}).tap();}
async function thumbnail(){return page.evaluate(async path=>{const s=window.__harness.game.scene.getScene('game'),image=s.textures.get('p08-joker-a11').getSourceImage(),b=await(await fetch(path)).arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',b),decoded=await createImageBitmap(new Blob([b],{type:'image/webp'}));const pixels=async img=>{const c=document.createElement('canvas');c.width=128;c.height=160;const x=c.getContext('2d');x.drawImage(img,0,0);const d=await crypto.subtle.digest('SHA-256',x.getImageData(0,0,128,160).data);return [...new Uint8Array(d)].map(n=>n.toString(16).padStart(2,'0')).join('');};return {width:image.naturalWidth,height:image.naturalHeight,bytes:b.byteLength,sha256:[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join(''),actualTexturePixels:await pixels(image),expectedDecodedPixels:await pixels(decoded)};},url('thumbnail'));}
try{
 await page.goto('http://127.0.0.1:5297'+base+'?harness=1');await waitScene(page,'title');report.oldCache=await warm();assert.equal(oldServed,2);assert.deepEqual(await warm(),report.oldCache);assert.equal(oldServed,2,'second read uses immutable old browser cache, not a fresh server response');for(const row of report.oldCache){assert.equal(row.sha256,createHash('sha256').update(oldBytes[row.path]).digest('hex'));assert.notEqual(row.sha256,output(row.path.includes('.detail.')?'detail':'thumbnail').sha256);}report.checks.push('both old v1 canonical URLs genuinely warmed and reused from HTTP cache; hashes remain v1');
 await page.locator('.run-menu-toggle').tap();const sec=page.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').tap();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入本局',exact:true}).tap();await(await chooser).setFiles({name:'a11-v2-fixture.json',mimeType:'application/json',buffer:Buffer.from(fixture)});await waitScene(page,'game');await page.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.ready&&s.textures.exists('p08-joker-a11')&&s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container));});assert.equal(await page.evaluate(()=>window.__harness.game.renderer.gl?'WebGL':'Canvas'),'Canvas');assert.ok(!requests.includes(url('detail')),'new HD not requested before opening');report.thumbnail=await thumbnail();expected(report.thumbnail,'thumbnail');assert.equal(report.thumbnail.actualTexturePixels,report.thumbnail.expectedDecodedPixels,'actual installed texture is exactly the newly decoded v2 image');const before=await page.evaluate(()=>window.__harness.game.registry.get('runController').state);
 await openHD();report.detail=await foreground();expected(report.detail,'detail');assert.equal(report.detail.fit,'contain');assert.ok((await page.locator('.detail-dialog[open]').textContent()).includes('返个场'));if(!existsSync(dir+'/390-a11-v2-detail.png')){await page.screenshot({path:dir+'/390-a11-v2-detail.png'});report.imageBuild=report.build;}else{assert.equal(previous.runtimeManifestSHA256,report.runtimeManifestSHA256,'retained screenshot has the same exact runtime inputs');report.imageSourceFingerprint=previous.imageSourceFingerprint??previous.sourceFingerprint;report.imageBuild=previous.imageBuild??previous.build;}report.imageSHA256=createHash('sha256').update(await readFile(dir+'/390-a11-v2-detail.png')).digest('hex');await close();const count=requests.filter(p=>p===url('detail')).length;await openHD();expected(await foreground(),'detail');assert.equal(requests.filter(p=>p===url('detail')).length,count,'new HD decoded cache reused');await close();assert.deepEqual(await page.evaluate(()=>window.__harness.game.registry.get('runController').state),before);report.checks.push('actual v2 installed texture pixels/new thumb+HD HTTP SHA/BASE_URL/on-demand/contain/native reopen cache/full run-RNG immutable despite warm v1');
 await page.reload();await waitScene(page,'title');await tapUI(page,'title','action/title-continue',true);await waitScene(page,'game');await page.waitForFunction(()=>window.__harness.game.scene.getScene('game').ready&&window.__harness.game.scene.getScene('game').textures.exists('p08-joker-a11'));expected(await thumbnail(),'thumbnail');await openHD();expected(await foreground(),'detail');await close();assert.deepEqual(await page.evaluate(()=>window.__harness.game.registry.get('runController').state),before);report.checks.push('reload with persisted run and browser caches still displays exact v2 thumb/detail; no run mutation');assert.deepEqual(errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);process.exitCode=1;console.error(e);}finally{await browser.close();await server.httpServer.close();await writeFile(dir+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,error:report.error,checks:report.checks}));}
