/** Bounded native-input AI selection, saved-profile and cancellation acceptance. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {build,createServer,preview} from 'vite';
import {chromium} from 'playwright';
import {point,waitScene} from './ui.mjs';
import {snapshotSource} from '../scripts/check-runner.mjs';

const dir=process.env.AI_CUT_DIR||'shots/p08-ai-cut/final',port=5336;
await mkdir(dir,{recursive:true});
const frozen=snapshotSource(process.cwd()),source=frozen.head;
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const legacy=JSON.parse(await readFile('tests/fixtures/r2-v10-amo-checkpoints.json','utf8'));
const fixtures={v10:legacy.before};let applyCommand,inputFor,aiKey;
const ssr=await createServer({server:{middlewareMode:true},optimizeDeps:{noDiscovery:true,include:[]},logLevel:'error'});
try{
 const domain=await ssr.ssrLoadModule('/src/domain/run.ts'),rules=await ssr.ssrLoadModule('/src/domain/r2Run.ts'),cp=await ssr.ssrLoadModule('/src/application/checkpoint.ts'),schema=await ssr.ssrLoadModule('/src/content/r2Schema.ts'),ai=await ssr.ssrLoadModule('/src/game/AiHandCandidates.ts');
 applyCommand=domain.applyCommand;aiKey=ai.aiHandKey;
 inputFor=s=>{const st=s.stage,hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)),c=rules.r2ScoreContext(s,hand,[]);return{hand,jokers:s.jokers,definitions:schema.R2_JOKERS,handRules:c.handRules,disabledIds:st.disabledIds,ordinaryPointsSuppressedIds:[],boss:c.boss,stageIndex:st.index,sealedJokerIds:c.sealedJokerIds,challengeDisabledJokerId:c.challengeDisabledJokerId,resources:{gold:s.gold,handsLeft:st.handsLeft,playIndex:st.playIndex,discardsUsed:st.discardsUsed,stageHeat:st.heat,target:st.targetHeat},contentVersion:s.contentVersion,score:{characterId:c.characterId,amoScoreTiming:c.amoScoreTiming,jokerSlots:c.jokerSlots,handLevels:s.handLevels,previousHandType:st.previousHandType,previousHandScore:c.previousHandScore,wager:st.wagerSelected}};};
 assert.ok(cp.readCheckpoint(fixtures.v10).ok,'actual unchanged legacy fixture accepted');
 let s=domain.createRun({runId:'fixture/ai-cut/v11',seed:'ai-cut/v11',characterId:'amo',rulesVersion:'r2',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});
 s.jokers=['c04','a03','a06'].map(id=>rules.r2CreateJoker(id,'fixture/'+id,0));
 for(const type of ['LeaveShop','EnterStage']){const r=applyCommand(s,{runId:s.runId,commandId:'fixture/'+type,expectedSeq:s.commandSeq,action:{type}});assert.ok(r.ok);s=r.state;}
 s.handOrder=['spades-14','hearts-14','hearts-12','hearts-11','hearts-10','spades-9','clubs-8','hearts-3','diamonds-2'];
 s.drawPile=s.deckInstances.filter(c=>!s.handOrder.includes(c.id)).map(c=>c.id);s.stage.handLimit=9;s.stage.initialHandLimit=9;s.stage.disabledIds=[];
 fixtures.v11=cp.makeCheckpoint(s,[]);assert.ok(cp.readCheckpoint(fixtures.v11).ok);
 // Same controlled hand-limit route as two-row-hand.mjs; no acquisition claim.
 let fourteen=domain.createRun({runId:'two-row-14',seed:'two-row-14',characterId:'amo',rulesVersion:'r2'});const journal=[];
 for(const type of ['LeaveShop','EnterStage']){const command={runId:fourteen.runId,commandId:type,expectedSeq:fourteen.commandSeq,action:{type}},r=applyCommand(fourteen,command);assert.ok(r.ok);fourteen=r.state;journal.push(command);}
 fourteen.stage.handLimit=14;fourteen.stage.initialHandLimit=14;while(fourteen.handOrder.length<14)fourteen.handOrder.push(fourteen.drawPile.pop());
 fixtures.fourteen=cp.makeCheckpoint(fourteen,journal);assert.ok(cp.readCheckpoint(fixtures.fourteen).ok);
}finally{await ssr.close();}
await build({mode:'e2e',build:{outDir:dir+'/build'},logLevel:'error'});
const server=await preview({build:{outDir:dir+'/build'},preview:{port,host:'127.0.0.1',strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});
const specs=[{name:'v11-390',fixture:'v11',width:390,height:740,top:0,bottom:0},{name:'v10-390',fixture:'v10',width:390,height:740,top:0,bottom:0},{name:'v11-320',fixture:'v11',width:320,height:568,top:0,bottom:0},{name:'v11-short-safe34',fixture:'v11',width:844,height:300,top:12,bottom:34},{name:'fourteen-slices-and-actions',fixture:'fourteen',width:390,height:740,top:0,bottom:0,diagnostic:true}];
const report={taskId:'P08',testedCommit:source,build:JSON.parse(await readFile(dir+'/build/build-info.json','utf8')),browser:browser.version(),renderer:'Chromium software Canvas',DPR:1,scope:'Current UI native touch, actual frozen v10 identity,9/14 soft-slice observations, cancellation. No original photo, GPU/FPS/video/device claim.',fixtures:{v10:'Unchanged tests/fixtures/r2-v10-amo-checkpoints.json.before, eight cards',v11:'Validator-approved curated nine-card visible hand with three modifiers',fourteen:'Existing two-row-hand controlled hand-limit route,14 cards; not natural acquisition'},runs:specs.map(profile=>({profile,status:'NOT_RUN',checks:[]})),screenshots:[],sourceFreeze:{before:frozen}};
const intersects=(a,b)=>a.x<b.x+b.width-1e-6&&b.x<a.x+a.width-1e-6&&a.y<b.y+b.height-1e-6&&b.y<a.y+a.height-1e-6;
const contained=(a,b)=>a.x>=b.x-.1&&a.y>=b.y-.1&&a.x+a.width<=b.x+b.width+.1&&a.y+a.height<=b.y+b.height+.1;
function installProbe(){
 const originalSet=window.setTimeout.bind(window),originalClear=window.clearTimeout.bind(window),rows=[],handles=new Map(),byGeneration=new Map();
 const scene=()=>window.__harness?.game.scene.getScene('game'),now=()=>performance.now();
 const probe=window.__aiProbe={rows,delayMs:0,deliverCleared:false,activeRequest:undefined,patched:false};
 const patch=()=>{const cache=scene()?.aiCandidates;if(!cache)return;const proto=Object.getPrototypeOf(cache),original=proto.update;if(original.__observed){probe.patched=true;return;}function observed(...args){const prior=probe.activeRequest;probe.activeRequest={at:now(),count:args[0].hand.length};try{return original.apply(this,args);}finally{probe.activeRequest=prior;}}observed.__observed=true;proto.update=observed;probe.patched=true;};
 const watch=()=>{patch();if(!probe.patched)requestAnimationFrame(watch);};requestAnimationFrame(watch);
 window.setTimeout=function(fn,delay,...args){
  if(typeof fn!=='function'||!/ordered\s*:/.test(Function.prototype.toString.call(fn))||!Function.prototype.toString.call(fn).includes('examined'))return originalSet(fn,delay,...args);
  const s=scene(),cache=s?.aiCandidates,generation=cache?.generation;let row=byGeneration.get(generation);
  if(!row){row={generation,handCount:s?.run?.handOrder.length,started:probe.activeRequest?.at??now(),clockOrigin:probe.activeRequest?'cache.update entry':'first scheduled timer',slices:0,maxSliceMs:0,totalSliceMs:0,cancelledTimers:0,staleCallbacks:0,staleApplied:0,busyUsefulCallbacks:0,readyMs:null};rows.push(row);byGeneration.set(generation,row);}
  let id;id=originalSet(()=>{handles.delete(id);const before=scene()?.aiCandidates.result,stale=scene()?.aiCandidates.generation!==generation,busy=!!scene()?.playing||!!scene()?.presentation,t=now();try{return fn(...args);}finally{const elapsed=now()-t;if(stale){row.staleCallbacks++;if(scene()?.aiCandidates.result!==before)row.staleApplied++;}else{row.slices++;row.maxSliceMs=Math.max(row.maxSliceMs,elapsed);row.totalSliceMs+=elapsed;if(busy)row.busyUsefulCallbacks++;}if(scene()?.aiCandidates.generation===generation&&scene()?.aiCandidates.result?.status==='ready')row.readyMs=now()-row.started;}},Math.max(Number(delay)||0,probe.delayMs));handles.set(id,row);return id;
 };
 window.clearTimeout=function(id){const row=handles.get(id);if(row){row.cancelledTimers++;handles.delete(id);if(probe.deliverCleared)return;}return originalClear(id);};
}
async function run(out){
 const spec=out.profile,context=await browser.newContext({viewport:{width:spec.width,height:spec.height},deviceScaleFactor:1,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage();out.status='RUNNING';out.errors=[];
 p.on('pageerror',e=>out.errors.push(String(e)));p.on('dialog',d=>d.accept());await p.addInitScript(installProbe);
 await p.addInitScript(({top,bottom})=>document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.setProperty('--safe-top',top+'px');document.documentElement.style.setProperty('--safe-bottom',bottom+'px');}),spec);
 const saved=()=>p.evaluate(()=>{const c=window.__harness.game.registry.get('runController');return{state:c.state,journal:c.journal,export:c.exportJSON()};}),selected=()=>p.evaluate(()=>[...window.__harness.game.scene.getScene('game').selectedIds]);
 const settled=()=>p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.ready&&!s.playing&&!s.presentation&&s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container));});
 const ready=async()=>{await settled();const current=(await saved()).state,key=aiKey(inputFor(current));await p.waitForFunction(key=>{const s=window.__harness.game.scene.getScene('game');return s.ready&&s.aiCandidates.result?.status==='ready'&&s.aiCandidates.result.key===key&&s.aiButton.input?.enabled;},key);};
 const hit=async name=>{await p.waitForFunction(name=>{const s=window.__harness.game.scene.getScene('game'),find=list=>{for(const o of list){if(o.name===name)return o;if(o.list){const f=find(o.list);if(f)return f;}}};return !!find(s.children.list)?.input?.enabled;},name);const q=await point(p,'game',name);assert.ok(q.enabled);await p.touchscreen.tap(q.x,q.y);};
 const observe=()=>p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game'),g=s.game,walk=list=>list.flatMap(o=>[o,...(o.list?walk(o.list):[])]),all=walk(s.children.list),r=g.canvas.getBoundingClientRect(),rect=b=>({x:b.x,y:b.y,width:b.width,height:b.height}),css=o=>{const b=o.getBounds(),a=s.cameras.main.matrix.transformPoint(b.x,b.y),z=s.cameras.main.matrix.transformPoint(b.right,b.bottom);return{x:r.left+a.x*r.width/g.scale.width,y:r.top+a.y*r.height/g.scale.height,width:(z.x-a.x)*r.width/g.scale.width,height:(z.y-a.y)*r.height/g.scale.height};};return{renderer:g.renderer.type,layout:s.view.layout,selected:[...s.selectedIds],type:s.selectionPreview()?.type,previewTotal:{text:s.scoreTotal.text,fullText:s.scoreTotal.getData('fullText'),visible:s.scoreTotal.visible},controls:['action/sort-rank','action/sort-suit','selection/switch-type','selection/hand-rules','action/tool-inventory','action/discard','action/play'].map(name=>{const o=all.find(o=>o.name===name),label=o.getData('label');return{name,enabled:!!o.input?.enabled,bounds:rect(o.getBounds()),CSS:css(o),label:{text:label.text,bounds:rect(label.getBounds()),font:parseFloat(label.style.fontSize)}};}),cards:s.cardViews.map(v=>({id:v.card.id,visible:v.container.visible,hit:rect(v.hit.getBounds()),bounds:rect(v.container.getBounds())})),toolbar:[...document.querySelectorAll('.run-menu-toggle,.run-fullscreen-toggle')].filter(e=>!e.hidden).map(e=>rect(e.getBoundingClientRect())),status:rect(s.statusText.getBounds())};});
 const noForecast=o=>{assert.ok(!o.previewTotal.visible);assert.ok(['','—'].includes(o.previewTotal.text.trim()));assert.ok(!o.previewTotal.fullText);};
 const geometry=o=>{assert.equal(o.renderer,1);const viewport={x:0,y:spec.top,width:spec.width,height:spec.height-spec.top-spec.bottom};for(const c of o.controls){assert.ok(c.CSS.width>=44-.01&&c.CSS.height>=44-.01);assert.ok(contained(c.CSS,viewport));assert.ok(contained(c.label.bounds,c.bounds));assert.ok(c.label.font>=14);for(const h of o.cards.filter(c=>c.visible))assert.ok(!intersects(c.bounds,h.hit));for(const t of o.toolbar)assert.ok(!intersects(c.CSS,t));}for(let i=0;i<o.controls.length;i++)for(let j=i+1;j<o.controls.length;j++)assert.ok(!intersects(o.controls[i].CSS,o.controls[j].CSS));assert.ok(contained(o.status,viewport));};
 async function importFixture(cp){await p.locator('.run-menu-toggle').tap();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').tap();const chooser=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).tap();await(await chooser).setFiles({name:'ai-cut-public-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});await waitScene(p,'game');await settled();assert.deepEqual((await saved()).state,cp.state);}
 async function sort(mode){const before=await saved(),suits=['spades','hearts','clubs','diamonds'],cards=before.state.handOrder.map(id=>before.state.deckInstances.find(c=>c.id===id));cards.sort((a,b)=>mode==='rank'?b.rank-a.rank||suits.indexOf(a.suit)-suits.indexOf(b.suit):suits.indexOf(a.suit)-suits.indexOf(b.suit)||b.rank-a.rank);await hit('action/sort-'+mode);await p.waitForFunction(seq=>window.__harness.game.registry.get('runController').state.commandSeq===seq+1,before.state.commandSeq);const after=await saved(),command={runId:before.state.runId,commandId:after.state.receipts.at(-1).commandId,expectedSeq:before.state.commandSeq,action:{type:'ReorderHand',ids:cards.map(c=>c.id)}},expected=applyCommand(before.state,command);assert.ok(expected.ok);assert.deepEqual(after.state,expected.state);assert.deepEqual(after.state.rng,before.state.rng);assert.deepEqual(await selected(),[]);out.checks.push({name:mode+' sort returns cards, authoritative full state/RNG',status:'PASS'});return after;}
 async function cancel(name){const before=await saved(),selection=await selected(),q=await point(p,'game',name),cdp=await context.newCDPSession(p);assert.ok(q.enabled);try{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:q.x,y:q.y,id:0,radiusX:1,radiusY:1,force:1}]});await p.waitForTimeout(420);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});}finally{await cdp.detach();}assert.deepEqual(await saved(),before);assert.deepEqual(await selected(),selection);assert.equal(await p.evaluate(()=>!!window.__harness.game.scene.getScene('game').view.pressed),false);out.checks.push({name:name+' held420ms native cancellation',status:'PASS'});}
 try{
  await p.goto('http://127.0.0.1:'+port+'/?harness=1');await waitScene(p,'title');await p.waitForFunction(()=>window.__aiProbe.patched);await importFixture(fixtures[spec.fixture]);
  if(!spec.diagnostic){
   await ready();const before=await saved(),rest=await observe();geometry(rest);noForecast(rest);assert.equal(rest.layout.visibleCardCount,spec.fixture==='v10'?8:9);assert.ok(rest.cards.every(c=>c.visible));const seats=rest.layout.cards;
   const sequence=spec.fixture==='v10'?['pair','high-card','pair']:['straight','flush','pair','high-card','straight'];let undoTarget=[];out.picks=[];
   for(const type of sequence){undoTarget=await selected();await ready();await hit('selection/switch-type');const o=await observe();assert.equal(o.type,type);noForecast(o);geometry(o);assert.deepEqual(o.layout.cards,seats);assert.deepEqual(await saved(),before);out.picks.push(type);}
   await hit('selection/facts');await p.getByRole('dialog',{name:'本轮可成牌型',exact:true}).waitFor();const undo=p.getByRole('button',{name:'撤销换组',exact:true});await undo.waitFor();assert.ok(await undo.isEnabled());await undo.tap();await p.waitForFunction(()=>!document.querySelector('.detail-dialog[open]'));assert.deepEqual(await selected(),undoTarget);assert.deepEqual(await saved(),before);assert.deepEqual((await observe()).layout.cards,seats);out.checks.push({name:'AI cycle, undo and complete state/journal/export/RNG readonly',status:'PASS',before:hash(before),after:hash(await saved())});
   await p.waitForTimeout(360);await hit('selection/hand-rules');const rules=p.getByRole('dialog',{name:'牌型规则',exact:true});await rules.waitFor();assert.match(await rules.innerText(),/成牌优先，高牌仅兜底/);assert.match(await rules.innerText(),/随机效果按保底比较/);await p.getByRole('button',{name:'关闭',exact:true}).tap();await p.waitForTimeout(360);assert.deepEqual(await saved(),before);
   await hit('action/tool-inventory');await p.getByRole('dialog',{name:'工具包',exact:true}).waitFor();await p.getByRole('button',{name:'关闭',exact:true}).tap();await p.waitForTimeout(360);assert.deepEqual(await saved(),before);assert.deepEqual(await selected(),undoTarget);
   for(const name of ['selection/switch-type','action/sort-rank','action/discard','action/play'])await cancel(name);
   for(const id of await selected())await hit('card/'+id);
   if(spec.fixture==='v11')for(const id of before.state.handOrder){await hit('card/'+id);assert.deepEqual(await selected(),[id]);await hit('card/'+id);assert.deepEqual(await selected(),[]);assert.deepEqual(await saved(),before);}
   await ready();await hit('selection/switch-type');await sort('rank');await ready();assert.deepEqual((await observe()).layout.cards,seats);await hit('selection/switch-type');await sort('suit');await ready();assert.deepEqual((await observe()).layout.cards,seats);
   const postSort=await saved();await hit('selection/switch-type');assert.equal((await observe()).type,sequence[0]);assert.deepEqual(await saved(),postSort);geometry(await observe());
   if(spec.fixture==='v11'){const file=spec.name+'.png';await p.screenshot({path:dir+'/'+file,fullPage:true,scale:'css'});report.screenshots.push(file);}
   out.geometry=await observe();out.savedIdentity={contentVersion:before.state.contentVersion,contentHash:before.state.contentHash,scoreTiming:inputFor(before.state).score.amoScoreTiming};out.checks.push({name:'every visible nine-card touch, stable seats,44px controls, rules/tool bag and no forecast',status:'PASS'});
   if(spec.name==='v11-390')out.naturalTiming=await p.evaluate(()=>{const r=window.__aiProbe.rows.find(r=>r.handCount===9&&r.readyMs!==null);return r?{...r,started:undefined}:null;});
  }else{
   const before=await saved(),first=before.state.handOrder[0],phase=await p.evaluate(()=>window.__harness.game.scene.getScene('game').aiCandidates.result?.status);await hit('card/'+first);assert.deepEqual(await selected(),[first]);assert.deepEqual(await saved(),before);out.manualDuringNatural={phaseBefore:phase,phaseAfter:await p.evaluate(()=>window.__harness.game.scene.getScene('game').aiCandidates.result?.status),selected:first};await ready();out.naturalTiming=await p.evaluate(()=>{const r=window.__aiProbe.rows.find(r=>r.handCount===14&&r.readyMs!==null);return r?{...r,started:undefined}:null;});assert.ok(out.naturalTiming?.slices>0&&out.naturalTiming.readyMs!==null);
   for(const kind of ['DiscardHand','PlayHand']){
    // Fault injection only: hold scheduled AI timers pending, never used for timings.
    await p.evaluate(()=>window.__aiProbe.delayMs=2000);await sort(kind==='DiscardHand'?'rank':'suit');await settled();const state=(await saved()).state,low=state.handOrder.map(id=>state.deckInstances.find(c=>c.id===id)).sort((a,b)=>a.rank-b.rank)[0].id;await hit('card/'+low);assert.deepEqual(await selected(),[low]);assert.equal(await p.evaluate(()=>window.__harness.game.scene.getScene('game').aiCandidates.result?.status),'working');const pre=await saved(),generation=await p.evaluate(()=>window.__harness.game.scene.getScene('game').aiCandidates.generation);await hit(kind==='PlayHand'?'action/play':'action/discard');await p.waitForFunction(seq=>window.__harness.game.registry.get('runController').state.commandSeq===seq+1,pre.state.commandSeq);const after=await saved(),expected=applyCommand(pre.state,{runId:pre.state.runId,commandId:after.state.receipts.at(-1).commandId,expectedSeq:pre.state.commandSeq,action:{type:kind,selectedIds:[low]}});assert.ok(expected.ok);assert.deepEqual(after.state,expected.state);const busy=await p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game');return{playing:s.playing,result:s.aiCandidates.result};});assert.ok(busy.playing);assert.equal(busy.result,undefined);await p.evaluate(()=>window.__aiProbe.delayMs=0);await ready();assert.deepEqual(await saved(),after);assert.deepEqual(await selected(),[]);const row=await p.evaluate(g=>window.__aiProbe.rows.find(r=>r.generation===g),generation);assert.ok(row?.cancelledTimers>0);assert.equal(row.busyUsefulCallbacks,0);assert.equal(row.staleApplied,0);out.checks.push({name:kind+' while AI pending: native action, scheduled work cancelled, authoritative full state, cache rebuilt',status:'PASS',fault:'AI timers delayed2000ms to hold pending work; not performance evidence',generation,row:{...row,started:undefined}});
   }
   // A timer already queued before cancellation may still deliver once after leave.
   await p.evaluate(()=>{window.__aiProbe.delayMs=1000;window.__aiProbe.deliverCleared=true;});await sort('rank');await settled();const generation=await p.evaluate(()=>window.__harness.game.scene.getScene('game').aiCandidates.generation),pre=await saved();await p.locator('.run-menu-toggle').tap();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').tap();await p.getByRole('button',{name:'保存并退出',exact:true}).tap();await waitScene(p,'character-select');await p.waitForFunction(g=>window.__aiProbe.rows.some(r=>r.generation===g&&r.staleCallbacks>0),generation);assert.deepEqual(await saved(),pre);const late=await p.evaluate(g=>({row:window.__aiProbe.rows.find(r=>r.generation===g),cache:window.__harness.game.scene.getScene('game').aiCandidates.result}),generation);assert.equal(late.row.staleApplied,0);assert.equal(late.cache,undefined);out.checks.push({name:'native leave during pending AI and one forced late timer: no cache/selection/save application',status:'PASS',fault:'Deliver one cleared1000ms AI timer to simulate already queued work; not performance evidence',row:{...late.row,started:undefined}});
  }
  assert.deepEqual(out.errors,[]);out.status='PASS';console.log(JSON.stringify({name:spec.name,status:'PASS',checks:out.checks.length,naturalTiming:out.naturalTiming}));
 }catch(e){out.status='FAIL';out.error=String(e);try{out.failure=await observe();await p.screenshot({path:dir+'/'+spec.name+'-failure.png',fullPage:true,scale:'css'});}catch{}throw e;}finally{await context.close();}
}
try{assert.equal(report.build.revision,source);assert.equal(report.build.modified,false);for(const out of report.runs)await run(out);report.sourceFreeze.after=snapshotSource(process.cwd());assert.deepEqual(report.sourceFreeze.after,frozen);report.sourceFreeze.status='PASS';report.status='PASS';}
catch(e){report.status='FAIL';report.error=String(e);console.error(e);process.exitCode=1;}
finally{report.sourceFreeze.after=snapshotSource(process.cwd());await browser.close();await server.httpServer.close();await writeFile(dir+'/browser.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,testedCommit:source,error:report.error,runs:report.runs.map(r=>({name:r.profile.name,status:r.status}))}));}
