/** Bounded PC shop region and native transaction audit. Native inputs, bounded existing fixtures. */
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createServer,build,preview} from 'vite';import {chromium} from 'playwright';import {tapUI,waitScene} from './ui.mjs';
const dir=process.env.PC_SHOP_DIR||'shots/pc-shop-p2';await mkdir(dir,{recursive:true});
const report={source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceStatus:execFileSync('git',['status','--short'],{encoding:'utf8'}).trim(),scope:'Software Canvas native import, three goods, detail/cancel, build/inventory/tool/item routes, horizontal rack drag, PC region and unchanged phone layout audit. Controlled saves, no natural purchase/score/physical device claim.',cases:[],pages:[],screenshots:[]};
const origin='docs/production/evidence/w1-inputs-2026-10-07/',cpShop=JSON.parse(await readFile(origin+'controlled-shop.json','utf8'));const cpFull=JSON.parse(await readFile('docs/production/evidence/pc-shop-2026-10-07/controlled-full-shop.json','utf8'));
const ssr=await createServer({server:{middlewareMode:true},logLevel:'error'});let disabled;
try{const {createRun}=await ssr.ssrLoadModule('/src/domain/run.ts'),{makeCheckpoint,readCheckpoint}=await ssr.ssrLoadModule('/src/application/checkpoint.ts');const s=createRun({seed:'challenge/q06/0',runId:'regions/disabled',rulesVersion:'r2',characterId:'amo',modeConfig:{mode:'challenge',difficulty:0,challengeId:'Q06',programsEnabled:true},contentVersion:cpShop.state.contentVersion});disabled=makeCheckpoint(s,[]);assert.ok(readCheckpoint(disabled).ok);assert.equal(s.shop.toolOffers[0].definitionId,'S01');await writeFile(dir+'/disabled.json',JSON.stringify(disabled));}finally{await ssr.close();}
await build({mode:'e2e',build:{outDir:dir+'/build'},logLevel:'error'});report.build=JSON.parse(await readFile(dir+'/build/build-info.json','utf8'));
const server=await preview({build:{outDir:dir+'/build'},preview:{host:'127.0.0.1',port:5397,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});report.browser=browser.version();
const state=p=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),ready=async(p,key)=>{await waitScene(p,key);await p.waitForFunction(key=>{const s=window.__harness.game.scene.getScene(key);return s.ready&&(key!=='game'||s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container)));},key);await p.waitForTimeout(350);};
const imp=async(p,cp,key)=>{await p.locator('.run-menu-toggle').click();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').click();const fc=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await fc).setFiles({name:'pc-shop.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});await ready(p,key);};
const dialog=async p=>{const d=p.locator('.detail-dialog[open]');await d.waitFor();return {text:await d.innerText(),buttons:await d.getByRole('button').evaluateAll(bs=>bs.map(b=>({text:b.textContent,disabled:b.disabled,bounds:b.getBoundingClientRect().toJSON()}))),rect:await d.evaluate(d=>d.getBoundingClientRect().toJSON())};};
const shot=async(p,name)=>{await p.screenshot({path:dir+'/'+name+'.png',scale:'css'});report.screenshots.push(name+'.png');};
const observe=(p,key)=>p.evaluate(key=>{const s=window.__harness.game.scene.getScene(key),walk=list=>list.flatMap(o=>[o,...(o.list?walk(o.list):[])]),all=walk(s.children.list),box=o=>{const b=o.getBounds();return{x:b.x,y:b.y,width:b.width,height:b.height};};return {layout:s.view.layout,geometry:key==='shop'?s.geometry():undefined,offerBoxes:s.pcOfferBoxes?Object.fromEntries(s.pcOfferBoxes):{},texts:all.filter(o=>o.type==='Text'&&o.visible&&o.parentContainer?.visible!==false).map(o=>({name:o.name,text:o.text,offerId:o.getData('offerId'),fullText:o.getData('fullText'),font:parseFloat(o.style.fontSize),bounds:box(o)})),controls:all.filter(o=>o.input?.enabled).map(o=>({name:o.name,bounds:box(o)}))};},key);
const intersects=(a,b)=>a.x<b.x+b.width-.01&&b.x<a.x+a.width-.01&&a.y<b.y+b.height-.01&&b.y<a.y+a.height-.01;
function inspect(o,spec){const inside=b=>assert.ok(b.x>=-.1&&b.y>=-.1&&b.x+b.width<=spec.width+.1&&b.y+b.height<=spec.height-(spec.safe?.bottom??0)+.1,JSON.stringify({spec,b}));
 for(const c of o.controls){inside(c.bounds);assert.ok(c.bounds.width>=44&&c.bounds.height>=44);}
 if(!o.geometry.pc)return;const pc=o.geometry.pc;for(const b of [...o.geometry.shelf,...pc.jokerOffers,pc.toolOffers,pc.itemOffers,pc.feedback])inside(b);for(const b of [pc.toolOffers,pc.itemOffers])assert.ok(!intersects(b,pc.feedback));
 for(const t of o.texts.filter(t=>t.name.startsWith('shop/offer-'))){inside(t.bounds);assert.ok(t.font>=14);}
 for(const t of o.texts.filter(t=>t.name==='shop/offer-purpose')){assert.equal(t.text.replaceAll('\n',''),t.fullText);const price=o.texts.find(x=>x.name==='shop/offer-price'&&x.offerId===t.offerId);assert.ok(price);assert.ok(!intersects(t.bounds,price.bounds),JSON.stringify({purpose:t,price}));const reason=o.texts.find(x=>x.name==='shop/offer-reason'&&x.offerId===t.offerId);if(reason)assert.ok(!intersects(t.bounds,reason.bounds));const tile=o.offerBoxes[t.offerId];assert.ok(tile);assert.ok(t.bounds.y+t.bounds.height<=tile.y+tile.height+.1,JSON.stringify({t,tile}));}
}
try{
 const specs=[...[1912,1920].flatMap(width=>[712,720,768].flatMap(height=>[0,12,34].map(bottom=>({width,height,safe:{top:0,bottom}})))),...[1000,1024,1280].map(width=>({width,height:768,safe:{top:0,bottom:0},s01:true}))];
 for(const spec of specs){const p=await browser.newPage({viewport:{width:spec.width,height:spec.height},reducedMotion:'reduce'});p.on('dialog',d=>d.accept());const row={spec};report.cases.push(row);try{await p.addInitScript(safe=>document.addEventListener('DOMContentLoaded',()=>{for(const [k,v]of Object.entries(safe))document.documentElement.style.setProperty('--safe-'+k,v+'px');}),spec.safe);await p.goto('http://127.0.0.1:5397/?harness=1');await waitScene(p,'title');await imp(p,spec.s01?disabled:cpShop,'shop');row.observation=await observe(p,'shop');inspect(row.observation,spec);if((spec.width===1920&&spec.height===720&&spec.safe.bottom===0)||spec.width===1000)await shot(p,'p2-'+spec.width+'x'+spec.height);row.status='PASS';}catch(e){row.status='FAIL';row.error=String(e);await shot(p,'FAIL-'+spec.width+'x'+spec.height);throw e;}finally{await p.close();}}
 const p=await browser.newPage({viewport:{width:1280,height:768},reducedMotion:'reduce'});p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:5397/?harness=1');await waitScene(p,'title');await imp(p,disabled,'shop');const before=await state(p),offer=before.shop.toolOffers[0];await tapUI(p,'shop','offer/'+offer.offerId);const detail=await dialog(p);assert.match(detail.text,/牺牲/);await p.getByRole('button',{name:'取消',exact:true}).click();report.resize=[];for(const width of [1000,1024,1280]){await p.setViewportSize({width,height:768});await p.waitForTimeout(350);const observation=await observe(p,'shop');inspect(observation,{width,height:768});assert.deepEqual(await state(p),before);assert.equal(await p.evaluate(()=>window.__harness.game.scene.getScene('shop').selectedOfferId),offer.offerId);report.resize.push({width,observation});}await p.close();report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);process.exitCode=1;console.error(e);}finally{await browser.close();await server.httpServer.close();await writeFile(dir+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(report.status,report.cases.length,report.error||'');}
