/** First-chapter shop response and adjacent-page audit. Native inputs, bounded existing fixtures. */
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createServer,build,preview} from 'vite';import {chromium} from 'playwright';import {tapUI,waitScene,openSelector} from './ui.mjs';
const dir=process.env.PC_SHOP_DIR||'shots/pc-shop-final';await mkdir(dir,{recursive:true});
const report={source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceStatus:execFileSync('git',['status','--short'],{encoding:'utf8'}).trim(),scope:'Software Canvas native import, three goods, detail/cancel, build/inventory/tool/item routes, wrapped rack drag and adjacent-page region audit. Controlled saves, no natural purchase/score/physical device claim.',cases:[],pages:[],screenshots:[]};
const origin='docs/production/evidence/w1-inputs-2026-10-07/',cpShop=JSON.parse(await readFile(origin+'controlled-shop.json','utf8')),cpNine=JSON.parse(await readFile(origin+'controlled-nine.json','utf8'));let cpFull,cpWin,cpLose;
const ssr=await createServer({server:{middlewareMode:true},logLevel:'error'});
try{const {applyCommand}=await ssr.ssrLoadModule('/src/domain/run.ts'),{r2CreateJoker}=await ssr.ssrLoadModule('/src/domain/r2Run.ts'),{makeCheckpoint,readCheckpoint}=await ssr.ssrLoadModule('/src/application/checkpoint.ts'),{r2SelectionFacts}=await ssr.ssrLoadModule('/src/domain/r2SelectionFacts.ts'),{r2JokerDefinitionsFor}=await ssr.ssrLoadModule('/src/domain/r2ContentProfiles.ts');
 const send=(s,action)=>{const r=applyCommand(s,{runId:s.runId,commandId:'pc-shop/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action});assert.ok(r.ok,r.code);return r.state;},checked=s=>{const cp=makeCheckpoint(s,[]);assert.ok(readCheckpoint(cp).ok);return cp;};
 let full=structuredClone(cpShop.state);for(const id of ['b03','b08','mantangcai'])full.jokers.push(r2CreateJoker(id,'pc-shop/'+id,6,undefined,full));cpFull=checked(full);
 const order=['flush-five','flush-house','five-kind','four-kind','full-house','straight-flush','flush','straight','three-kind','two-pair','pair','high-card'];
 let s=structuredClone(cpNine.state);for(let n=0;n<4&&s.phase==='await-input';n++){const hand=s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)),choices=[];const visit=(start,ids)=>{if(ids.length){const facts=r2SelectionFacts({hand,selectedIds:ids,jokers:s.jokers,definitions:r2JokerDefinitionsFor(s),handRules:s.handRules,disabledIds:s.stage.disabledIds});choices.push({ids,type:facts.type});}if(ids.length===5)return;for(let i=start;i<hand.length;i++)visit(i+1,[...ids,hand[i].id]);};visit(0,[]);choices.sort((a,b)=>order.indexOf(a.type)-order.indexOf(b.type)||b.ids.length-a.ids.length);s=send(s,{type:'PlayHand',selectedIds:choices[0].ids});}assert.equal(s.phase,'stage-cleared');cpWin=checked(s);
 s=structuredClone(cpNine.state);for(let n=0;n<4&&s.phase==='await-input';n++)s=send(s,{type:'PlayHand',selectedIds:[s.handOrder[0]]});assert.equal(s.phase,'run-lost');cpLose=checked(s);
 await writeFile(dir+'/controlled-full-shop.json',JSON.stringify(cpFull,null,2)+'\n');await writeFile(dir+'/controlled-win.json',JSON.stringify(cpWin,null,2)+'\n');await writeFile(dir+'/controlled-lose.json',JSON.stringify(cpLose,null,2)+'\n');
}finally{await ssr.close();}
await build({mode:'e2e',build:{outDir:dir+'/build'},logLevel:'error'});report.build=JSON.parse(await readFile(dir+'/build/build-info.json','utf8'));
const server=await preview({build:{outDir:dir+'/build'},preview:{host:'127.0.0.1',port:5393,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});report.browser=browser.version();
const state=p=>p.evaluate(()=>window.__harness.game.registry.get('runController').state),ready=async(p,key)=>{await waitScene(p,key);await p.waitForFunction(key=>{const s=window.__harness.game.scene.getScene(key);return s.ready&&(key!=='game'||s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container)));},key);await p.waitForTimeout(350);};
const imp=async(p,cp,key)=>{await p.locator('.run-menu-toggle').click();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').click();const fc=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await fc).setFiles({name:'pc-shop.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});await ready(p,key);};
const dialog=async p=>{const d=p.locator('.detail-dialog[open]');await d.waitFor();return {text:await d.innerText(),buttons:await d.getByRole('button').evaluateAll(bs=>bs.map(b=>({text:b.textContent,disabled:b.disabled,bounds:b.getBoundingClientRect().toJSON()}))),rect:await d.evaluate(d=>d.getBoundingClientRect().toJSON())};};
const shot=async(p,name)=>{await p.screenshot({path:dir+'/'+name+'.png',scale:'css'});report.screenshots.push(name+'.png');};
const observe=(p,key)=>p.evaluate(key=>{const s=window.__harness.game.scene.getScene(key),walk=list=>list.flatMap(o=>[o,...(o.list?walk(o.list):[])]),all=walk(s.children.list),box=o=>{const b=o.getBounds();return{x:b.x,y:b.y,width:b.width,height:b.height};};return {layout:s.view.layout,geometry:key==='shop'?s.geometry():undefined,texts:all.filter(o=>o.type==='Text'&&o.visible&&o.parentContainer?.visible!==false).map(o=>({name:o.name,text:o.text,font:parseFloat(o.style.fontSize),bounds:box(o)})),controls:all.filter(o=>o.input?.enabled).map(o=>({name:o.name,bounds:box(o)}))};},key);
const intersects=(a,b)=>a.x<b.x+b.width-.01&&b.x<a.x+a.width-.01&&a.y<b.y+b.height-.01&&b.y<a.y+a.height-.01;
function inspectGeometry(o,spec){const safe=spec.safe??{top:0,bottom:0},inside=b=>assert.ok(b.x>=-.1&&b.y>=safe.top-.1&&b.x+b.width<=spec.width+.1&&b.y+b.height<=spec.height-safe.bottom+.1,JSON.stringify({spec,b}));for(const c of o.controls){inside(c.bounds);assert.ok(c.bounds.width>=44&&c.bounds.height>=44,c.name);}
 const texts=o.texts.filter(t=>t.name?.startsWith('shop/offer-'));for(const t of texts){inside(t.bounds);assert.ok(t.font>=14);for(const c of o.controls.filter(c=>c.name?.startsWith('action/')))assert.ok(!intersects(t.bounds,c.bounds),'copy clear of '+c.name);}
 if(o.geometry.desktop){assert.ok(o.geometry.tabs.width>420);const purposes=texts.filter(t=>t.name==='shop/offer-purpose');assert.equal(purposes.length,3);assert.ok(purposes.every(t=>!t.text.includes('条件与效果')&&!t.text.includes('…')),'actual current three effects visible');for(const t of purposes){const price=texts.find(p=>p.name==='shop/offer-price'&&Math.abs(p.bounds.x-t.bounds.x)<1);assert.ok(t.bounds.y+t.bounds.height<=price.bounds.y-4);}}
}
try{
 for(const spec of [{width:1280,height:720},{width:1366,height:768},{width:1912,height:954},{width:1920,height:1080},{width:1024,height:500,safe:{top:24,bottom:34}},{width:390,height:740},{width:320,height:740},{width:740,height:390}]){
  const ctx=await browser.newContext({viewport:{width:spec.width,height:spec.height},deviceScaleFactor:1,reducedMotion:'reduce'}),p=await ctx.newPage(),row={spec,errors:[]};report.cases.push(row);p.on('pageerror',e=>row.errors.push(String(e)));p.on('dialog',d=>d.accept());
  try{await p.addInitScript(safe=>document.addEventListener('DOMContentLoaded',()=>{for(const [k,v] of Object.entries(safe))document.documentElement.style.setProperty('--safe-'+k,v+'px');}),spec.safe??{});await p.goto('http://127.0.0.1:5393/?harness=1');await waitScene(p,'title');await imp(p,cpShop,'shop');row.shop=await observe(p,'shop');inspectGeometry(row.shop,spec);const before=await state(p);
   if([1912,320,740].includes(spec.width))await shot(p,'shop-'+spec.width);
   for(const o of before.shop.offers){await tapUI(p,'shop','offer/'+o.offerId);const detail=await dialog(p);assert.ok(detail.text.includes('取消'));assert.ok(detail.rect.left>=0&&detail.rect.right<=spec.width&&detail.rect.bottom<=spec.height-(spec.safe?.bottom??0));row.purchase??=[];row.purchase.push({id:o.definitionId,...detail});await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await state(p),before);}
   for(const kind of ['tools','items']){await tapUI(p,'shop','action/shelf-'+kind);await p.waitForTimeout(350);row[kind]=await observe(p,'shop');const offer=before.shop[kind==='tools'?'toolOffers':'itemOffers'][0];await tapUI(p,'shop','offer/'+offer.offerId);row[kind+'Detail']=await dialog(p);await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await state(p),before);}
   await tapUI(p,'shop','action/tool-inventory');row.inventory=await dialog(p);assert.match(row.inventory.text,/红桃染/);assert.match(row.inventory.text,/宽桌面/);await p.getByRole('button',{name:'关闭',exact:true}).click();assert.deepEqual(await state(p),before);
   await tapUI(p,'shop','action/build');row.build=await dialog(p);assert.match(row.build.text,/长期道具 1\/4/);await p.getByRole('button',{name:'关闭',exact:true}).click();
   if(!row.shop.geometry.inventoryCollapsed){await tapUI(p,'shop','joker/w1/b10');row.held=await dialog(p);await p.getByRole('button',{name:'出售',exact:true}).click();row.sell=await dialog(p);await p.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await state(p),before);}else row.heldManagement='NOT_AVAILABLE: existing collapsed short-landscape build dialog lists owned cards but exposes no reorder/sell entry; W3 gap, not claimed passed.';
   if(row.shop.geometry.desktop){await imp(p,cpFull,'shop');row.full=await observe(p,'shop');const old=await state(p),target=row.full.geometry.slots[3],first=row.full.geometry.slots[0];await p.mouse.move(first.x+first.width/2,first.y+first.height/2);await p.mouse.down();await p.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:6});await p.mouse.up();await p.waitForFunction(()=>window.__harness.game.registry.get('runController').state.jokers[3].instanceId==='w1/b10');row.afterDrag=await state(p);assert.equal(row.afterDrag.gold,old.gold);assert.deepEqual([...row.afterDrag.jokers].sort((a,b)=>a.instanceId.localeCompare(b.instanceId)),[...old.jokers].sort((a,b)=>a.instanceId.localeCompare(b.instanceId)));if(spec.width===1912)await shot(p,'full-build-1912');}
   assert.deepEqual(row.errors,[]);row.status='PASS';
  }catch(e){row.status='FAIL';row.error=String(e);await shot(p,'FAIL-'+spec.width);throw e;}finally{await ctx.close();}
 }
 // Finite region audit at the user's desktop dimensions; no changes to adjacent scenes.
 const p=await browser.newPage({viewport:{width:1912,height:954},reducedMotion:'reduce'});p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:5393/?harness=1');await openSelector(p);await tapUI(p,'character-select','character/erxiang');await p.waitForTimeout(350);report.pages.push({page:'character-select',observation:await observe(p,'character-select')});await shot(p,'selector-1912');await imp(p,cpNine,'game');report.pages.push({page:'game',observation:await observe(p,'game')});await shot(p,'table-1912');await imp(p,cpWin,'intermission');report.pages.push({page:'success',observation:await observe(p,'intermission')});await shot(p,'success-1912');await imp(p,cpLose,'intermission');report.pages.push({page:'failure',observation:await observe(p,'intermission')});await shot(p,'failure-1912');await p.close();report.status='PASS';
}catch(e){report.status='FAIL';report.error=String(e);process.exitCode=1;console.error(e);}finally{await browser.close();await server.httpServer.close();await writeFile(dir+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(report.status,report.cases.map(c=>[c.spec.width,c.status]),report.error||'');}
