/** D40: frozen-bundle resource observations and real-input scope-cancellation regressions. */
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
import {preview} from 'vite';
import {waitScene,tapUI,confirmHeroRoute} from './ui.mjs';
const dir=process.env.RESOURCE_FLOW_EVIDENCE_DIR||'shots/resource-flow/after',build=process.env.RESOURCE_FLOW_BUILD_DIR||'shots/resource-flow/after/build',port=5221;
await mkdir(dir,{recursive:true});
const report={scope:'D40 registered-runtime resource flow: natural desktop/mobile, controlled slow HD after shelf replacement/exit and mobile revisit; only intentional reroll/EnterStage domain commands',node:process.version,runs:[],limits:['Linux Chromium Canvas, GPU/software rasterization disabled; no physical-phone/WebGL claim.','decode wrappers measure explicit HTMLImageElement.decode/createImageBitmap promises; browser implicit decode internals are not observable.','Scene readiness is first observed enabled public control, not a network-idle milestone.','Controlled slow HD is separate from natural local-server timing.']};
report.buildInfo=JSON.parse(await readFile(build+'/build-info.json','utf8'));const html=await readFile(build+'/index.html','utf8'),asset=html.match(/src="([^"]+\.js)"/)[1];report.bundle={asset,sha256:createHash('sha256').update(await readFile(build+'/'+asset)).digest('hex')};
const registry=(await readFile('src/game/jokerArt.ts','utf8')).matchAll(/id: '([^']+)'/g),registered=new Set([...registry].map(m=>m[1]));
const server=await preview({build:{outDir:build},preview:{host:'127.0.0.1',port,strictPort:true},logLevel:'warn'});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});report.browser=browser.version();
async function persisted(p){return p.evaluate(async()=>{const c=window.__harness.game.registry.get('runController');const storage=await new Promise((resolve,reject)=>{const q=indexedDB.open('dachoupai-checkpoints');q.onsuccess=()=>{const db=q.result,tx=db.transaction('saves','readonly'),req=tx.objectStore('saves').getAll();tx.oncomplete=()=>{db.close();resolve(req.result);};tx.onerror=()=>reject(tx.error);};q.onerror=()=>reject(q.error);});return{state:c.state,journal:c.journal,status:c.status,export:c.exportJSON(),storage};});}
async function observe(p){return p.evaluate(()=>{const g=window.__harness.game,d=document.querySelector('.detail-dialog[open]'),i=d?.querySelector('.dialog-card-image'),f=d?.querySelector('.dialog-actions');return{at:performance.now(),scene:g.scene.getScenes(true).map(s=>s.sys.settings.key),renderer:g.renderer.gl?'WebGL':'Canvas',fps:g.loop.actualFps,dialog:d?{title:d.querySelector('h2')?.textContent,ability:d.querySelector('.card-ability')?.innerText,width:i?.naturalWidth,height:i?.naturalHeight,src:i?.currentSrc?.startsWith('blob:')?'blob':i?.currentSrc,origin:window.__rf.blobOrigins.get(i?.currentSrc)??null,visual:(()=>{const node=d.querySelector('.f09-art-window,.dialog-art-visual'),card=node?.closest('.dialog-card-art'),b=node?.getBoundingClientRect(),parent=d.getBoundingClientRect(),frame=card?.getBoundingClientRect(),sx=parent.width/d.offsetWidth,sy=parent.height/d.offsetHeight;return b&&frame?{x:(b.x-frame.x)/sx,y:(b.y-frame.y)/sy,width:b.width/sx,height:b.height/sy}:null;})(),positionInDialog:(()=>{const b=d.querySelector('.f09-art-window,.dialog-art-visual')?.getBoundingClientRect(),parent=d.getBoundingClientRect(),sx=parent.width/d.offsetWidth,sy=parent.height/d.offsetHeight;return b?{x:(b.x-parent.x)/sx,y:(b.y-parent.y)/sy}:null;})(),hdStatus:d.querySelector('.detail-art-status:not(.dialog-art-load-status)')?.textContent,footerBottom:f?.getBoundingClientRect().bottom}:null,activeFetches:[...window.__rf.activeFetches.values()],decodeActive:window.__rf.decodeActive,bitmapActive:window.__rf.bitmapActive};});}
async function run(name,viewport,touch,variant='natural'){
 const slow=variant!=='natural';
 const c=await browser.newContext({viewport,hasTouch:touch,deviceScaleFactor:touch?3:1}),p=await c.newPage(),r={name,viewport,touch,dpr:touch?3:1,network:slow?'CONTROLLED HD responses held until explicit release':'unthrottled local server, cold browser context',requests:[],marks:[],errors:[],checks:[]};report.runs.push(r);let phase='boot';const navStart=Date.now(),reqMap=new Map(),held=[];
 p.on('pageerror',e=>r.errors.push(String(e)));p.on('request',req=>{const x={scheme:new URL(req.url()).protocol,path:new URL(req.url()).pathname,type:req.resourceType(),phase,startMs:Date.now()-navStart};r.requests.push(x);reqMap.set(req,x);});p.on('response',res=>{const x=reqMap.get(res.request());if(x){x.status=res.status();x.responseMs=Date.now()-navStart;}});p.on('requestfinished',req=>{const x=reqMap.get(req);if(x)x.endMs=Date.now()-navStart;});p.on('requestfailed',req=>{const x=reqMap.get(req);if(x){x.endMs=Date.now()-navStart;x.failure=req.failure()?.errorText;}});
 await p.addInitScript(()=>{
  const r=window.__rf={phase:'boot',events:[],ready:{},activeFetches:new Map(),blobOrigins:new Map(),decodeActive:0,bitmapActive:0,maxDecode:0,maxBitmap:0,maxFetch:0};let serial=0;
  const push=(type,data={})=>r.events.push({type,at:performance.now(),phase:r.phase,...data});
  const origins=new WeakMap(),readBlob=Response.prototype.blob,objectURL=URL.createObjectURL;Response.prototype.blob=function(...args){const url=this.url;return readBlob.apply(this,args).then(blob=>{origins.set(blob,url);return blob;});};URL.createObjectURL=function(blob){const url=objectURL.call(this,blob);r.blobOrigins.set(url,origins.get(blob));return url;};
  const decode=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=function(...args){const id=++serial;r.decodeActive++;r.maxDecode=Math.max(r.maxDecode,r.decodeActive);push('decode-start',{id,src:this.src});return decode.apply(this,args).then(value=>{push('decode-end',{id,src:this.src});r.decodeActive--;return value;},error=>{push('decode-error',{id,src:this.src,error:String(error)});r.decodeActive--;throw error;});};
  const bitmap=window.createImageBitmap;window.createImageBitmap=function(...args){const id=++serial;r.bitmapActive++;r.maxBitmap=Math.max(r.maxBitmap,r.bitmapActive);push('bitmap-start',{id,bytes:args[0]?.size});return bitmap.apply(this,args).then(value=>{push('bitmap-end',{id,width:value.width,height:value.height});r.bitmapActive--;return value;},error=>{push('bitmap-error',{id,error:String(error)});r.bitmapActive--;throw error;});};
  const fetch=window.fetch;window.fetch=function(input,init){const url=typeof input==='string'?input:input.url,id=++serial;r.activeFetches.set(id,{url,at:performance.now(),phase:r.phase});r.maxFetch=Math.max(r.maxFetch,r.activeFetches.size);push('fetch-start',{id,url,priority:init?.priority});init?.signal?.addEventListener('abort',()=>push('fetch-abort',{id,url}),{once:true});return fetch.apply(this,arguments).then(v=>{r.activeFetches.delete(id);push('fetch-response',{id,url,status:v.status});return v;},e=>{r.activeFetches.delete(id);push('fetch-error',{id,url,error:String(e)});throw e;});};
  const watch=()=>{const g=window.__harness?.game;if(g){const walk=(list,name)=>list.some(o=>o.name===name&&o.input?.enabled||o.list&&walk(o.list,name));for(const [key,target]of[['title','action/title-start'],['character-select','character/amo'],['shop','action/start-stage']]){const s=g.scene.getScene(key);if(!r.ready[key]&&s?.scene.isActive()&&s.input.enabled&&g.input.enabled&&walk(s.children.list,target))r.ready[key]={at:performance.now(),fps:g.loop.actualFps,renderer:g.renderer.gl?'WebGL':'Canvas'};}}requestAnimationFrame(watch);};requestAnimationFrame(watch);
 });
 if(slow)await p.route('**/*-detail.webp',async route=>{const entry={path:new URL(route.request().url()).pathname,at:Date.now()-navStart,released:false};r.held??=[];r.held.push(entry);await new Promise(resolve=>held.push({entry,release:()=>{entry.released=true;entry.releaseMs=Date.now()-navStart;resolve();}}));await route.continue().catch(()=>{});});
 const mark=async(label)=>{phase=label;await p.evaluate(label=>window.__rf.phase=label,label);const o=await observe(p);r.marks.push({label,...o});return o;};
 const open=async id=>{const offer=await p.evaluate(id=>window.__harness.game.registry.get('runController').state.shop.offers.find(o=>o.definitionId===id),id);assert.ok(offer,id+' natural offer');await tapUI(p,'shop','offer/'+offer.offerId,touch);await p.locator('.detail-dialog[open]').waitFor();return offer;};
 const close=async()=>{const b=p.getByRole('button',{name:'取消',exact:true});if(touch)await b.tap();else await b.click();};
 // Releasing only the current response proves it does not depend on retired transfers.
 const releaseHeld=(predicate=()=>true)=>{for(const h of held)if(!h.entry.released&&predicate(h.entry.path))h.release();};
 const hdEvents=()=>p.evaluate(()=>window.__rf.events.filter(e=>e.type==='fetch-start'||e.type==='fetch-abort'));
 const waitFetch=id=>p.waitForFunction(id=>window.__rf.events.some(e=>e.type==='fetch-start'&&e.url.endsWith('/'+id+'-detail.webp')),id);
 const assertAborted=async ids=>{const events=await hdEvents();for(const id of ids)assert.ok(events.some(e=>e.type==='fetch-abort'&&e.url.endsWith('/'+id+'-detail.webp')),id+': retired fetch signal aborted');};
 const readyHD=async id=>{await p.waitForFunction(id=>{const image=document.querySelector('.dialog-card-image');return image?.naturalWidth>256&&window.__rf.blobOrigins.get(image.currentSrc)?.endsWith('/'+id+'-detail.webp');},id);return observe(p);};
 // Compare the art window in its card frame coordinates, removing the existing dialog entrance scale.
 // Keep dialog-relative position as a diagnostic: the old baseline also shifts vertically when its loading row collapses.
 const sameFrame=(a,b)=>{(r.frameComparisons??=[]).push({before:a.dialog.visual,after:b.dialog.visual,title:b.dialog.title});for(const k of ['x','y','width','height'])assert.ok(Math.abs(a.dialog.visual[k]-b.dialog.visual[k])<=1.5,'HD replacement keeps fixed visual '+k);assert.equal(b.dialog.title,a.dialog.title,'late old image cannot change current detail');};

 try{
  await p.goto(`http://127.0.0.1:${port}/?harness=1&seed=f09-sample-30`);await waitScene(p,'title');await mark('title-usable');assert.equal(r.marks.at(-1).renderer,'Canvas');assert.ok(!r.requests.some(q=>q.path.includes('jokers-p07')||q.path.includes('-detail.webp')||/characters-p07\/[a-z]+\.webp$/.test(q.path)),'Boot excludes Joker and full portraits');r.checks.push('Boot has no Joker/full portrait/HD requests');
  await tapUI(p,'title','action/title-start',touch);await waitScene(p,'character-select');await mark('selector-usable');await tapUI(p,'character-select','character/amo',touch);assert.equal(await p.evaluate(()=>window.__harness.game.scene.getScene('character-select').selectedId),'amo');await confirmHeroRoute(p,touch);await waitScene(p,'shop');await mark('shop-usable');r.offers=await p.evaluate(()=>window.__harness.game.registry.get('runController').state.shop.offers);const before=await persisted(p);
  if(!slow){
   await open('f09');const low=await mark('f09-detail-controls-usable');assert.ok(low.dialog.ability.includes('×1.5'));assert.ok(low.dialog.footerBottom<=viewport.height+.5);const high=await readyHD('f09');sameFrame(low,high);await mark('f09-HD-visible');await p.screenshot({path:`${dir}/${name}-detail.png`});await close();assert.deepEqual(await persisted(p),before,'detail opening/closing cannot mutate state/RNG/save');r.checks.push('Natural f09 ability/footer, correct HD source, fixed visual, unchanged state/RNG/save');
  }else if(variant==='exit'){
   await p.waitForFunction(()=>window.__rf.activeFetches.size===2);await mark('two-prefetches-active');await open('f09');await mark('A-open');await close();await mark('A-closed-shelf-still-visible');assert.equal((await hdEvents()).filter(e=>e.type==='fetch-abort').length,0,'visible shelf remains a valid shared consumer');assert.deepEqual(await persisted(p),before);
   await tapUI(p,'shop','action/start-stage',false);await waitScene(p,'game');await mark('shop-shutdown-game-active');await p.waitForTimeout(250);await mark('after-exit250ms');await assertAborted(['a03','f09']);assert.equal((await observe(p)).activeFetches.length,0,'retired scope frees fetches without response release');releaseHeld();await p.unroute('**/*-detail.webp');await p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.cardViews.length&&s.cardViews.every(c=>!c.dealing&&!c.back?.visible);});assert.equal(await p.evaluate(()=>window.__rf.events.filter(e=>e.type==='bitmap-start').length),0,'abandoned responses never begin bitmap decode');await p.screenshot({path:`${dir}/${name}-after-exit.png`});r.checks.push('Scene exit cancels two retired transfers before response release; no obsolete bitmap decode');
  }else if(variant==='mobile-revisit'){
   await waitFetch('a03');await open('a03');await close();await mark('A-closed-still-visible');assert.equal((await hdEvents()).filter(e=>e.type==='fetch-abort').length,0,'closing detail preserves visible shelf consumer');
   await open('f09');await mark('B-on-second-page');await assertAborted(['a03']);await close();await tapUI(p,'shop','action/shelf-tools',true);await mark('tools-no-joker-consumers');await assertAborted(['f09']);assert.equal((await observe(p)).activeFetches.length,0);
   const count=(await hdEvents()).filter(e=>e.type==='fetch-start'&&e.url.endsWith('/f09-detail.webp')).length;await tapUI(p,'shop','action/shelf-jokers',true);await open('f09');const low=await mark('A-revisited-after-cancel');await p.waitForFunction(count=>window.__rf.events.filter(e=>e.type==='fetch-start'&&e.url.endsWith('/f09-detail.webp')).length>count,count);releaseHeld(path=>path.endsWith('/f09-detail.webp'));const high=await readyHD('f09');sameFrame(low,high);await mark('A-revisit-HD-visible');await p.screenshot({path:`${dir}/${name}-revisit.png`});await close();assert.deepEqual(await persisted(p),before,'paging/tool tabs/cancel/revisit do not mutate full state/RNG/save');r.checks.push('Mobile shelf change cancels only obsolete URL; returning requests canceled image anew; correct source/frame and unchanged persistence');
  }else{
   await p.waitForFunction(()=>window.__rf.activeFetches.size===2);await mark('two-prefetches-active');await open('f09');await mark('A-f09-open');await close();await mark('A-closed');await open('a03');await mark('B-a03-open');await close();await mark('B-closed');await open('f09');await mark('A-reopened');await close();assert.deepEqual(await persisted(p),before,'A/B/reopen does not mutate state/RNG/save');assert.equal((await hdEvents()).filter(e=>e.type==='fetch-abort').length,0,'A/B closing leaves visible shelf subscriptions');
   await mark('before-natural-reroll');const seq=before.state.commandSeq;await tapUI(p,'shop','action/reroll',false);await p.waitForFunction(seq=>{const c=window.__harness.game.registry.get('runController');return c.state.commandSeq>seq&&c.status==='idle';},seq);const changed=await p.evaluate(()=>window.__harness.game.registry.get('runController').state);r.reroll={gold:changed.gold,seq:changed.commandSeq,offers:changed.shop.offers};await mark('after-natural-reroll');const next=changed.shop.offers.find(o=>registered.has(o.definitionId)&&!['a03','f09'].includes(o.definitionId));assert.ok(next,'natural reroll supplies third registered card');r.third=next.definitionId;const afterReroll=await persisted(p);await open(next.definitionId);const low=await mark('C-open-with-old-HD');await p.waitForTimeout(250);await mark('C-after250ms');await assertAborted(['a03','f09']);await waitFetch(next.definitionId);assert.ok(r.held.filter(h=>/\/(a03|f09)-detail.webp$/.test(h.path)).every(h=>!h.released),'new request starts while retired responses remain held');
   releaseHeld(path=>path.endsWith('/'+next.definitionId+'-detail.webp'));const high=await readyHD(next.definitionId);sameFrame(low,high);await mark('C-HD-visible-before-old-release');await p.screenshot({path:`${dir}/${name}-C-ready.png`});releaseHeld(path=>/\/(a03|f09)-detail.webp$/.test(path));await mark('old-HD-released');assert.equal((await observe(p)).dialog.origin,high.dialog.origin,'late retired requests cannot paste their image into C');await close();assert.deepEqual(await persisted(p),afterReroll,'details do not alter intentional reroll result');r.checks.push('Last shelf consumers abort; C requests/displays before old responses release; correct source/frame; no stale image or extra commands');
  }
  assert.deepEqual(r.errors,[],'no browser page errors');assert.ok(await p.evaluate(()=>window.__rf.maxFetch<=2),'HD fetch concurrency stays bounded at two');
  r.status='PASS';
 }catch(e){r.status='FAIL';r.error=String(e);process.exitCode=1;await p.screenshot({path:`${dir}/${name}-failure.png`}).catch(()=>{});}
 finally{
  releaseHeld();r.observer=await p.evaluate(()=>({events:window.__rf.events,ready:window.__rf.ready,maxDecode:window.__rf.maxDecode,maxBitmap:window.__rf.maxBitmap,maxFetch:window.__rf.maxFetch,resources:performance.getEntriesByType('resource').map(e=>({name:e.name,initiator:e.initiatorType,start:e.startTime,end:e.responseEnd,duration:e.duration,bytes:e.encodedBodySize,transfer:e.transferSize}))})).catch(()=>null);await writeFile(`${dir}/${name}.json`,JSON.stringify(r,null,2));await c.close();await writeFile(`${dir}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({name,status:r.status,error:r.error,ready:r.observer?.ready,requests:r.requests.length,third:r.third}));
 }
}
const cases=[['desktop-natural',{width:1280,height:800},false],['touch-natural',{width:412,height:820},true],['desktop-slow-HD',{width:1280,height:800},false,'replace'],['desktop-slow-exit',{width:1280,height:800},false,'exit'],['touch-slow-revisit',{width:412,height:820},true,'mobile-revisit']];
const requested=process.env.RESOURCE_FLOW_CASES?.split(',')??cases.map(c=>c[0]);assert.ok(requested.every(name=>cases.some(c=>c[0]===name)),'known focused cases');
try{for(const spec of cases.filter(c=>requested.includes(c[0])))await run(...spec);
}finally{await browser.close();await server.httpServer.close();report.status=report.runs.every(r=>r.status==='PASS')?'PASS':'FAIL';await writeFile(dir+'/report.json',JSON.stringify(report,null,2));}
