/** Bounded source-label arrivals. Controlled holdings/deal are explicitly not natural acquisition. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createServer,build,preview} from 'vite';
import {chromium} from 'playwright';
import {tapUI,waitScene,tapMenuAction} from './ui.mjs';
const dir=process.env.SOURCE_DIR||'shots/source-impact',baseline=!!process.env.SOURCE_BASELINE;await mkdir(dir,{recursive:true});
const report={source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),baseline,scope:'Controlled legacy group-upgrade-v1 normal stage index19 holdings and public hand for multi-source trace; current basic-choice b10 controlled shelf reused only for read10. No natural rate, six-hero, device/FPS/audio/human acceptance.',cases:[]};
const ssr=await createServer({server:{middlewareMode:true},logLevel:'error'});let fixtures=[];
try{const {createRun,applyCommand}=await ssr.ssrLoadModule('/src/domain/run.ts'),{r2CreateJoker}=await ssr.ssrLoadModule('/src/domain/r2Run.ts'),{r2DisabledCards}=await ssr.ssrLoadModule('/src/domain/r2Chapter.ts'),{makeCheckpoint,readCheckpoint}=await ssr.ssrLoadModule('/src/application/checkpoint.ts');
const send=(s,action)=>{const r=applyCommand(s,{runId:s.runId,commandId:s.runId+'/command/'+(s.commandSeq+1),expectedSeq:s.commandSeq,action});assert.ok(r.ok,r.code);assert.ok(readCheckpoint(makeCheckpoint(r.state,[])).ok);return r.state;};
let s=createRun({seed:'source-impact-controlled',runId:'source-impact-controlled',characterId:'amo',rulesVersion:'r2',r2Profile:'group-upgrade-v1',modeConfig:{mode:'standard',difficulty:0,challengeId:null,programsEnabled:false}});s.jokers=['b05','a11','b06','f09'].map(id=>r2CreateJoker(id,id,8,undefined,s));Object.assign(s,{chapter:7,stageIndex:19,phase:'stage-ready',shop:null,boss:{definitionId:'B13',disabledSuit:null},seenBossIds:['B01','B02','B03','B04','B05','B06','B13']});s=send(s,{type:'EnterStage'});const ids=['spades-9','hearts-9','clubs-9','clubs-13','diamonds-13'];s.handOrder=[...ids,'spades-12','hearts-12','diamonds-7'];s.drawPile=s.deckInstances.map(c=>c.id).filter(id=>!s.handOrder.includes(id));s.stage.disabledIds=r2DisabledCards(s.stage.boss,s.stageIndex,s.handOrder.map(id=>s.deckInstances.find(c=>c.id===id)));const cp=makeCheckpoint(s,[]);assert.ok(readCheckpoint(cp).ok);const expected=send(s,{type:'PlayHand',selectedIds:ids});assert.equal(expected.phase,'await-input');fixtures.push({name:'chain',cp,ids,expected});
const prior=JSON.parse(await readFile('docs/production/evidence/growth-payoff-2026-10-09/current-controlled-fixture.json','utf8'));const readCP=makeCheckpoint(prior.expected[0],[]);assert.ok(readCheckpoint(readCP).ok);fixtures.push({name:'read',cp:readCP,ids:prior.ids[1],expected:prior.expected[1]});await writeFile(dir+'/fixtures.json',JSON.stringify(fixtures,null,2));}finally{await ssr.close();}
await build({mode:'e2e',build:{outDir:dir+'/build'},logLevel:'error'});const server=await preview({build:{outDir:dir+'/build'},preview:{host:'127.0.0.1',port:5402,strictPort:true},logLevel:'error'}),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--disable-gpu','--disable-software-rasterizer']});report.browser=browser.version();
const saved=p=>p.evaluate(async()=>{const c=window.__harness.game.registry.get('runController');return {state:c.state,journal:c.journal,storage:await c.store.read()};}),settled=p=>p.waitForFunction(()=>{const s=window.__harness.game.scene.getScene('game');return s.scene.isActive()&&s.ready&&!s.playing&&!s.presentation&&s.cardViews.every(v=>!v.dealing&&!s.tweens.isTweening(v.container));});
const shot=(p,name)=>p.screenshot({path:dir+'/'+name+'.png',fullPage:true,scale:'css'});
const observe=async p=>p.evaluate(()=>{window.__sourceObserved=[];window.__sourceWatch=setInterval(()=>{const s=window.__harness.game.scene.getScene('game');if(!s?.scene.isActive())return;const walk=list=>list.flatMap(o=>[o,...(o.list?walk(o.list):[])]);for(const label of walk(s.children.list).filter(o=>o.name==='source/impact')){const cue=label.getData('sourceImpact');if(window.__sourceObserved.some(o=>o.cue.eventId===cue.eventId))continue;const v=s.jokerViews.get(cue.instanceId),target=s.settledCards.get(cue.targetId)??s.cardViews.find(v=>v.card.id===cue.targetId);window.__sourceObserved.push({cue,text:label.text,font:label.style.fontSize,bounds:label.getBounds(),frame:v.getData('frame').getBounds(),originalVisible:v.getData('valueLabel').visible,targetGlow:target?.faceGlow?.alpha,phase:s.scoreTotal.getData('eventPhase'),scoreEvent:s.scoreTotal.getData('eventId'),duplicateFloats:walk(s.children.list).filter(o=>o.type==='Text'&&['18px','22px'].includes(o.style.fontSize)&&o.style.fontStyle==='bold'&&o.text===s.operationText(s.presentation.score.events.find(e=>e.eventId===cue.eventId))).length});}},25);});
const live=(p,kind)=>p.waitForFunction(kind=>{const s=window.__harness.game.scene.getScene('game'),walk=list=>list.some(o=>o.name==='source/impact'&&(!kind||o.getData('sourceImpact').kind===kind)||o.list&&walk(o.list));return walk(s.children.list);},kind,{timeout:30000,polling:25});
const clean=p=>p.evaluate(()=>{const s=window.__harness.game.scene.getScene('game'),walk=list=>list.some(o=>o.name==='source/impact'||o.list&&walk(o.list));return !walk(s.children.list)&&[...s.jokerViews.values()].every(v=>v.getData('valueLabel')?.visible);});
const imp=async(p,cp)=>{await p.locator('.run-menu-toggle').click();const sec=p.getByText('进度与存档',{exact:true}).locator('..');if(!await sec.evaluate(e=>e.open))await sec.locator('summary').click();const fc=p.waitForEvent('filechooser');await p.getByRole('button',{name:'导入本局',exact:true}).click();await(await fc).setFiles({name:'source.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cp))});await waitScene(p,'game');await settled(p);const start=p.getByRole('button',{name:'开始出牌',exact:true});if(await start.count())await start.click();await settled(p);};
const specs=baseline?[{width:1366,height:768,mode:'reduce',fixture:'chain'},{width:390,height:740,mode:'reduce',fixture:'chain'}]:[{width:1366,height:768,mode:'normal',fixture:'chain'},{width:390,height:740,mode:'normal',fixture:'chain'},{width:390,height:740,mode:'fast',fixture:'chain'},{width:390,height:740,mode:'reduce',fixture:'chain'},{width:390,height:740,mode:'normal',fixture:'read'}];
try{for(const spec of specs){if(process.env.SOURCE_CASES&&!process.env.SOURCE_CASES.split(',').includes(spec.width+'-'+spec.mode+'-'+spec.fixture))continue;const row={spec,status:'RUNNING'};report.cases.push(row);const f=fixtures.find(f=>f.name===spec.fixture),p=await browser.newPage({viewport:{width:spec.width,height:spec.height},hasTouch:spec.width<800,reducedMotion:spec.mode==='reduce'?'reduce':'no-preference'});p.on('dialog',d=>d.accept());try{await p.goto('http://127.0.0.1:5402/?harness=1');await waitScene(p,'title');await imp(p,f.cp);assert.deepEqual((await saved(p)).state,f.cp.state);await observe(p);for(const id of f.ids)await tapUI(p,'game','card/'+id);await tapUI(p,'game','action/play');await p.waitForFunction(seq=>window.__harness.game.registry.get('runController').state.commandSeq>seq,f.cp.state.commandSeq);
if(spec.mode==='fast')await tapMenuAction(p,'快进当前手');
if(baseline){for(const [source,name] of [['b05','arrival'],['a11','target'],['f09','multiply']]){const e=f.expected.lastTrace.events.find(e=>e.sourceDefinitionId===source);await p.waitForFunction(id=>{const s=window.__harness.game.scene.getScene('game');return s.scoreTotal.getData('eventId')===id&&s.scoreTotal.getData('eventPhase')==='impact';},e.eventId,{timeout:30000,polling:25});await shot(p,spec.width+'-chain-'+name);}}
if(spec.mode==='normal'&&!baseline){await live(p,spec.fixture==='read'?'read-heat':'heat');await shot(p,spec.width+'-'+spec.fixture+'-arrival');if(spec.fixture==='chain'){await live(p,'retrigger');await shot(p,spec.width+'-chain-target');const multiply=f.expected.lastTrace.events.find(e=>e.sourceDefinitionId==='f09'&&e.operation==='multiply-multiplier');assert.ok(multiply);await p.waitForFunction(id=>{const s=window.__harness.game.scene.getScene('game');return s.scoreTotal.getData('eventId')===id&&s.scoreTotal.getData('eventPhase')==='impact';},multiply.eventId,{timeout:30000,polling:25});await shot(p,spec.width+'-chain-multiply');}}
await settled(p);row.after=await saved(p);assert.deepEqual(row.after.state,f.expected);assert.deepEqual(row.after.storage.current.state,f.expected);assert.deepEqual(row.after.storage.current.journal,row.after.journal);assert.ok(await clean(p));row.observed=await p.evaluate(()=>window.__sourceObserved);if(!baseline&&spec.mode!=='fast'){assert.ok(row.observed.length);for(const o of row.observed){assert.equal(o.phase,'impact');assert.equal(o.scoreEvent,o.cue.eventId);assert.equal(o.originalVisible,false);assert.equal(o.duplicateFloats,0,'no duplicate source or target float for a mounted cue');assert.equal(o.font,'14px');assert.ok(o.bounds.x>=o.frame.x-1&&o.bounds.x+o.bounds.width<=o.frame.x+o.frame.width+1,'actual label horizontal containment');assert.ok(o.bounds.y>=o.frame.y-1&&o.bounds.y+o.bounds.height<=o.frame.y+o.frame.height+1,'actual label vertical containment');if(o.cue.kind==='retrigger')assert.ok(o.targetGlow>0,'actual matching target is illuminated');}if(spec.fixture==='chain'){assert.ok(row.observed.some(o=>o.cue.instanceId==='b05'));assert.ok(row.observed.some(o=>o.cue.instanceId==='a11'));assert.ok(row.observed.some(o=>o.cue.instanceId==='b06'));}else assert.ok(row.observed.some(o=>o.text==='读热10'||o.text==='读+10'));}await shot(p,spec.width+'-'+spec.mode+'-'+spec.fixture+'-settled');
if(!baseline&&spec.mode==='normal'&&spec.width===1366){row.interruptions=[];for(const mode of ['resize','cancel','background-controlled']){await tapMenuAction(p,'回看上一手');await live(p);if(mode==='resize')await p.setViewportSize({width:390,height:740});else if(mode==='cancel')await tapMenuAction(p,'快进当前手');else await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await settled(p);assert.deepEqual(await saved(p),row.after);assert.ok(await clean(p));row.interruptions.push({mode,status:'PASS',stateJournalStorageEqual:true});if(mode==='resize')await p.setViewportSize({width:1366,height:768});}}
if(!baseline&&spec.mode==='reduce'&&spec.fixture==='chain'){row.boundaries=[];for(const viewport of [{width:320,height:740},{width:740,height:390}]){await p.setViewportSize(viewport);await settled(p);await tapMenuAction(p,'回看上一手');await live(p);await shot(p,viewport.width+'-same-saved-hand');await tapMenuAction(p,'快进当前手');await settled(p);assert.deepEqual(await saved(p),row.after);assert.ok(await clean(p));row.boundaries.push({viewport,status:'PASS'});}}
await p.reload();await waitScene(p,'title');assert.deepEqual(await saved(p),row.after);row.status='PASS';}catch(e){row.status='FAIL';row.error=String(e);row.stack=e.stack;row.observed=await p.evaluate(()=>window.__sourceObserved??[]);await shot(p,spec.width+'-'+spec.mode+'-'+spec.fixture+'-FAIL');throw e;}finally{await p.close();await writeFile(dir+'/report.json',JSON.stringify(report,null,2));}}report.status='PASS';}catch(e){report.status='FAIL';report.error=String(e);process.exitCode=1;}finally{await writeFile(dir+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,error:report.error,cases:report.cases.map(c=>({spec:c.spec,status:c.status,error:c.error,observed:c.observed?.length}))}));await browser.close();await new Promise(r=>server.httpServer.close(r));}
